//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef _CKDAAPParser_h
#define _CKDAAPParser_h

@import Foundation;

@interface _CKDAAPParser : NSObject

/* class methods */
+ (id)sharedInstance;
+ (id)decodeData:(id)_data;
+ (id)decodeHexString:(id)_hexString;
+ (id)typeForDRCPValueType:(int)_forDRCPValueType;

/* instance methods */
- (unsigned long long)SwapInt64BigToHost:(const char *)_swapInt64BigToHost size:(long long)_size;
- (id)parseGetSpeakersResponse:(const char *)_getSpeakersResponse count:(long long)_count;
- (id)parseBrowseResults:(const char *)_browseResults count:(long long)_count;
- (id)parseContentCodes:(const char *)_contentCodes count:(long long)_count;
- (id)parseContentCollectionDict:(const char *)_contentCollectionDict count:(long long)_count;
- (id)parseControlPromptCollection:(const char *)_controlPromptCollection count:(long long)_count;
- (id)parseControlPromptResponse:(const char *)_controlPromptResponse count:(long long)_count;
- (id)parseDACPPropertyResponse:(const char *)_dacppropertyResponse count:(long long)_count;
- (id)parseDeletedIDsList:(const char *)_deletedIDsList count:(long long)_count;
- (void)parseDict:(const char *)_dict size:(long long)_size intoDict:(id)_dict;
- (id)parseError:(const char *)_error count:(long long)_count;
- (id)parseListingCollection:(const char *)_listingCollection count:(long long)_count capacity:(int)_capacity;
- (id)parseListingHeader:(const char *)_listingHeader count:(long long)_count;
- (id)parseListingItem:(const char *)_listingItem count:(long long)_count;
- (id)parseLogin:(const char *)_login count:(long long)_count;
- (id)parseMACAddressListing:(const char *)_macaddressListing count:(long long)_count;
- (id)parseServerInfo:(const char *)_serverInfo count:(long long)_count;
- (id)parseUTF8String:(const char *)_utf8String length:(long long)_length;
- (id)parseUnicodeCharacter:(const char *)_unicodeCharacter count:(long long)_count;
- (id)processFlavor:(const char *)_flavor size:(long long)_size;
- (id)processFlavors:(const char *)_flavors size:(long long)_size;
- (id)processResponseCode:(unsigned int)_responseCode bytes:(const char *)_bytes count:(long long)_count;
- (id)processXMLContent:(const char *)_xmlcontent count:(long long)_count;
- (void)setBool:(const char *)_bool size:(long long)_size inDict:(id)_dict forKey:(id)_key;
- (void)setDate:(const char *)_date size:(long long)_size inDict:(id)_dict forKey:(id)_key;
- (void)setFloat32:(const char *)_float32 size:(long long)_size inDict:(id)_dict forKey:(id)_key;
- (void)setSInt16:(const char *)_sint16 size:(long long)_size inDict:(id)_dict forKey:(id)_key;
- (void)setSInt8:(const char *)_sint8 size:(long long)_size inDict:(id)_dict forKey:(id)_key;
- (void)setString:(const char *)_string size:(long long)_size inDict:(id)_dict forKey:(id)_key;
- (void)setUInt16:(const char *)_uint16 size:(long long)_size inDict:(id)_dict forKey:(id)_key;
- (void)setUInt32:(const char *)_uint32 size:(long long)_size inDict:(id)_dict forKey:(id)_key;
- (void)setUInt64:(const char *)_uint64 size:(long long)_size inDict:(id)_dict forKey:(id)_key;
- (void)setUInt8:(const char *)_uint8 size:(long long)_size inDict:(id)_dict forKey:(id)_key;
- (void)unknownCode:(unsigned int)_code bytes:(const char *)_bytes size:(long long)_size;

@end

#endif /* _CKDAAPParser_h */
