//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef _CKPurchaseQueueDelegateWrapper_h
#define _CKPurchaseQueueDelegateWrapper_h

@import Foundation;

#include "CKDialogContext.h"
#include "CKPurchaseQueueDelegate-Protocol.h"

@interface _CKPurchaseQueueDelegateWrapper : NSObject <CKPurchaseQueueDelegate>

@property (readonly) CKDialogContext *dialogContext;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithDialogContext:(id)_dialogContext;
- (id)purchaseQueue:(id)_queue dialogContextForTransaction:(id)_contextForTransaction;

@end

#endif /* _CKPurchaseQueueDelegateWrapper_h */
