//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef AccountObserver_Protocol_h
#define AccountObserver_Protocol_h

@import Foundation;

@protocol AccountObserver <NSObject>

@required

/* required instance methods */
- (void)storeClient:(id)_client changedPrimaryAccount:(id)_primaryAccount;

@optional

@end

#endif /* AccountObserver_Protocol_h */
