//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef CKAccountObserver_Protocol_h
#define CKAccountObserver_Protocol_h

@import Foundation;

@protocol CKAccountObserver <NSObject>

@required

/* required instance methods */
- (void)accountStore:(id)_store primaryAccountChanged:(id)_accountChanged;

@optional

@end

#endif /* CKAccountObserver_Protocol_h */
