//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef CKAuthenticationContext_h
#define CKAuthenticationContext_h

@import Foundation;

#include "CKAuthenticationSettings.h"
#include "CKDialogContext.h"
#include "CKStoreClient.h"

@interface CKAuthenticationContext : NSObject <NSCopying>

@property (readonly) CKStoreClient *storeClient;
@property (retain) CKDialogContext *dialogContext;
@property (retain) CKAuthenticationSettings *settings;

/* class methods */
+ (id)authenticationContextForStoreClient:(id)_contextForStoreClient;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)_zone;
- (id)initWithStoreClient:(id)_storeClient;
- (void)_authenticateWithDialog:(id)_withDialog completionHandler:(id /* block */)_handler;
- (void)_finishAuthWithResult:(id)_authWithResult error:(id)_error completionHandler:(id /* block */)_handler;
- (void)_signChallenge:(id)_challenge withCaller:(id)_caller completionHandler:(id /* block */)_handler;
- (id)_viewControllerForAuthentication;
- (void)authenticateWithDialog:(id)_withDialog completionHandler:(id /* block */)_handler;
- (void)signChallenge:(id)_challenge withCompletionHandler:(id /* block */)_completionHandler;

@end

#endif /* CKAuthenticationContext_h */
