//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef CKBag_h
#define CKBag_h

@import Foundation;

#include "CKStoreClient.h"

@interface CKBag : NSObject

@property (readonly, nonatomic) CKStoreClient *storeClient;

/* class methods */
+ (id)valueForKey:(id)_forKey;
+ (id)urlForKey:(id)_key;
+ (id)bagWithType:(unsigned long long)_withType;
+ (id)productionBag;
+ (id)sandboxBox;

/* instance methods */
- (signed char)isValid;
- (id)dictionary;
- (id)valueForKey:(id)_forKey;
- (id)urlForKey:(id)_key;
- (id)initWithStoreClient:(id)_storeClient;
- (id)initWithBagType:(unsigned long long)_bagType;
- (id)loadBagAndObserveUpdatesWithHandler:(id /* block */)_handler;
- (signed char)regexWithKey:(id)_withKey matchesString:(id)_string;
- (signed char)sendGUIDWithURL:(id)_url;
- (void)startUpdate;
- (void)stopObservingBagWithObserver:(id)_observer;
- (id)storefrontURL;
- (signed char)urlIsTrusted:(id)_isTrusted;

@end

#endif /* CKBag_h */
