//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef CKClientDispatch_h
#define CKClientDispatch_h

@import Foundation;

@protocol OS_dispatch_queue; // @import Dispatch;

@interface CKClientDispatch : NSObject {
    /* instance variables */
    NSObject<OS_xpc_object> *serviceXPCConnection;
    NSLock *serviceConnectionLock;
    NSObject<OS_xpc_object> *agentXPCConnection;
    NSLock *agentConnectionLock;
    NSObject<OS_dispatch_queue> *mQueue;
}

/* class methods */
+ (id)sharedInstance;

/* instance methods */
- (void)dealloc;
- (id)init;
- (void)cancelCallback:(id)_callback;
- (id)_sendMessage:(id)_message callbackQueue:(id)_queue callbackBlock:(id /* block */)_block;
- (void)_sendMessage:(id)_message replyQueue:(id)_queue replyBlock:(id /* block */)_block;
- (id)_syncInvokeSelector:(id)_invokeSelector ofClass:(id)_class withObject:(id)_object;
- (void)invokeSelector:(id)_selector ofClass:(id)_class;
- (void)invokeSelector:(id)_selector ofClass:(id)_class replyQueue:(id)_queue replyBlock:(id /* block */)_block;
- (void)invokeSelector:(id)_selector ofClass:(id)_class withObject:(id)_object;
- (id)invokeSelector:(id)_selector ofClass:(id)_class withObject:(id)_object callbackQueue:(id)_queue callbackBlock:(id /* block */)_block;
- (void)invokeSelector:(id)_selector ofClass:(id)_class withObject:(id)_object replyQueue:(id)_queue replyBlock:(id /* block */)_block;

@end

#endif /* CKClientDispatch_h */
