//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef CKDemoAccount_h
#define CKDemoAccount_h

@import Foundation;

@interface CKDemoAccount : NSObject <NSCopying, NSSecureCoding>

@property (readonly) NSString *username;
@property (readonly) NSString *password;
@property signed char autoLogin;

/* class methods */
+ (signed char)supportsSecureCoding;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)_zone;
- (void)encodeWithCoder:(id)_withCoder;
- (id)initWithCoder:(id)_coder;
- (id)initWithUsername:(id)_username password:(id)_password;

@end

#endif /* CKDemoAccount_h */
