//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef CKDialog_h
#define CKDialog_h

@import Foundation;

@interface CKDialog : NSObject <NSCopying, NSSecureCoding>

@property (retain, nonatomic) NSMutableDictionary *buttonActions;
@property signed char kind;
@property (copy) NSString *messageText;
@property (copy) NSString *informativeText;
@property signed char defaultButton;
@property (copy) NSString *okButtonTitle;
@property (copy) NSString *cancelButtonTitle;
@property (copy) NSString *otherButtonTitle;
@property (copy) NSString *checkboxTitle;
@property signed char checkboxChecked;
@property signed char showsHelp;
@property (copy) NSString *helpAnchor;

/* class methods */
+ (signed char)supportsSecureCoding;
+ (id)_dialogFromResponseDictionary:(id)_fromResponseDictionary;
+ (id)dialogWithError:(id)_withError;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)_zone;
- (id)description;
- (id)init;
- (void)encodeWithCoder:(id)_withCoder;
- (id)initWithCoder:(id)_coder;
- (id)actionForButton:(signed char)_forButton;
- (void)setAction:(id)_action forButton:(signed char)_button;

@end

#endif /* CKDialog_h */
