//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef CKDownload_h
#define CKDownload_h

@import Foundation;

#include "CKDownloadStatus.h"
#include "CKStoreClient.h"

@interface CKDownload : NSObject <NSSecureCoding>

@property (readonly) CKStoreClient *storeClient;
@property (readonly) NSURL *cancelURL;
@property (readonly) NSArray *assets;
@property (copy) NSString *downloadQueueIdentifier;
@property (retain) CKDownloadStatus *status;
@property (readonly) NSString *identifier;
@property (readonly) NSString *itemIdentifier;
@property (readonly) NSString *versionIdentifier;
@property (readonly) unsigned long long primaryAssetSize;
@property (readonly) NSDictionary *metadata;
@property (copy) NSString *installedVersionIdentifier;
@property unsigned char priority;
@property signed char decryptAsset;
@property signed char verifyAsset;

/* class methods */
+ (signed char)supportsSecureCoding;

/* instance methods */
- (id)description;
- (void)encodeWithCoder:(id)_withCoder;
- (id)initWithCoder:(id)_coder;
- (void)resume;
- (void)finish;
- (void)pause;
- (void)cancel;
- (id)_initWithStoreClient:(id)_withStoreClient purchaseResponseDictionary:(id)_responseDictionary;

@end

#endif /* CKDownload_h */
