//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef CKExtensionSearchController_h
#define CKExtensionSearchController_h

@import Foundation;

@interface CKExtensionSearchController : NSObject

/* class methods */
+ (void)urlToSearchForExtensionsWithIdentifier:(id)_extensionsWithIdentifier completion:(id /* block */)_completion;

@end

#endif /* CKExtensionSearchController_h */
