//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef CKItemLookupRequest_h
#define CKItemLookupRequest_h

@import Foundation;

@interface CKItemLookupRequest : NSObject {
    /* instance variables */
    NSArray *_bundleIdentifiers;
    NSArray *_adamIdentifiers;
    NSString *_keyProfile;
    id /* block */ _lookupCallbackBlock;
}

@property (retain, nonatomic) NSString *preferredLanguage;
@property signed char platformOverride;

/* instance methods */
- (signed char)start;
- (id)parameters;
- (id)initWithBundleIdentifiers:(id)_bundleIdentifiers adamIDs:(id)_ids keyProfile:(id)_profile;
- (signed char)startWithLookupBlock:(id /* block */)_withLookupBlock;

@end

#endif /* CKItemLookupRequest_h */
