//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef CKItem_h
#define CKItem_h

@import Foundation;

@interface CKItem : NSObject {
    /* instance variables */
    NSDictionary *_properties;
}

@property (readonly, nonatomic) NSNumber *ITunesStoreIdentifier;
@property (readonly, nonatomic) NSString *developerName;
@property (readonly, nonatomic) NSString *itemTitle;
@property (readonly, nonatomic) NSURL *viewItemURL;
@property (readonly, nonatomic) float averageUserRating;
@property (readonly, nonatomic) long long numberOfUserRatings;
@property (readonly, nonatomic) NSArray *thumbnailImages;

/* instance methods */
- (id)description;
- (id)bundleIdentifier;
- (id)bundleVersion;
- (id)valueForProperty:(id)_forProperty;
- (id)releaseDate;
- (id)buyParameters;
- (id)itemKind;
- (id)collectionName;
- (id)mediaKind;
- (id)_tellAFriendDictionary;
- (id)initWithItemDictionary:(id)_itemDictionary;
- (id)priceDisplay;
- (id)rawItemDictionary;
- (id)sendGiftURL;
- (id)viewReviewsURL;

@end

#endif /* CKItem_h */
