//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef CKItemArtworkImage_h
#define CKItemArtworkImage_h

@import Foundation;

@interface CKItemArtworkImage : NSObject {
    /* instance variables */
    signed char _prerendered;
    NSURL *_url;
}

@property (readonly, nonatomic) long long height;
@property (readonly, nonatomic) long long width;
@property (readonly, nonatomic) NSString *imageKind;
@property (readonly, nonatomic) NSURL *URL;

/* instance methods */
- (id)description;
- (unsigned long long)hash;
- (signed char)isEqual:(id)_equal;
- (id)initWithArtworkDictionary:(id)_artworkDictionary;

@end

#endif /* CKItemArtworkImage_h */
