//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef CKLicenseAgreementSheet_h
#define CKLicenseAgreementSheet_h

@import AppKit;
@import Foundation;

@interface CKLicenseAgreementSheet : NSWindowController {
    /* instance variables */
    NSButton *_agreeButton;
    NSButton *_cancelButton;
    NSTextView *_textView;
    NSTextField *_titleField;
    long long _sheetReturnCode;
}

@property (weak) NSWindow *hostWindow;
@property (copy) NSArray *productKeys;

/* instance methods */
- (id)init;
- (void)cancel:(id)_cancel;
- (id)_nibName;
- (void)didEndSheet:(id)_endSheet returnCode:(long long)_code contextInfo:(void *)_info;
- (void)_dismissPanelWithCode:(long long)_panelWithCode;
- (id)_textValueKey;
- (id)_titleValueKey;
- (void)agree:(id)_agree;
- (void)displaySheetWithTitle:(id)_sheetWithTitle content:(id)_content onWindow:(id)_window replyBlock:(id /* block */)_block;
- (id)initWithUpdateProductKeys:(id)_updateProductKeys;
- (signed char)userAgreedToAllAgreementsWithWindowForSheet:(id)_windowForSheet;

@end

#endif /* CKLicenseAgreementSheet_h */
