//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef CKMachineAuthorizationContext_h
#define CKMachineAuthorizationContext_h

@import Foundation;

#include "CKDialogContext.h"
#include "CKStoreClient.h"
#include "CKStoreRequestDelegate-Protocol.h"

@interface CKMachineAuthorizationContext : NSObject <CKStoreRequestDelegate>

@property (readonly) CKStoreClient *storeClient;
@property (retain) CKDialogContext *dialogContext;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)machineAuthorizationContextWithStoreClient:(id)_authorizationContextWithStoreClient;

/* instance methods */
- (id)initWithStoreClient:(id)_storeClient;
- (id)_authenticationContextWithAppleID:(id)_contextWithAppleID;
- (id)_requestBodyForAccount:(id)_bodyForAccount bagURLKey:(id)_urlkey;
- (void)_runRequestWithAccount:(id)_account bagURLKey:(id)_urlkey authenticationContext:(id)_context completionHandler:(id /* block */)_handler;
- (void)authorizeMachineWithAppleID:(id)_machineWithAppleID completionHandler:(id /* block */)_handler;
- (void)deauthorizeMachineWithCompletionHandler:(id /* block */)_machineWithCompletionHandler;
- (void)storeRequest:(id)_request didAuthenticateAccount:(id)_authenticateAccount;

@end

#endif /* CKMachineAuthorizationContext_h */
