//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef CKPrivacyController_h
#define CKPrivacyController_h

@import Foundation;

@interface CKPrivacyController : NSObject

/* class methods */
+ (void)_acknowledgePrivacyConsentForIdentifiers:(id)_privacyConsentForIdentifiers account:(id)_account;
+ (signed char)_mergeLocalPrivacyConsentWithAccount:(id)_localPrivacyConsentWithAccount;
+ (signed char)_shouldDisableGDPR;
+ (void)acknowledgePrivacyLinkForIdentifier:(id)_privacyLinkForIdentifier storeClient:(id)_client;
+ (signed char)shouldDisplayPrivacyLinkForIdentifier:(id)_displayPrivacyLinkForIdentifier storeClient:(id)_client;

@end

#endif /* CKPrivacyController_h */
