//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef CKPurchaseQueue_h
#define CKPurchaseQueue_h

@import Foundation;

#include "_CKPurchaseQueueDelegateWrapper.h"

@interface CKPurchaseQueue : NSObject

@property (retain) _CKPurchaseQueueDelegateWrapper *delegateWrapper;
@property (readonly) NSString *identifier;
@property (readonly) NSArray *transactions;

/* class methods */
+ (void)_cancelTransactionWithResumeData:(id)_transactionWithResumeData;
+ (void)_resumeTransactionWithResumeData:(id)_transactionWithResumeData storeResponse:(id)_response;
+ (id)purchaseQueueForIdentifier:(id)_queueForIdentifier;

/* instance methods */
- (void)setDelegate:(id)_delegate;
- (id)_initWithIdentifier:(id)_withIdentifier;
- (void)_updateTransactions:(id)_transactions;
- (id)addPurchase:(id)_purchase;
- (id)addPurchases:(id)_purchases;
- (id)addTransactionObserver:(id)_transactionObserver;
- (void)cancelTransaction:(id)_transaction;
- (void)cancelTransactionGroup:(id)_transactionGroup;
- (void)removeTransactionObserver:(id)_transactionObserver;
- (void)setDialogContext:(id)_dialogContext;

@end

#endif /* CKPurchaseQueue_h */
