//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef CKPushNotificationManager_h
#define CKPushNotificationManager_h

@import Foundation;

#include "CKStoreClient.h"

@protocol CKPushNotificationManagerDelegate;

@interface CKPushNotificationManager : NSObject

@property (readonly, nonatomic) CKStoreClient *storeClient;
@property (weak) id <CKPushNotificationManagerDelegate> delegate;

/* class methods */
+ (id)sharedManager;
+ (id)pushNotificationManagerForStoreClient:(id)_notificationManagerForStoreClient;

/* instance methods */
- (signed char)start;
- (signed char)stop;
- (id)initWithStoreClient:(id)_storeClient;
- (signed char)isRegisteredForAccount:(id)_registeredForAccount andMask:(long long)_mask;
- (void)_sendChangedToDelegate;
- (void)_sendErrorToDelegate:(id)_errorToDelegate;
- (void)_sendSuccessToDelegate;
- (signed char)checkEnabledMediaTypes;
- (void)disableAutoDownloadAtSignOutWithCompletionHandler:(id /* block */)_autoDownloadAtSignOutWithCompletionHandler;
- (void)disableAutoDownloadWithCompletionHandler:(id /* block */)_autoDownloadWithCompletionHandler;
- (void)enableAutoDownloadAtSignInWithCompletionHandler:(id /* block */)_autoDownloadAtSignInWithCompletionHandler;
- (void)enableAutoDownloadWithCompletionHandler:(id /* block */)_autoDownloadWithCompletionHandler;
- (void)getEnabledMedaTypesWithCompletionHandler:(id /* block */)_enabledMedaTypesWithCompletionHandler;
- (signed char)isRegisteredForAccount:(id)_registeredForAccount;
- (void)registerDeviceTokenWithCompletionHandler:(id /* block */)_deviceTokenWithCompletionHandler;
- (signed char)registerPushToken;
- (signed char)startAtSignIn;
- (signed char)stopAtSignOut;

@end

#endif /* CKPushNotificationManager_h */
