//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef CKPurchaseResponse_h
#define CKPurchaseResponse_h

@import Foundation;

#include "CKStoreClient.h"
#include "CKStoreResponse.h"

@interface CKPurchaseResponse : NSObject <NSCopying, NSSecureCoding>

@property (retain) CKStoreClient *storeClient;
@property (retain) CKStoreResponse *storeResponse;
@property (readonly) NSError *error;
@property (readonly) NSArray *downloads;
@property (readonly) NSDictionary *metrics;

/* class methods */
+ (signed char)supportsSecureCoding;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)_zone;
- (void)encodeWithCoder:(id)_withCoder;
- (id)initWithCoder:(id)_coder;
- (id)_initWithStoreClient:(id)_withStoreClient response:(id)_response;
- (id)_storeResponse;

@end

#endif /* CKPurchaseResponse_h */
