//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef CKRestoreDownloadsRequest_h
#define CKRestoreDownloadsRequest_h

@import Foundation;

#include "SSRequest.h" // @import StoreFoundation;

@class ISServiceProxy; // @import StoreFoundation;

@interface CKRestoreDownloadsRequest : SSRequest {
    /* instance variables */
    NSArray *_archivedFiles;
    ISServiceProxy *_serviceProxy;
}

@property signed char userInitiated;

/* instance methods */
- (id)initWithArchivedFiles:(id)_archivedFiles;
- (signed char)issueRequestForIdentifier:(id)_requestForIdentifier error:(id *)_error;

@end

#endif /* CKRestoreDownloadsRequest_h */
