//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef CKServiceInterface_h
#define CKServiceInterface_h

#include "ISServiceProxy.h" // @import StoreFoundation;

@interface CKServiceInterface : ISServiceProxy

@end

#endif /* CKServiceInterface_h */
