//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef CKSoftwareMapObserver_h
#define CKSoftwareMapObserver_h

@import Foundation;

@protocol OS_dispatch_queue; // @import Dispatch;
@protocol ISSoftwareMapObserver; // @import StoreFoundation;

@interface CKSoftwareMapObserver : NSObject <ISSoftwareMapObserver>

@property (copy) id /* block */ block;
@property (retain) NSObject<OS_dispatch_queue> *queue;

/* instance methods */
- (void)softwareProduct:(id)_product updatedState:(long long)_state;

@end

#endif /* CKSoftwareMapObserver_h */
