//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef CKStoreAccountSettingsContext_h
#define CKStoreAccountSettingsContext_h

@import Foundation;

#include "CKDialogContext.h"
#include "CKStoreAccount.h"

@protocol AMSURLProtocolDelegate; // @import AppleMediaServices;

@interface CKStoreAccountSettingsContext : NSObject <NSURLSessionDelegate, AMSURLProtocolDelegate>

@property (readonly) CKStoreAccount *account;
@property (retain) CKDialogContext *dialogContext;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)contextForStoreAccount:(id)_forStoreAccount;

/* instance methods */
- (void)AMSURLSession:(id)_amsurlsession task:(id)_task handleAuthenticateRequest:(id)_authenticateRequest completion:(id /* block */)_completion;
- (void)AMSURLSession:(id)_amsurlsession task:(id)_task handleDialogRequest:(id)_dialogRequest completion:(id /* block */)_completion;
- (id)_bag;
- (void)_setEnabledAutomaticDownloadMediaKinds:(long long)_enabledAutomaticDownloadMediaKinds withCompletionHandler:(id /* block */)_completionHandler;
- (void)_setEnabledAutomaticDownloadMediaKinds:(long long)_enabledAutomaticDownloadMediaKinds withURL:(id)_url bodyPlist:(id)_plist completionHandler:(id /* block */)_handler;
- (void)disableAutomaticDownloadForMediaKinds:(long long)_automaticDownloadForMediaKinds withCompletionHandler:(id /* block */)_completionHandler;
- (void)eligibilityForService:(long long)_forService completionHandler:(id /* block */)_handler;
- (void)enableAutomaticDownloadForMediaKinds:(long long)_automaticDownloadForMediaKinds withCompletionHandler:(id /* block */)_completionHandler;
- (void)enabledAutomaticDownloadMediaKindsWithCompletionHandler:(id /* block */)_automaticDownloadMediaKindsWithCompletionHandler;
- (id)initWithStoreAccount:(id)_storeAccount;
- (void)passwordSettingsWithCompletionHandler:(id /* block */)_settingsWithCompletionHandler;
- (void)setPasswordSettings:(id)_passwordSettings withCompletionHandler:(id /* block */)_completionHandler;
- (void)setTouchIDState:(long long)_touchIDState withCompletionHandler:(id /* block */)_completionHandler;
- (long long)touchIDState;

@end

#endif /* CKStoreAccountSettingsContext_h */
