//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef CKStoreAction_h
#define CKStoreAction_h

@import Foundation;

@interface CKStoreAction : NSObject <NSCopying, NSSecureCoding>

@property (readonly, nonatomic) unsigned char action;
@property (readonly, nonatomic) NSDictionary *actionParameters;

/* class methods */
+ (signed char)supportsSecureCoding;
+ (id)_actionFromResponseDictionary:(id)_fromResponseDictionary;
+ (id)stringForActionType:(unsigned char)_forActionType;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)_zone;
- (id)description;
- (void)encodeWithCoder:(id)_withCoder;
- (id)initWithCoder:(id)_coder;
- (id)initWithAction:(unsigned char)_action parameters:(id)_parameters;

@end

#endif /* CKStoreAction_h */
