//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef CKStoreDAAPLibrary_h
#define CKStoreDAAPLibrary_h

@import Foundation;

#include "CKAccountObserver-Protocol.h"
#include "CKStoreClient.h"

@protocol OS_dispatch_queue; // @import Dispatch;

@interface CKStoreDAAPLibrary : NSObject <CKAccountObserver>

@property (retain) NSNumber *localVersion;
@property (retain) NSMutableDictionary *items;
@property (retain) NSString *serviceName;
@property (retain) NSNumber *sessionID;
@property (retain) NSObject<OS_dispatch_queue> *requestQueue;
@property double pollFrequency;
@property double forcedRefreshFrequency;
@property (retain) NSTimer *pollTimer;
@property (retain) NSTimer *forcedRefreshTimer;
@property (retain) NSMutableDictionary *observers;
@property (readonly) CKStoreClient *storeClient;
@property long long mediaKinds;
@property (readonly) unsigned long long count;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)daapLibraryWithStoreClient:(id)_storeClient;

/* instance methods */
- (void)dealloc;
- (id)itemAtIndex:(unsigned long long)_atIndex;
- (void)removeObserver:(id)_observer;
- (id)addObserver:(id)_observer;
- (void)update;
- (void)reload;
- (id)allItems;
- (id)initWithStoreClient:(id)_storeClient;
- (id)itemsAtIndexes:(id)_atIndexes;
- (void)_configureWithBagInfo:(id)_withBagInfo;
- (void)_forcedRefreshTimerFired:(id)_refreshTimerFired;
- (void)_latestDatabaseVersionWithReason:(int)_databaseVersionWithReason completionHandler:(id /* block */)_handler;
- (void)_loadPersistedStore;
- (void)_loginWithCompletionHandler:(id /* block */)_withCompletionHandler;
- (id)_mediaKindsQueryString;
- (void)_performDAAPRequestWithAction:(id)_daaprequestWithAction body:(id)_body contentType:(id)_type reason:(int)_reason completionHandler:(id /* block */)_handler;
- (id)_persistedStoreURL;
- (void)_pollDAAPServerWithReason:(int)_daapserverWithReason completionHandler:(id /* block */)_handler;
- (void)_pollingTimerFired:(id)_timerFired;
- (void)_updatedItems:(id)_items deletedItems:(id)_items withLatestVersion:(id)_latestVersion;
- (void)_writePersistedStoreItems:(id)_persistedStoreItems mediaKind:(long long)_kind version:(id)_version;
- (void)accountStore:(id)_store primaryAccountChanged:(id)_accountChanged;
- (id)daapClientTokenPairs;
- (id)filteredItemsUsingPredicate:(id)_itemsUsingPredicate;
- (id)sortedItemsUsingDescriptors:(id)_itemsUsingDescriptors;

@end

#endif /* CKStoreDAAPLibrary_h */
