//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef CKStoreRequest_h
#define CKStoreRequest_h

@import Foundation;

#include "CKAuthenticationContext.h"
#include "CKStoreClient.h"
#include "CKStoreRequestDelegate-Protocol.h"

@interface CKStoreRequest : NSObject <NSCopying, NSSecureCoding>

@property (readonly) CKStoreClient *storeClient;
@property (readonly) NSString *bagURLKey;
@property (readonly) NSURL *URL;
@property (weak) id <CKStoreRequestDelegate> delegate;
@property (copy) CKAuthenticationContext *authenticationContext;
@property (copy) NSDictionary *additionalQueryParameters;
@property (copy) NSDictionary *additionalHTTPHeaders;
@property (copy) NSData *bodyData;
@property (copy) NSDictionary *bodyPlist;

/* class methods */
+ (signed char)supportsSecureCoding;
+ (id)_commerceKitVersionString;
+ (id)_macOSBuildString;
+ (id)_macOSVersionString;
+ (void)_processURLResponse:(id)_urlresponse forRequest:(id)_request storeClient:(id)_client;
+ (id)_webKitVersionString;
+ (id)userAgentForStoreClient:(id)_agentForStoreClient;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)_zone;
- (void)encodeWithCoder:(id)_withCoder;
- (id)initWithCoder:(id)_coder;
- (id)initWithStoreClient:(id)_storeClient bagURLKey:(id)_urlkey;
- (void)runAsyncWithCompletionHandler:(id /* block */)_asyncWithCompletionHandler;
- (id)_URLRequestWithError:(id *)_error;
- (void)_authenticateWithChallenge:(id)_withChallenge completionHandler:(id /* block */)_handler;
- (id)_cookieHeader;
- (id)_initWithStoreClient:(id)_withStoreClient;
- (id)initWithStoreClient:(id)_storeClient URL:(id)_url;
- (id)runSync:(id *)_sync;

@end

#endif /* CKStoreRequest_h */
