//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef CommerceClient_Protocol_h
#define CommerceClient_Protocol_h

#include "AccountObserver-Protocol.h"
#include "DownloadQueueObserver-Protocol.h"
#include "PurchaseQueueDelegate-Protocol.h"
#include "PurchaseQueueObserver-Protocol.h"

@protocol CommerceClient <AccountObserver, DownloadQueueObserver, PurchaseQueueObserver, PurchaseQueueDelegate>

@required

@optional

@end

#endif /* CommerceClient_Protocol_h */
