//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef ISProcessPropertyListOperation_h
#define ISProcessPropertyListOperation_h

@import Foundation;

#include "ISOperation.h" // @import StoreFoundation;

@class ISPropertyListProvider; // @import StoreFoundation;

@protocol ISURLOperationDelegate; // @import StoreFoundation;

@interface ISProcessPropertyListOperation : ISOperation <ISURLOperationDelegate> {
    /* instance variables */
    NSDictionary *_propertyList;
    NSURL *_propertyListURL;
    id /* block */ _preParserBlock;
}

@property (retain) ISPropertyListProvider *dataProvider;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (void)run;
- (void)operation:(id)_operation failedWithError:(id)_withError;
- (id)initWithStoreClient:(id)_storeClient;
- (id)initWithPropertyList:(id)_propertyList storeClient:(id)_client;
- (id)initWithPropertyListAtURL:(id)_propertyListAtURL withPreParserBlock:(id /* block */)_preParserBlock storeClient:(id)_client;
- (void)operation:(id)_operation finishedWithOutput:(id)_withOutput;

@end

#endif /* ISProcessPropertyListOperation_h */
