//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef PurchaseQueueObserver_Protocol_h
#define PurchaseQueueObserver_Protocol_h

@import Foundation;

@protocol PurchaseQueueObserver <NSObject>

@required

/* required instance methods */
- (void)purchaseQueueWithIdentifier:(id)_queueWithIdentifier addedTransactions:(id)_transactions;
- (void)purchaseQueueWithIdentifier:(id)_queueWithIdentifier updatedTransactions:(id)_transactions;

@optional

@end

#endif /* PurchaseQueueObserver_Protocol_h */
