//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef SSRestoreContentItem_h
#define SSRestoreContentItem_h

@import Foundation;

@interface SSRestoreContentItem : NSObject {
    /* instance variables */
    NSNumber *_accountID;
    NSString *_appleID;
    signed char _isRestore;
    NSMutableDictionary *_properties;
}

@property (copy, nonatomic) NSString *bundleID;
@property (retain, nonatomic) NSNumber *cloudItemID;
@property (retain, nonatomic) NSNumber *cloudMatchStatus;
@property (copy, nonatomic) NSString *downloadKind;
@property (copy, nonatomic) NSString *podcastEpisodeGUID;
@property (copy, nonatomic) NSString *storeAccountAppleID;
@property (retain, nonatomic) NSNumber *storeAccountID;
@property (copy, nonatomic) NSString *storeFrontID;
@property (retain, nonatomic) NSNumber *storeItemID;
@property (copy, nonatomic) NSString *storeSoftwareVersionID;
@property (copy, nonatomic) NSString *installPath;
@property (nonatomic) signed char DRMFree;
@property (copy, nonatomic) NSString *storeFlavor;
@property (copy, nonatomic) NSString *videoDimensions;

/* instance methods */
- (id)init;
- (void)_setValue:(id)_value forProperty:(id)_property;
- (id)_restoreKeyForDownloadProperty:(id)_keyForDownloadProperty;
- (id)_initSSRestoreContentItem;
- (id)_restoreKeyForAssetProperty:(id)_keyForAssetProperty;
- (id)copyRestoreDictionary;
- (id)initWithRestoreDownload:(id)_restoreDownload;
- (signed char)isDRMFree;
- (signed char)isEligibleForRestore:(id *)_eligibleForRestore;
- (void)setValue:(id)_value forAssetProperty:(id)_assetProperty;
- (void)setValue:(id)_value forDownloadProperty:(id)_downloadProperty;

@end

#endif /* SSRestoreContentItem_h */
