//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tool: ld (951.9)
//    - LC_SOURCE_VERSION: 714.4.9.0.0
//
#ifndef SSRemoteNotification_h
#define SSRemoteNotification_h

@import Foundation;

@interface SSRemoteNotification : NSObject {
    /* instance variables */
    NSDictionary *_userInfo;
}

@property (readonly, nonatomic) NSDictionary *notificationUserInfo;
@property (readonly, nonatomic) long long actionType;
@property (readonly, nonatomic) NSNumber *targetDSID;
@property (readonly, nonatomic) NSString *alertBodyString;
@property (readonly, nonatomic) NSString *alertCancelString;
@property (readonly, nonatomic) NSString *alertOKString;
@property (readonly, nonatomic) NSString *alertTitleString;
@property (readonly, nonatomic) id badgeValue;
@property (readonly, nonatomic) NSString *soundFileName;

/* instance methods */
- (id)valueForKey:(id)_forKey;
- (id)_valueForAlertKey:(id)_forAlertKey;
- (id)initWithNotificationUserInfo:(id)_notificationUserInfo;

@end

#endif /* SSRemoteNotification_h */
