//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef __EXMainConnectionHandler_Protocol_h
#define __EXMainConnectionHandler_Protocol_h

@import Foundation;

#include "_EXConnectionHandler-Protocol.h"

@protocol _EXMainConnectionHandler <_EXConnectionHandler>

@required

@property (readonly) id principalObject;

/* required instance methods */
- (id)initWithPrincipalObject:(id)object;

@optional

@end

#endif /* __EXMainConnectionHandler_Protocol_h */
