//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef __TtCV18AppleMediaServices9KeepAliveP33_8D5EA5EE57B6E86A66C300315FB9941621RBSAssertionComponent_h
#define __TtCV18AppleMediaServices9KeepAliveP33_8D5EA5EE57B6E86A66C300315FB9941621RBSAssertionComponent_h

@import Foundation;

#include "RBSAssertionObserving-Protocol.h"

// @interface AppleMediaServices.KeepAlive.(RBSAssertionComponent in _8D5EA5EE57B6E86A66C300315FB99416) : NSObject <RBSAssertionObserving> { // (Swift)
//     /* instance variables */
//      logKey;
//      assertion;
//      invalidationHandler;
// }
// 
// /* instance methods */
// - (id)init;
// - (void)assertion:(id)assertion didInvalidateWithError:(id)error;
// - (void)assertionWillInvalidate:(id)invalidate;
// 
// @end

#endif /* __TtCV18AppleMediaServices9KeepAliveP33_8D5EA5EE57B6E86A66C300315FB9941621RBSAssertionComponent_h */
