//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _ACAccountStore_AppleMediaServices_h
#define _ACAccountStore_AppleMediaServices_h

@import Foundation;

#include "ACAccountStore.h"

@interface ACAccountStore (AppleMediaServices)

/* class methods */
+ (id)_ams_defaultAccountStore;
+ (id)_ams_newAccountStore;
+ (signed char)_isAccountsCachingEnabled;
+ (id)_secureTokenForIdentifier:(id)identifier;
+ (id)ams_accountTypeIdentifierForMediaType:(id)type;
+ (id)ams_defaultMediaType;
+ (void)ams_setDefaultMediaType:(id)type;
+ (id)ams_sharedAccountStore;
+ (id)ams_sharedAccountStoreForClient:(id)client;
+ (id)ams_sharedAccountStoreForMediaType:(id)type;
+ (id)ams_sharedAccountStoreForProcessInfo:(id)info;

/* instance methods */
- (id)ams_activeiTunesAccount;
- (id)ams_iTunesAccountsForMediaType:(id)type;
- (id)_saveAccount:(id)account verifyCredentials:(signed char)credentials;
- (id)ams_demoAccount;
- (id)_accountTypeForMediaType:(id)type;
- (signed char)_addGlobalCookiesForResponse:(id)response error:(id *)error;
- (signed char)_addUserCookiesForResponse:(id)response account:(id)account error:(id *)error;
- (id)_ams_accountTypeWithAccountTypeIdentifier:(id)identifier error:(id *)error;
- (id)_ams_accountWithIdentifier:(id)identifier error:(id *)error;
- (id)_ams_accountsWithAccountType:(id)type options:(unsigned long long)options error:(id *)error;
- (id)_ams_accountsWithAccountTypeIdentifier:(id)identifier options:(unsigned long long)options error:(id *)error;
- (id)_ams_fetchAccountTypeWithAccountTypeIdenfitier:(id)idenfitier;
- (id)_ams_fetchAccountWithIdentifier:(id)identifier;
- (id)_ams_fetchAccountsWithAccountType:(id)type options:(unsigned long long)options;
- (id)_ams_fetchAccountsWithAccountTypeIdentifier:(id)identifier options:(unsigned long long)options;
- (id)_ams_localiTunesAccount;
- (id)_ams_localiTunesAccountAfterUpdatingStorefront:(signed char)storefront;
- (id)_ams_localiTunesAccountForAccountMediaType:(id)type updateStorefront:(signed char)storefront;
- (id)_ams_localiTunesAccountForAccountType:(id)type shouldUpdateStorefront:(signed char)storefront;
- (id)_correspondingAccountWithAccountTypeIdentifier:(id)identifier forAccount:(id)account;
- (id)_createLocaliTunesAccountForAccountType:(id)type;
- (id)_fetchLocaliTunesAccountForAccountType:(id)type shouldUpdateStorefront:(signed char)storefront;
- (id)_iTunesAccountsForAccountType:(id)type;
- (id)_updateStorefrontInLocalAccount:(id)account;
- (id)ams_IDMSAccountForAccount:(id)account;
- (id)ams_IDSAccountForAccount:(id)account;
- (id)ams_accountWithAltDSID:(id)dsid DSID:(id)dsid username:(id)username accountTypeIdentifier:(id)identifier;
- (id)ams_activeiCloudAccount;
- (id)ams_activeiTunesAccountForMediaType:(id)type;
- (signed char)ams_addCookiesForResponse:(id)response account:(id)account error:(id *)error;
- (signed char)ams_addCookiesForResponse:(id)response request:(id)request account:(id)account error:(id *)error;
- (signed char)ams_addCookiesForResult:(id)result account:(id)account error:(id *)error;
- (id)ams_alliTunesAccounts;
- (id)ams_cookiesForURL:(id)url;
- (id)ams_cookiesForURL:(id)url bag:(id)bag;
- (id)ams_fetchActiveiCloudAccount;
- (id)ams_fetchGrandSlamTokenForAccount:(id)account withIdentifier:(id)identifier;
- (id)ams_fetchGrandSlamTokenForAccount:(id)account withIdentifier:(id)identifier error:(id *)error;
- (id)ams_fetchLocaliTunesAccount;
- (id)ams_fetchiTunesAccounts;
- (id)ams_fetchiTunesSandboxAccounts;
- (id)ams_iCloudAccountForAccount:(id)account;
- (id)ams_iTunesAccountForAccount:(id)account;
- (id)ams_iTunesAccountForAccount:(id)account forMediaType:(id)type createIfNeeded:(signed char)needed;
- (id)ams_iTunesAccountForHomeWithIdentifier:(id)identifier;
- (id)ams_iTunesAccountForHomeWithIdentifier:(id)identifier error:(id *)error;
- (id)ams_iTunesAccountWithAltDSID:(id)dsid;
- (id)ams_iTunesAccountWithAltDSID:(id)dsid DSID:(id)dsid username:(id)username;
- (id)ams_iTunesAccountWithAltDSID:(id)dsid DSID:(id)dsid username:(id)username forMediaType:(id)type;
- (id)ams_iTunesAccountWithAltDSID:(id)dsid forMediaType:(id)type;
- (id)ams_iTunesAccountWithDSID:(id)dsid;
- (id)ams_iTunesAccountWithDSID:(id)dsid forMediaType:(id)type;
- (id)ams_iTunesAccountWithUsername:(id)username;
- (id)ams_iTunesAccountWithUsername:(id)username forMediaType:(id)type;
- (id)ams_iTunesAccounts;
- (id)ams_iTunesAccountsForMediaTypes:(id)types;
- (id)ams_iTunesSandboxAccounts;
- (signed char)ams_isAccountNew:(id)_new;
- (signed char)ams_isActiveAccountCombined;
- (id)ams_localiTunesAccount;
- (id)ams_localiTunesAccountForAccountMediaType:(id)type;
- (id)ams_localiTunesAccountForAccountType:(id)type;
- (id)ams_mediaAccountForHomeWithIdentifier:(id)identifier;
- (id)ams_mediaType;
- (id)ams_regulatoryAccount;
- (signed char)ams_removeCookiesMatchingProperties:(id)properties error:(id *)error;
- (id)ams_saveAccount:(id)account;
- (id)ams_saveAccount:(id)account verifyCredentials:(signed char)credentials;
- (id)ams_saveAccount:(id)account withOptions:(long long)options;
- (id)ams_secureTokenForAccount:(id)account;
- (signed char)ams_setSecureToken:(id)token forAccount:(id)account error:(id *)error;
- (id)ams_setiTunesAccount:(id)account forHomeWithIdentifier:(id)identifier;

@end

#endif /* _ACAccountStore_AppleMediaServices_h */
