//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _ACAccount_AppleMediaServices_h
#define _ACAccount_AppleMediaServices_h

@import Foundation;

#include "ACAccount.h"

@interface ACAccount (AppleMediaServices) <AMSHashable>

/* class methods */
+ (id)_defaultValueForAccountFlag:(id)flag;
+ (id)_getSetCookiesForResponse:(id)response;
+ (id)_getSetGlobalCookiesForResponse:(id)response;
+ (id)_globalCookieAllowlistWithBag:(id)bag forURL:(id)url;
+ (signed char)_isAccountFlagValue:(id)value validForAccountFlag:(id)flag;
+ (signed char)_isAccountFlagWritable:(id)writable;
+ (id)ams_createEphemeralAccount;
+ (id)ams_globalEphemeralAccountProperties;
+ (id)ams_globalEphemeralAccountPropertiesForAccount:(id)account;

/* instance methods */
- (signed char)ams_isActiveForMediaType:(id)type;
- (id)ams_DSID;
- (id)ams_storefront;
- (signed char)ams_addCookies:(id)cookies;
- (id)ams_rawPassword;
- (void)ams_setAltDSID:(id)dsid;
- (void)ams_setRegisterSuccessCriteria:(id)criteria;
- (id)ams_pushRegistrationThrottleMap;
- (id)ams_secureToken;
- (void)ams_setDisableAccountFlagsSync:(signed char)sync;
- (void)ams_setStorefront:(id)storefront forMediaType:(id)type;
- (signed char)_accountPropertyBooleanForKey:(id)key;
- (id)_accountPropertyForKey:(id)key dataProtectionClass:(unsigned long long)_class expectedClasses:(id)classes error:(id *)error;
- (id)_accountPropertyForKey:(id)key expectedClass:(Class)_class;
- (id)_accountPropertyForKey:(id)key expectedClassContainedInArray:(Class)array;
- (id)_ams_cookieProperties;
- (id)_ams_getAccountFlagsShimmedWithError:(id *)error;
- (signed char)_ams_migrateCookieProperties:(id)properties intoCookies:(id)cookies error:(id *)error;
- (void)_ams_setAccountFlagsShimmed:(id)shimmed;
- (signed char)_ams_setCookieProperties:(id)properties;
- (id)_cookiesMatchingProperties:(id)properties;
- (id)_ephemeralAccountPropertyForKey:(id)key dataProtectionClass:(unsigned long long)_class expectedClasses:(id)classes error:(id *)error;
- (id)_hashedActiveState;
- (id)_hashedIdentifiers;
- (id)_hashedMultiUserIdentifiers;
- (id)_hashedMultiUserIdentifiers:(id)identifiers;
- (id)_hashedStorefront;
- (void)_setAccountProperty:(id)property forKey:(id)key dataProtectionClass:(unsigned long long)_class expectedClass:(Class)_class;
- (void)_setAccountProperty:(id)property forKey:(id)key expectedClass:(Class)_class;
- (void)_setEphemeralAccountProperty:(id)property forKey:(id)key dataProtectionClass:(unsigned long long)_class expectedClass:(Class)_class;
- (signed char)_updateCookiesWithCookiesToAdd:(id)add cookiesToRemove:(id)remove error:(id *)error;
- (id)ams_accountFlagOverrideValueForAccountFlag:(id)flag;
- (id)ams_accountFlagValueForAccountFlag:(id)flag;
- (id)ams_accountFlags;
- (id)ams_accountID;
- (signed char)ams_addCookies:(id)cookies error:(id *)error;
- (signed char)ams_addCookiesForResponse:(id)response;
- (signed char)ams_addCookiesForResponse:(id)response error:(id *)error;
- (signed char)ams_addCookiesForResult:(id)result;
- (signed char)ams_addGlobalCookiesForResponse:(id)response;
- (signed char)ams_addGlobalCookiesForResult:(id)result;
- (void)ams_addHomeUserIdentifier:(id)identifier;
- (id)ams_allStorefronts;
- (id)ams_altDSID;
- (id)ams_automaticDownloadKinds;
- (long long)ams_biometricsState;
- (id)ams_cookieDatabasePath;
- (id)ams_cookies;
- (id)ams_cookiesForURL:(id)url;
- (id)ams_cookiesForURL:(id)url bag:(id)bag;
- (id)ams_cookiesForURL:(id)url bag:(id)bag cleanupGlobalCookies:(signed char)cookies;
- (signed char)ams_copyStorefrontFromAccount:(id)account;
- (id)ams_creditsString;
- (id)ams_dataMigrationStoragePath;
- (id)ams_delta:(id)ams_delta;
- (signed char)ams_didAgreeToTerms;
- (signed char)ams_disableAccountFlagsSync;
- (signed char)ams_disablePrivacyAcknowledgementSync;
- (signed char)ams_encryptAccountFlags;
- (id)ams_firstName;
- (unsigned long long)ams_freePasswordPromptSetting;
- (id)ams_fullName;
- (id)ams_isBackingAccountForActiveiCloudAccount;
- (id)ams_isBundleOwner;
- (signed char)ams_isDemoAccount;
- (signed char)ams_isDuplicate:(id)duplicate;
- (signed char)ams_isEphemeralAccount;
- (signed char)ams_isHSA2;
- (signed char)ams_isIDMSAccount;
- (signed char)ams_isInGoodStanding;
- (signed char)ams_isInRestrictedRegionWithBag:(id)bag shouldWaitForSync:(signed char)sync;
- (id)ams_isInRestrictedRegionWithBag:(id)bag waitForSync:(signed char)sync;
- (signed char)ams_isLocalAccount;
- (signed char)ams_isLocalOrSandboxAccount;
- (signed char)ams_isManagedAppleID;
- (signed char)ams_isRegulatoryAccount;
- (signed char)ams_isSandboxAccount;
- (signed char)ams_isValidPayment;
- (signed char)ams_isiCloudAccount;
- (signed char)ams_isiCloudFamily;
- (signed char)ams_isiTunesAccount;
- (unsigned long long)ams_lastAuthenticationCredentialSource;
- (id)ams_lastAuthenticationServerResponse;
- (id)ams_lastName;
- (id)ams_lastRestrictedRegionSyncTimestamp;
- (long long)ams_mergePrivacyAcknowledgement:(id)acknowledgement;
- (signed char)ams_mergedPrivacyAcknowledgement;
- (signed char)ams_migrateCookiePropertiesWithError:(id *)error;
- (unsigned long long)ams_paidPasswordPromptSetting;
- (id)ams_password;
- (signed char)ams_postAccountFlagsWithBagContract:(id)contract;
- (id)ams_privacyAcknowledgement;
- (id)ams_registerSuccessCriteria;
- (signed char)ams_removeAllCookies;
- (signed char)ams_removeAllCookiesWithError:(id *)error;
- (signed char)ams_removeCookies:(id)cookies;
- (signed char)ams_removeCookies:(id)cookies error:(id *)error;
- (signed char)ams_removeCookiesMatchingProperties:(id)properties;
- (signed char)ams_removeCookiesMatchingProperties:(id)properties error:(id *)error;
- (void)ams_removeHomeUserIdentifier:(id)identifier;
- (signed char)ams_requiresAuthKitUpdate;
- (unsigned long long)ams_securityLevel;
- (signed char)ams_setAccountFlagOverrideValue:(id)value forAccountFlag:(id)flag;
- (void)ams_setAccountFlagValue:(id)value forAccountFlag:(id)flag;
- (void)ams_setAccountFlags:(id)flags;
- (void)ams_setActive:(signed char)active forMediaType:(id)type;
- (void)ams_setAgreedToTerms:(signed char)terms;
- (void)ams_setBiometricsState:(long long)state;
- (void)ams_setCreditsString:(id)string;
- (void)ams_setDSID:(id)dsid;
- (void)ams_setDemoAccount:(signed char)account;
- (void)ams_setDisablePrivacyAcknowledgementSync:(signed char)sync;
- (void)ams_setFirstName:(id)name;
- (void)ams_setFreePasswordPromptSetting:(unsigned long long)setting;
- (void)ams_setInGoodStanding:(signed char)standing;
- (void)ams_setInUse:(signed char)use;
- (void)ams_setIsBundleOwner:(id)owner;
- (void)ams_setLastAuthenticationCredentialSource:(unsigned long long)source;
- (void)ams_setLastName:(id)name;
- (void)ams_setLastRestrictedRegionSyncTimestamp:(id)timestamp;
- (void)ams_setManagedAppleID:(signed char)id;
- (void)ams_setMergedPrivacyAcknowledgement:(signed char)acknowledgement;
- (void)ams_setPaidPasswordPromptSetting:(unsigned long long)setting;
- (void)ams_setPassword:(id)password;
- (void)ams_setPushRegistrationThrottleMap:(id)map;
- (void)ams_setRawPassword:(id)password;
- (void)ams_setRegulatoryAccount:(signed char)account;
- (void)ams_setServerResponse:(id)response;
- (void)ams_setStorefront:(id)storefront;
- (void)ams_setValidPayment:(signed char)payment;
- (void)ams_setValue:(signed char)value forAccountFlag:(id)flag;
- (void)ams_setiCloudFamily:(signed char)family;
- (id)ams_storefrontForMediaType:(id)type;
- (signed char)ams_valueForAccountFlag:(id)flag;
- (id)hashedDescription;

@end

#endif /* _ACAccount_AppleMediaServices_h */
