//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSAuthKitUpdateTask_h
#define _AMSAuthKitUpdateTask_h

@import Foundation;

#include "ACAccount.h"
#include "AKAppleIDAuthenticationDelegate-Protocol.h"
#include "AMSAuthenticateOptions.h"
#include "AMSTask.h"

@protocol AMSAuthKitUpdateTaskDelegate;

@interface AMSAuthKitUpdateTask : AMSTask <AKAppleIDAuthenticationDelegate>

@property (weak) id <AMSAuthKitUpdateTaskDelegate> delegate;
@property (readonly) ACAccount *account;
@property (readonly) AMSAuthenticateOptions *options;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (void)_updateAccountRawPasswordUsingSecondaryAccounts:(id)accounts options:(id)options;

/* instance methods */
- (unsigned long long)_authenticationType;
- (signed char)authenticationController:(id)controller shouldContinueWithAuthenticationResults:(id)results error:(id)error forContext:(id)context;
- (id)initWithAccount:(id)account options:(id)options;
- (void)_configureClientInfoForContext:(id)context;
- (signed char)_canPresentBackgroundPrompt;
- (void)_configureAuthKitContext:(id)context;
- (void)_configureCompanionDeviceForContext:(id)context;
- (void)_configureIdentifiersForContext:(id)context;
- (void)_configureProxyIdentifiersForContext:(id)context;
- (void)_configureStringsForContext:(id)context;
- (id)_createAuthKitContext;
- (id)_createAuthKitController;
- (void)_logPromptSummaryForResults:(id)results context:(id)context;
- (signed char)_shouldPrefillPrimaryiCloudAccount;
- (id)performAuthKitUpdate;

@end

#endif /* _AMSAuthKitUpdateTask_h */
