//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSAccountCachedServerDataCore_h
#define _AMSAccountCachedServerDataCore_h

@import Foundation;

#include "AMSAccountIdentity.h"

@interface AMSAccountCachedServerDataCore : NSObject { // (Swift)
    /* instance variables */
    //  observations;
    //  dataAccessor;
}

/* class methods */
+ (id)sharedInstance;

/* instance methods */
- (void)dealloc;
- (id)init;
- (id)accountFlagsForAccountID:(id)id;
- (id)boolForKey:(long long)key accountID:(id)id updateBlock:(id /* block */)block;
- (id)cancelUpdateBlockFor:(id)_for;
- (id)intForKey:(long long)key accountID:(id)id updateBlock:(id /* block */)block;
- (void)setAccountFlags:(NSDictionary *)flags forAccountID:(AMSAccountIdentity *)id completionHandler:(id /* block */)handler;
- (void)setAutoPlayTo:(signed char)to forAccountID:(AMSAccountIdentity *)id completionHandler:(id /* block */)handler;
- (void)setPersonalizationTo:(signed char)to forAccountID:(AMSAccountIdentity *)id completionHandler:(id /* block */)handler;
- (id)stringForKey:(long long)key accountID:(id)id updateBlock:(id /* block */)block;

@end

#endif /* _AMSAccountCachedServerDataCore_h */
