//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSAgeVerificationCore_h
#define _AMSAgeVerificationCore_h

@import Foundation;

@interface AMSAgeVerificationCore : NSObject

/* class methods */
+ (signed char)_isAgeVerificationNeededForExpiration:(id)expiration at:(id)at;
+ (signed char)_isTimestamp:(id)timestamp validAsOf:(id)of;
+ (id)_momentOfExpiryFrom:(id)from;
+ (id)_resultForAccountVerificationExpirationTimestamp:(id)timestamp withBagControlledAgeVerificationRequired:(id)required bagWarningThresholdDays:(id)days at:(id)at;
+ (id)_timestampForWarningThresholdDays:(id)days addedTo:(id)to;

@end

#endif /* _AMSAgeVerificationCore_h */
