//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSAnisetteSyncTask_h
#define _AMSAnisetteSyncTask_h

@import Foundation;

#include "ACAccount.h"
#include "AMSBagProtocol-Protocol.h"
#include "AMSTask.h"

@interface AMSAnisetteSyncTask : AMSTask

@property (readonly) ACAccount *account;
@property (readonly) id <AMSBagProtocol> bag;
@property (readonly) NSData *data;
@property (readonly) long long type;

/* instance methods */
- (id)initWithData:(id)data type:(long long)type account:(id)account bag:(id)bag;
- (id)performSync;

@end

#endif /* _AMSAnisetteSyncTask_h */
