//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSActionRunner_h
#define _AMSActionRunner_h

@import Foundation;

#include "AMSActionContext.h"

@interface AMSActionRunner : NSObject // (Swift)

/* class methods */
+ (id)handle:(id)handle context:(id)context;
+ (signed char)canHandle:(id)handle context:(id)context;
+ (void)handle:(NSDictionary *)handle context:(AMSActionContext *)context completionHandler:(id /* block */)handler;

/* instance methods */
- (id)init;

@end

#endif /* _AMSActionRunner_h */
