//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSAuthorizeMachineTask_h
#define _AMSAuthorizeMachineTask_h

@import Foundation;

#include "ACAccount.h"
#include "AMSAuthenticateRequest.h"
#include "AMSBagConsumer-Protocol.h"
#include "AMSBagProtocol-Protocol.h"
#include "AMSProcessInfo.h"
#include "AMSRequestPresentationDelegate-Protocol.h"
#include "AMSTask.h"
#include "AMSURLProtocolDelegate-Protocol.h"
#include "AMSURLSession.h"

@interface AMSAuthorizeMachineTask : AMSTask <NSURLSessionDelegate, AMSURLProtocolDelegate, AMSBagConsumer>

@property (retain) AMSAuthenticateRequest *authenticateRequest;
@property signed char deauthorize;
@property (retain) AMSURLSession *session;
@property (retain) ACAccount *validAccount;
@property unsigned long long authorizeReason;
@property (readonly) id <AMSBagProtocol> bag;
@property (retain) AMSProcessInfo *clientInfo;
@property (copy) NSNumber *familyMemberAccountDSID;
@property (retain) NSString *logKey;
@property (weak) id <AMSRequestPresentationDelegate> presentationDelegate;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)bagSubProfile;
+ (id)bagSubProfileVersion;
+ (id)bagKeySet;
+ (id)createBagForSubProfile;

/* instance methods */
- (id)account;
- (id)performAuthorization;
- (void)AMSURLSession:(id)amsurlsession task:(id)task handleAuthenticateRequest:(id)request completion:(id /* block */)completion;
- (void)AMSURLSession:(id)amsurlsession task:(id)task handleEngagementRequest:(id)request completion:(id /* block */)completion;
- (void)AMSURLSession:(id)amsurlsession task:(id)task handleDialogRequest:(id)request completion:(id /* block */)completion;
- (id)_authenticate;
- (id)_buildRequest;
- (id)_buildRequestParametersWithError:(id *)error;
- (id)_buildRequestTask;
- (id)_checkRequestThrottle;
- (id)_keybagSyncStringForAccount:(id)account withTransactionType:(unsigned int)type error:(id *)error;
- (id)_performAuthorization;
- (id)initWithAccount:(id)account authorizeReason:(unsigned long long)reason bag:(id)bag;
- (id)initWithUsername:(id)username authorizeReason:(unsigned long long)reason bag:(id)bag presentationDelegate:(id)delegate;
- (signed char)isDeauthorize;
- (id)performDeauthorization;

@end

#endif /* _AMSAuthorizeMachineTask_h */
