//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSAccountCachedServerData_h
#define _AMSAccountCachedServerData_h

@import Foundation;

#include "AMSAccountCachedServerDataCore.h"

@interface AMSAccountCachedServerData : NSObject

@property (readonly, nonatomic) AMSAccountCachedServerDataCore *core;

/* class methods */
+ (id)sharedInstance;

/* instance methods */
- (id)accountFlagsForAccountID:(id)id;
- (id)boolForKey:(unsigned long long)key accountID:(id)id updateBlock:(id /* block */)block;
- (id)cancelUpdatesForToken:(id)token;
- (id)initWithWrappedInstance:(id)instance;
- (id)intForKey:(unsigned long long)key accountID:(id)id updateBlock:(id /* block */)block;
- (void)setAccountFlags:(id)flags forAccountID:(id)id;
- (void)setAccountFlags:(id)flags forAccountID:(id)id completion:(id /* block */)completion;
- (void)setAutoPlay:(signed char)play forAccountID:(id)id;
- (void)setPersonalization:(signed char)personalization forAccountID:(id)id;
- (id)stringForKey:(unsigned long long)key accountID:(id)id updateBlock:(id /* block */)block;

@end

#endif /* _AMSAccountCachedServerData_h */
