//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSAccountCachedServerStringCore_h
#define _AMSAccountCachedServerStringCore_h

@import Foundation;

@interface AMSAccountCachedServerStringCore : NSObject { // (Swift)
    /* instance variables */
    //  cachedValue;
}

@property (nonatomic, readonly) NSDate *expiration;
@property (nonatomic, readonly) signed char isStale;
@property (nonatomic, readonly) NSString *value;
@property (nonatomic, retain) id token;
@property (nonatomic, readonly) NSString *description;

/* instance methods */
- (id)init;

@end

#endif /* _AMSAccountCachedServerStringCore_h */
