//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSAgeVerificationTask_h
#define _AMSAgeVerificationTask_h

@import Foundation;

#include "ACAccount.h"
#include "AMSBagConsumer-Protocol.h"
#include "AMSBagProtocol-Protocol.h"
#include "AMSQRCodeDialogTask.h"
#include "AMSRequestPresentationDelegate-Protocol.h"
#include "AMSTask.h"

@interface AMSAgeVerificationTask : AMSTask <AMSBagConsumer>

@property (retain) AMSQRCodeDialogTask *task;
@property (readonly) ACAccount *account;
@property (readonly) id <AMSBagProtocol> bag;
@property (retain) NSDictionary *options;
@property (retain) NSString *pincode;
@property (readonly) id <AMSRequestPresentationDelegate> presentationDelegate;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)bagSubProfile;
+ (id)bagSubProfileVersion;
+ (id)_errorCheckWithAccount:(id)account bag:(id)bag;
+ (id)bagKeySet;
+ (id)createBagForSubProfile;

/* instance methods */
- (id)performTask;
- (id)_performTaskForAccount:(id)account withBag:(id)bag;
- (void)_handleAccountStoreDidChangeNotification:(id)notification;
- (void)_handleAccountStoreDidChangeNotification:(id)notification at:(id)at;
- (void)_startObservingAccountStoreChanges;
- (void)_stopObservingAccountStoreChanges;
- (id)initWithAccount:(id)account bag:(id)bag options:(id)options presentationDelegate:(id)delegate;
- (id)isVerificationNeeded;

@end

#endif /* _AMSAgeVerificationTask_h */
