//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSAttestation_h
#define _AMSAttestation_h

@import Foundation;

@interface AMSAttestation : NSObject

/* class methods */
+ (id)_attestationPListWithStyle:(unsigned long long)style primaryAttestation:(id)attestation extendedAttestation:(id)attestation error:(id *)error;
+ (id)_generateCertificateChainStringsForOptions:(id)options error:(id *)error;
+ (id)attestationHTTPBodyDataWithStyle:(unsigned long long)style regenerateKeys:(signed char)keys error:(id *)error;
+ (id)attestationWithOptions:(id)options error:(id *)error;

@end

#endif /* _AMSAttestation_h */
