//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSAuthenticateRequest_h
#define _AMSAuthenticateRequest_h

@import Foundation;

#include "ACAccount.h"
#include "AMSAuthenticateOptions.h"

@interface AMSAuthenticateRequest : NSObject <NSSecureCoding>

@property (retain) ACAccount *account;
@property (retain) NSString *logKey;
@property (retain) AMSAuthenticateOptions *options;
@property (retain) NSDictionary *userInfo;

/* class methods */
+ (signed char)supportsSecureCoding;

/* instance methods */
- (id)description;
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;
- (id)initWithAccount:(id)account options:(id)options;
- (id)initWithDSID:(id)dsid altDSID:(id)dsid username:(id)username options:(id)options;

@end

#endif /* _AMSAuthenticateRequest_h */
