//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSAuthenticateResult_h
#define _AMSAuthenticateResult_h

@import Foundation;

#include "ACAccount.h"
#include "AMSAuthKitUpdateResult.h"

@interface AMSAuthenticateResult : NSObject <NSSecureCoding>

@property (retain) AMSAuthKitUpdateResult *authKitUpdateResult;
@property (readonly) ACAccount *account;
@property (readonly) NSDictionary *authenticationResults;
@property (readonly) NSDictionary *serverResponse;

/* class methods */
+ (signed char)supportsSecureCoding;

/* instance methods */
- (id)description;
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;
- (id)initWithAccount:(id)account;

@end

#endif /* _AMSAuthenticateResult_h */
