//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSAbsinthe_h
#define _AMSAbsinthe_h

@import Foundation;

#include "AMSBagConsumer-Protocol.h"

@interface AMSAbsinthe : NSObject <AMSBagConsumer>

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)bagSubProfile;
+ (id)bagSubProfileVersion;
+ (id)_dataToSignFromRequest:(id)request bagDefinition:(id)definition;
+ (void)_signingDataFromRequest:(id)request buyParams:(id)params bag:(id)bag completion:(id /* block */)completion;
+ (id)bagKeySet;
+ (id)createBagForSubProfile;
+ (id)handleResponse:(id)response bag:(id)bag;
+ (id)headersForRequest:(id)request buyParams:(id)params bag:(id)bag;

@end

#endif /* _AMSAbsinthe_h */
