//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSAccountDeviceInfoTask_h
#define _AMSAccountDeviceInfoTask_h

@import Foundation;

#include "ACAccount.h"
#include "ACAccountStore.h"
#include "AMSBagConsumer-Protocol.h"
#include "AMSBagProtocol-Protocol.h"
#include "AMSProcessInfo.h"
#include "AMSTask.h"
#include "AMSURLRequestEncoder.h"
#include "AMSURLSession.h"

@interface AMSAccountDeviceInfoTask : AMSTask <AMSBagConsumer>

@property (retain) AMSURLSession *session;
@property (retain) AMSURLRequestEncoder *requestEncoder;
@property (retain) NSString *serialNumber;
@property (retain) ACAccountStore *accountStore;
@property (readonly) ACAccount *account;
@property (readonly) id <AMSBagProtocol> bag;
@property (retain) AMSProcessInfo *clientInfo;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)bagSubProfile;
+ (id)bagSubProfileVersion;
+ (id)createBagForSubProfile;

/* instance methods */
- (id)perform;
- (id)_deviceInfoRequest;
- (id)_requestWithURL:(id)url;
- (void)_updateAccountWithInfo:(id)info;
- (id)initWithAccount:(id)account accountStore:(id)store bag:(id)bag;
- (id)initWithAccount:(id)account accountStore:(id)store bag:(id)bag requestEncoder:(id)encoder session:(id)session serialNumber:(id)number;

@end

#endif /* _AMSAccountDeviceInfoTask_h */
