//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSBiometricsSignatureRequest_h
#define _AMSBiometricsSignatureRequest_h

@import Foundation;

#include "ACAccount.h"
#include "AMSBagProtocol-Protocol.h"
#include "AMSKeychainOptions.h"
#include "AMSProcessInfo.h"

@class LAContext;

@interface AMSBiometricsSignatureRequest : NSObject <NSSecureCoding>

@property (readonly, copy) ACAccount *account;
@property (retain) id <AMSBagProtocol> bag;
@property (readonly, copy) NSString *challenge;
@property (readonly, copy) AMSProcessInfo *clientInfo;
@property signed char dualAction;
@property (readonly) AMSKeychainOptions *keychainOptions;
@property (readonly) NSDictionary *localAuthOptions;
@property signed char useApplePayClassic;
@property signed char useAutoEnrollment;
@property (readonly) struct __SecAccessControl * localAuthAccessControlRef;
@property (readonly) LAContext *localAuthContext;

/* class methods */
+ (signed char)supportsSecureCoding;
+ (id)biometricsSignatureRequestForURLResponse:(id)urlresponse account:(id)account session:(id)session task:(id)task clientInfo:(id)info options:(id)options error:(id *)error;

/* instance methods */
- (void)dealloc;
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;
- (id)_localAuthOptions;
- (id)initWithAccount:(id)account clientInfo:(id)info challenge:(id)challenge localAuthContext:(id)context options:(id)options error:(id *)error;
- (signed char)isDualAction;
- (signed char)shouldUseApplePayClassic;
- (signed char)shouldUseAutoEnrollment;

@end

#endif /* _AMSBiometricsSignatureRequest_h */
