//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSBinaryPromise_h
#define _AMSBinaryPromise_h

@import Foundation;

#include "AMSMutablePromise.h"

@interface AMSBinaryPromise : NSObject

@property (retain) AMSMutablePromise *backingPromise;

/* class methods */
+ (id)promiseWithAll:(id)all;
+ (id)promiseWithAny:(id)any;
+ (id)_globalPromiseStorage;
+ (id)_globalPromiseStorageAccessQueue;
+ (id)promiseWithError:(id)error;
+ (id)promiseWithFlattenedPromises:(id)promises;
+ (id)promiseWithPromise:(id)promise;
+ (id)promiseWithSuccess;

/* instance methods */
- (id)init;
- (void)waitUntilFinished;
- (signed char)cancel;
- (signed char)resultWithError:(id *)error;
- (signed char)finishWithError:(id)error;
- (void)addFinishBlock:(id /* block */)block;
- (void)addSuccessBlock:(id /* block */)block;
- (id /* block */)completionHandlerAdapter;
- (signed char)resultWithTimeout:(double)timeout error:(id *)error;
- (void)_removeFromGlobalPromiseStorage;
- (id)catchWithBlock:(id /* block */)block;
- (void)addErrorBlock:(id /* block */)block;
- (id)continueWithBlock:(id /* block */)block;
- (signed char)finishWithPromise:(id)promise;
- (signed char)finishWithSuccess;
- (signed char)finishWithSuccess:(signed char)success error:(id)error;
- (id)promiseAdapter;
- (void)resultWithCompletion:(id /* block */)completion;
- (void)resultWithTimeout:(double)timeout completion:(id /* block */)completion;
- (id)thenWithBlock:(id /* block */)block;
- (void)waitUntilFinishedWithTimeout:(double)timeout;

@end

#endif /* _AMSBinaryPromise_h */
