//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSBagFailingDataSource_h
#define _AMSBagFailingDataSource_h

@import Foundation;

#include "AMSBagDataSourceProtocol-Protocol.h"
#include "AMSProcessInfo.h"

@interface AMSBagFailingDataSource : NSObject <AMSBagDataSourceProtocol>

@property double delay;
@property (retain) NSError *error;
@property (copy) NSString *profile;
@property (copy) NSString *profileVersion;
@property (readonly) NSDate *expirationDate;
@property (readonly) signed char loaded;
@property (readonly, copy) NSString *bagLoadingPartialIdentifier;
@property (readonly, copy) AMSProcessInfo *processInfo;
@property (retain) NSString *descriptionExtended;
@property (copy) id /* block */ dataSourceChangedHandler;
@property (copy) id /* block */ dataSourceDataInvalidatedHandler;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (signed char)isLoaded;
- (id)defaultValueForKey:(id)key;
- (id)initWithProfile:(id)profile profileVersion:(id)version error:(id)error delay:(double)delay;
- (void)loadWithCompletion:(id /* block */)completion;
- (void)setDefaultValue:(id)value forKey:(id)key;
- (id)valueForURLVariable:(id)urlvariable account:(id)account;
- (void)valueForURLVariable:(id)urlvariable account:(id)account completion:(id /* block */)completion;

@end

#endif /* _AMSBagFailingDataSource_h */
