//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSBagURLQueryItemsBuilder_h
#define _AMSBagURLQueryItemsBuilder_h

@import Foundation;

@interface AMSBagURLQueryItemsBuilder : NSObject { // (Swift)
    /* instance variables */
    //  clientInfo;
    //  profile;
    //  profileVersion;
    //  operatingSystem;
    //  operatingSystemVersion;
    //  deviceClass;
    //  buildVariant;
}

/* class methods */
+ (id)storefrontFromQueryItems:(id)items;

/* instance methods */
- (id)init;
- (id)initWithClientInfo:(id)info profile:(id)profile profileVersion:(id)version;
- (id)initWithClientInfo:(id)info profile:(id)profile profileVersion:(id)version operatingSystem:(id)system operatingSystemVersion:(id)version deviceClass:(id)_class buildVariant:(id)variant;
- (id)queryItemsWithCookies:(id)cookies storefront:(id)storefront;

@end

#endif /* _AMSBagURLQueryItemsBuilder_h */
