//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSBagUnderlyingDataPersistence_h
#define _AMSBagUnderlyingDataPersistence_h

@import Foundation;

@interface AMSBagUnderlyingDataPersistence : NSObject { // (Swift)
    /* instance variables */
    //  directoryURL;
}

/* class methods */
+ (id)persistenceWithDefaultDirectory;

/* instance methods */
- (id)init;
- (id)initWithDirectoryURL:(id)url;
- (signed char)persist:(id)persist error:(id *)error;
- (signed char)removeUnderlyingDataFor:(id)_for error:(id *)error;
- (id)underlyingDataFor:(id)_for error:(id *)error;

@end

#endif /* _AMSBagUnderlyingDataPersistence_h */
