//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSBiometricsSignatureTask_h
#define _AMSBiometricsSignatureTask_h

@import Foundation;

#include "AMSBiometricsSignatureRequest.h"
#include "AMSTask.h"

@interface AMSBiometricsSignatureTask : AMSTask

@property (readonly) AMSBiometricsSignatureRequest *request;

/* class methods */
+ (SecKeyRef)copyPrivateKeyWithStyle:(unsigned long long)style context:(id)context account:(id)account options:(id)options error:(id *)error;
+ (id)fetchDataToSignWithPublicKeyData:(id)data challenge:(id)challenge error:(id *)error;
+ (id)fetchPublicKeyDataFromPrivateKey:(SecKeyRef)key error:(id *)error;
+ (id)signDataWithPrivateKey:(SecKeyRef)key dataToSign:(id)sign error:(id *)error;

/* instance methods */
- (id)initWithRequest:(id)request;
- (id)_performSignatureInProcess;
- (id)_performSignatureOutOfProcess;
- (id)performSignature;
- (id)performSignatureFromService;
- (void)regenerateAttestationKeys;
- (id)signWithPrivateKey:(SecKeyRef)key error:(id *)error;

@end

#endif /* _AMSBiometricsSignatureTask_h */
