//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSBagProtocol_Protocol_h
#define _AMSBagProtocol_Protocol_h

@import Foundation;

#include "AMSProcessInfo.h"

@protocol AMSBagProtocol <NSObject>

@required

@property (readonly) signed char expired;
@property (readonly) NSDate *expirationDate;
@property (readonly, copy) NSString *profile;
@property (readonly, copy) NSString *profileVersion;

/* required instance methods */
- (id)URLForKey:(id)key;
- (id)arrayForKey:(id)key;
- (id)boolForKey:(id)key;
- (id)dictionaryForKey:(id)key;
- (id)stringForKey:(id)key;
- (id)integerForKey:(id)key;
- (id)doubleForKey:(id)key;
- (signed char)isExpired;
- (void)createSnapshotWithCompletion:(id /* block */)completion;

@optional

@property (readonly, copy, nonatomic) AMSProcessInfo *processInfo;

/* optional instance methods */
- (id)URLForKey:(id)key account:(id)account;

@end

#endif /* _AMSBagProtocol_Protocol_h */
