//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSBagValue_h
#define _AMSBagValue_h

@import Foundation;

#include "ACAccount.h"
#include "AMSBagDataSourceProtocol-Protocol.h"

@interface AMSBagValue : NSObject

@property (copy) ACAccount *account;
@property (weak) id <AMSBagDataSourceProtocol> dataSource;
@property (retain) NSString *key;
@property (retain) NSArray *transformBlocks;
@property unsigned long long valueType;
@property (readonly) signed char loaded;

/* class methods */
+ (id)_valueFromDictionary:(id)dictionary forBagKey:(id)key;
+ (signed char)_value:(id)_value isKindOfValueType:(unsigned long long)type;
+ (id)bagValueWithKey:(id)key valueType:(unsigned long long)type valuePromise:(id)promise;
+ (id)failingBagValueWithKey:(id)key valueType:(unsigned long long)type error:(id)error;
+ (id)frozenBagValueWithKey:(id)key value:(id)value valueType:(unsigned long long)type;
+ (id)globalBagValueStorage;

/* instance methods */
- (signed char)isLoaded;
- (id)valueWithError:(id *)error;
- (void)_applyTransformsToValue:(id)value index:(long long)index completion:(id /* block */)completion;
- (void)_handleSuccessWithValue:(id)value isDefault:(signed char)_default completion:(id /* block */)completion;
- (id)_processedDefaultValue:(id)value;
- (id)_processedDefaultValuePromise:(id)promise;
- (id)initWithDataSource:(id)source key:(id)key valueType:(unsigned long long)type;
- (id)initWithDataSource:(id)source key:(id)key valueType:(unsigned long long)type account:(id)account;
- (id)transformWithBlock:(id /* block */)block;
- (id)valuePromise;
- (void)valueWithCompletion:(id /* block */)completion;

@end

#endif /* _AMSBagValue_h */
