//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSBagFrozenDataSource_h
#define _AMSBagFrozenDataSource_h

@import Foundation;

#include "AMSBagDataSourceProtocol-Protocol.h"
#include "AMSProcessInfo.h"

@interface AMSBagFrozenDataSource : NSObject <AMSBagDataSourceProtocol, NSCopying, NSSecureCoding>

@property (readonly) NSDictionary *data;
@property (readonly) NSDictionary *defaultValues;
@property (readonly) NSDate *expirationDate;
@property (readonly) signed char loaded;
@property (readonly, copy) NSString *bagLoadingPartialIdentifier;
@property (readonly, copy) AMSProcessInfo *processInfo;
@property (readonly, copy) NSString *profile;
@property (readonly, copy) NSString *profileVersion;
@property (retain) NSString *descriptionExtended;
@property (copy) id /* block */ dataSourceChangedHandler;
@property (copy) id /* block */ dataSourceDataInvalidatedHandler;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (signed char)supportsSecureCoding;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;
- (signed char)isLoaded;
- (id)defaultValueForKey:(id)key;
- (id)_initWithProfile:(id)profile profileVersion:(id)version data:(id)data expirationDate:(id)date processInfo:(id)info defaultValues:(id)values;
- (void)loadWithCompletion:(id /* block */)completion;
- (void)setDefaultValue:(id)value forKey:(id)key;
- (id)valueForURLVariable:(id)urlvariable account:(id)account;
- (void)valueForURLVariable:(id)urlvariable account:(id)account completion:(id /* block */)completion;

@end

#endif /* _AMSBagFrozenDataSource_h */
