//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSCookieDatabaseSchema_h
#define _AMSCookieDatabaseSchema_h

@import Foundation;

@interface AMSCookieDatabaseSchema : NSObject

/* class methods */
+ (signed char)promptTapToRadarForSchemaMigrationFailureWithDescription:(id)description error:(id *)error;
+ (signed char)createOrUpdateSchemaUsingConnection:(id)connection;
+ (signed char)createOrUpdateSchemaUsingConnection:(id)connection error:(id *)error;
+ (signed char)migrateVersion0to1WithMigration:(id)migration error:(id *)error;

@end

#endif /* _AMSCookieDatabaseSchema_h */
