//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSCarrierLinkTask_h
#define _AMSCarrierLinkTask_h

@import Foundation;

#include "ACAccount.h"
#include "AMSBagConsumer-Protocol.h"
#include "AMSBagProtocol-Protocol.h"
#include "AMSCarrierLinkParams.h"
#include "AMSEngagement.h"
#include "AMSMetrics.h"
#include "AMSProcessInfo.h"
#include "AMSPromise.h"
#include "AMSTask.h"
#include "AMSURLProtocolDelegate-Protocol.h"
#include "AMSURLRequestEncoder.h"
#include "AMSURLSession.h"

@protocol AMSCarrierLinkTaskDelegate;

@interface AMSCarrierLinkTask : AMSTask <AMSURLProtocolDelegate, NSURLSessionDelegate, AMSBagConsumer>

@property (retain) ACAccount *account;
@property (readonly) AMSEngagement *engagementHandler;
@property (readonly) NSString *guid;
@property (readonly) AMSMetrics *metrics;
@property (readonly) NSString *msisdn;
@property (readonly) AMSURLRequestEncoder *requestEncoder;
@property (readonly) AMSURLSession *urlSession;
@property (readonly) AMSPromise *pacTokenPromise;
@property (retain) NSDictionary *additionalLinkingParameters;
@property (readonly) id <AMSBagProtocol> bag;
@property (retain) AMSProcessInfo *clientInfo;
@property (weak) id <AMSCarrierLinkTaskDelegate> delegate;
@property (readonly) AMSCarrierLinkParams *linkParams;
@property (copy) NSDictionary *metricsOverlay;
@property (readonly) NSString *productCode;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)bagSubProfile;
+ (id)bagSubProfileVersion;
+ (id)bagKeySet;
+ (id)createBagForSubProfile;

/* instance methods */
- (id)perform;
- (void)AMSURLSession:(id)amsurlsession task:(id)task handleAuthenticateRequest:(id)request completion:(id /* block */)completion;
- (void)AMSURLSession:(id)amsurlsession task:(id)task handleEngagementRequest:(id)request completion:(id /* block */)completion;
- (id)_linkURLRequest;
- (id)_performLinking;
- (void)AMSURLSession:(id)amsurlsession task:(id)task handleDialogRequest:(id)request completion:(id /* block */)completion;
- (id)_linkParameters;
- (void)_delegateHandleEngagementRequest:(id)request completion:(id /* block */)completion;
- (id)_linkFailureFromResult:(id)result;
- (id)_metricsEventFromCarrierLinkResult:(id)result error:(id)error;
- (id)_pacToken;
- (void)_performDelegateAuthenticationWithRequest:(id)request completion:(id /* block */)completion;
- (id)_performLinkingWithValidations;
- (id)_promptForAccount;
- (id)_recordEngagementMetricsEvent:(id)event;
- (id)_resultDecodingURLResult:(id)urlresult;
- (id)initWithAccount:(id)account bag:(id)bag engagementHandler:(id)handler guid:(id)guid linkParams:(id)params metrics:(id)metrics msisdn:(id)msisdn pacTokenPromise:(id)promise productCode:(id)code requestEncoder:(id)encoder urlSession:(id)session;
- (id)initWithAccount:(id)account bag:(id)bag linkParams:(id)params productCode:(id)code;

@end

#endif /* _AMSCarrierLinkTask_h */
