//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSClipMediaURLBuilder_h
#define _AMSClipMediaURLBuilder_h

@import Foundation;

#include "AMSBagProtocol-Protocol.h"

@interface AMSClipMediaURLBuilder : NSObject

@property (retain, nonatomic) id <AMSBagProtocol> bag;
@property (retain, nonatomic) NSString *bundleID;
@property (retain, nonatomic) NSNumber *externalVersionID;

/* instance methods */
- (id)build;
- (id)_devicePlatform;
- (id)_hostPromise;
- (id)_pathPromise;
- (id)_queryPromise;
- (id)initWithBundleID:(id)id bag:(id)bag;

@end

#endif /* _AMSClipMediaURLBuilder_h */
