//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSCookieService_h
#define _AMSCookieService_h

@import Foundation;

#include "AMSCookieServiceInterface-Protocol.h"
#include "os_unfair_lock_s.h"

@interface AMSCookieService : NSObject <NSCacheDelegate, AMSCookieServiceInterface>

@property (readonly) struct os_unfair_lock_s inMemoryStorageLock;
@property (readonly) NSCache *inMemoryStorage;
@property signed char isObservingNotifications;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)sharedService;
+ (signed char)_isEntitledForDirectCookieAccess;

/* instance methods */
- (id)init;
- (void)cache:(id)cache willEvictObject:(id)object;
- (void)_cacheCookieProperties:(id)properties forAccount:(id)account;
- (id)_cachedCookiePropertiesForAccount:(id)account;
- (void)_registerForCookieChangeNotifications;
- (void)_unregisterFromCookieChangeNotifications;
- (signed char)_useInMemoryCacheForAccount:(id)account;
- (void)clearCookiePropertyCache;
- (void)clearCookiePropertyCacheForAccount:(id)account;
- (void)clearDanglingCookieDatabasesWithCompletion:(id /* block */)completion;
- (void)getCookieDatabasePathForAccount:(id)account withCompletion:(id /* block */)completion;
- (id)getCookiePropertiesForAccount:(id)account cookieDatabaseOnly:(signed char)only error:(id *)error;
- (void)getCookiePropertiesForAccount:(id)account cookieDatabaseOnly:(signed char)only withCompletion:(id /* block */)completion;
- (id)getCookiePropertiesForAccount:(id)account error:(id *)error;
- (void)getCookiePropertiesForAccount:(id)account withCompletion:(id /* block */)completion;
- (void)updateCookiesWithCookiePropertiesToAdd:(id)add cookiePropertiesToRemove:(id)remove forAccount:(id)account withCompletion:(id /* block */)completion;

@end

#endif /* _AMSCookieService_h */
