//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSConnectionDelegateProxy_h
#define _AMSConnectionDelegateProxy_h

@import Foundation;

@interface AMSConnectionDelegateProxy : NSObject

@property (weak) id delegate;

/* class methods */
+ (id)proxyWithDelegate:(id)delegate;

/* instance methods */
- (void)forwardInvocation:(id)invocation;
- (id)methodSignatureForSelector:(SEL)selector;

@end

#endif /* _AMSConnectionDelegateProxy_h */
