//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSCardEnrollmentVerificationTask_h
#define _AMSCardEnrollmentVerificationTask_h

@import Foundation;

#include "AMSTask.h"

@interface AMSCardEnrollmentVerificationTask : AMSTask

/* class methods */
+ (id)performPaymentVerificationForPayment:(id)payment isDefault:(signed char)_default;
+ (id)performPaymentVerificationForPayment:(id)payment isDefault:(signed char)_default bag:(id)bag;
+ (void)verifyPayment:(id)payment isDefault:(signed char)_default bag:(id)bag completion:(id /* block */)completion;
+ (void)verifyPayment:(id)payment isDefault:(signed char)_default completion:(id /* block */)completion;

@end

#endif /* _AMSCardEnrollmentVerificationTask_h */
