//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSCarrierMSISDNProvider_h
#define _AMSCarrierMSISDNProvider_h

@import Foundation;

#include "AMSCarrierMSISDNProviding-Protocol.h"

@interface AMSCarrierMSISDNProvider : NSObject <AMSCarrierMSISDNProviding>

@property (readonly) NSString *msisdn;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

@end

#endif /* _AMSCarrierMSISDNProvider_h */
