//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSChannelLinkResult_h
#define _AMSChannelLinkResult_h

@import Foundation;

#include "AMSChannelLinkParams.h"

@interface AMSChannelLinkResult : NSObject <NSSecureCoding>

@property (readonly) NSError *error;
@property (readonly) NSDictionary *response;
@property (readonly) NSNumber *statusCode;
@property (readonly) NSString *channelCustomerId;
@property (readonly) AMSChannelLinkParams *linkParams;
@property (readonly) NSString *productCode;
@property (readonly) NSSet *supplementaryFields;

/* class methods */
+ (signed char)supportsSecureCoding;

/* instance methods */
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;
- (id)initWithResponse:(id)response linkParams:(id)params;
- (id)initWithResponse:(id)response linkParams:(id)params supplementaryFields:(id)fields;

@end

#endif /* _AMSChannelLinkResult_h */
