//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSCommerceAccountStore_h
#define _AMSCommerceAccountStore_h

@import Foundation;

#include "ACAccount.h"
#include "ACAccountStore.h"

@protocol OS_dispatch_queue;

@interface AMSCommerceAccountStore : NSObject

@property long long accountStoreType;
@property (retain) NSString *clientIdentifier;
@property (readonly) NSHTTPCookieStorage *cookieStorage;
@property (retain) NSObject<OS_dispatch_queue> *propertyQueue;
@property (retain) ACAccountStore *underlyingAccountStore;
@property (readonly) ACAccount *activeAccount;
@property (readonly) NSArray *accounts;

/* class methods */
+ (id)accountStoreWithClientIdentifier:(id)identifier accountStore:(id)store;

/* instance methods */
- (id)_cookies;
- (id)_defaultsDomainKey;
- (id)_defaultsKnownAccountsKey;
- (id)_defaultsPrimaryAccountKey;
- (id)_defaultsStorefrontKeyForDSID:(id)dsid;
- (id)initWithClientIdentifier:(id)identifier accountStore:(id)store;
- (id)storefrontForDSID:(id)dsid;

@end

#endif /* _AMSCommerceAccountStore_h */
