//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSCarrierLinkResult_h
#define _AMSCarrierLinkResult_h

@import Foundation;

#include "AMSCarrierLinkParams.h"

@interface AMSCarrierLinkResult : NSObject <NSSecureCoding>

@property (readonly) NSError *error;
@property (readonly) NSDictionary *response;
@property (readonly) NSNumber *statusCode;
@property (readonly) NSString *channelCustomerId;
@property (readonly) AMSCarrierLinkParams *linkParams;
@property (readonly) NSString *productCode;

/* class methods */
+ (signed char)supportsSecureCoding;

/* instance methods */
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;
- (id)initWithChannelLinkResult:(id)result;
- (id)initWithLinkParams:(id)params channelCustomerId:(id)id productCode:(id)code statusCode:(id)code error:(id)error;
- (id)initWithResponse:(id)response linkParams:(id)params;

@end

#endif /* _AMSCarrierLinkResult_h */
