//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSCardMetadataRegistrationResult_h
#define _AMSCardMetadataRegistrationResult_h

@import Foundation;

@interface AMSCardMetadataRegistrationResult : NSObject

@property (retain) NSString *cardArtwork;
@property (retain) NSData *cardArtworkData;
@property long long cardType;
@property (retain) NSString *descriptionLong;
@property (retain) NSString *descriptionShort;
@property long long paymentNetwork;
@property (retain) NSString *serialNumber;
@property (retain) NSString *suffix;
@property (retain) NSString *passTypeIdentifier;
@property (retain, nonatomic) NSDictionary *dictionary;

/* instance methods */
- (id)init;

@end

#endif /* _AMSCardMetadataRegistrationResult_h */
