//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSCommerceMigrator_h
#define _AMSCommerceMigrator_h

@import Foundation;

@interface AMSCommerceMigrator : NSObject

/* class methods */
+ (id)_cookiesFromURL:(id)url;
+ (id)_createAccountFromKnownAccountsDictionary:(id)dictionary accountTypeIdentifier:(id)identifier;
+ (void)_migrateAppStoreInformationIntoAccounts:(id)accounts;
+ (void)_migrateBiometricsStateIntoAccounts:(id)accounts;
+ (void)_migrateBooksInformationIntoAccounts:(id)accounts;
+ (id)_migrateCommerceAccounts;
+ (void)_migrateConfiguratorInformationIntoAccounts:(id)accounts;
+ (void)_migrateCookiesIntoAccounts:(id)accounts;
+ (id)_migrateLegacyCommerceAccounts;
+ (void)_migratePrivacyAcknowledgementIntoAccounts:(id)accounts;
+ (void)_migrateiTunesInformation;
+ (id)_primaryDSIDFromLegacyPreferencesDomain:(id)domain clientType:(id)type serverType:(id)type;
+ (void)_removeAccountRelatedDefaultsUsingAccounts:(id)accounts;
+ (void)migrateCommerceAccountsWithOptions:(id)options;

@end

#endif /* _AMSCommerceMigrator_h */
