//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSCookieServiceInterface_Protocol_h
#define _AMSCookieServiceInterface_Protocol_h

@import Foundation;

@protocol AMSCookieServiceInterface <NSObject>

@required

/* required instance methods */
- (void)clearDanglingCookieDatabasesWithCompletion:(id /* block */)completion;
- (void)getCookieDatabasePathForAccount:(id)account withCompletion:(id /* block */)completion;
- (void)getCookiePropertiesForAccount:(id)account cookieDatabaseOnly:(signed char)only withCompletion:(id /* block */)completion;
- (void)getCookiePropertiesForAccount:(id)account withCompletion:(id /* block */)completion;
- (void)updateCookiesWithCookiePropertiesToAdd:(id)add cookiePropertiesToRemove:(id)remove forAccount:(id)account withCompletion:(id /* block */)completion;

@optional

@end

#endif /* _AMSCookieServiceInterface_Protocol_h */
