//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSDeprecatedBagContract_h
#define _AMSDeprecatedBagContract_h

@import Foundation;

#include "AMSBagProtocol-Protocol.h"
#include "AMSBagValue.h"
#include "AMSDeviceOfferBagContract-Protocol.h"
#include "AMSLookupBagContract-Protocol.h"
#include "AMSMescalBagContract-Protocol.h"
#include "AMSMetricsBagContract-Protocol.h"

@interface AMSDeprecatedBagContract : NSObject <AMSDeviceOfferBagContract, AMSMetricsBagContract, AMSMescalBagContract, AMSLookupBagContract>

@property (retain) id <AMSBagProtocol> bag;
@property (readonly) AMSBagValue *appleMusicDeviceOfferDeepLink;
@property (readonly) AMSBagValue *iCloudDeviceOfferDeepLink;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (readonly) AMSBagValue *metricsURL;
@property (readonly) AMSBagValue *metricsDictionary;
@property (readonly) AMSBagValue *metricsUrl;
@property (readonly) AMSBagValue *apsEnabledPatterns;
@property (readonly) AMSBagValue *apsSamplingPercent;
@property (readonly) AMSBagValue *apsAllowedProductTypes;
@property (readonly) AMSBagValue *guidRegexes;
@property (readonly) AMSBagValue *guidSchemes;
@property (readonly) id <AMSMescalBagContract> mescalContract;
@property (readonly) AMSBagValue *storefrontSuffix;
@property (readonly) AMSBagValue *TLSSamplingPercentage;
@property (readonly) AMSBagValue *TLSSamplingSessionDuration;
@property (readonly) AMSBagValue *TFOSamplingPercentage;
@property (readonly) AMSBagValue *TFOSamplingSessionDuration;
@property (readonly) AMSBagValue *trustedDomains;
@property (readonly) id <AMSMetricsBagContract> metricsContract;
@property (readonly) AMSBagValue *mescalCertificateURL;
@property (readonly) AMSBagValue *mescalSetupURL;
@property (readonly) AMSBagValue *mescalPrimingURL;
@property (readonly) AMSBagValue *mescalSignedActions;
@property (readonly) AMSBagValue *mescalSignSapRequests;
@property (readonly) AMSBagValue *mescalSignSapResponses;
@property (readonly) AMSBagValue *personalizedLookupURL;
@property (readonly) AMSBagValue *unpersonalizedLookupURL;

/* instance methods */
- (id)initWithBag:(id)bag;

@end

#endif /* _AMSDeprecatedBagContract_h */
