//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSDialogRequest_h
#define _AMSDialogRequest_h

@import Foundation;

#include "AMSDialogAction.h"
#include "AMSMetricsEvent.h"

@interface AMSDialogRequest : NSObject <NSSecureCoding, NSCopying>

@property signed char allowsNativeWatchCancelPlacement;
@property (readonly) NSDictionary *appearanceInfo;
@property (copy) NSArray *buttonActions;
@property (retain) AMSDialogAction *cancelAction;
@property (copy) NSDictionary *clickstreamMetricsEvent;
@property (retain) AMSDialogAction *defaultAction;
@property (copy) NSURL *iconBundleURL;
@property (copy) NSURL *iconURL;
@property (copy) NSString *identifier;
@property (copy) NSString *logKey;
@property (copy) NSString *message;
@property (copy) NSString *messageAccessibilityLabel;
@property (copy) AMSMetricsEvent *metricsEvent;
@property (copy) NSString *preferredButtonActionIdentifier;
@property signed char preventsCancelButtonStyle;
@property long long style;
@property (copy) NSArray *textFields;
@property (copy) NSString *title;
@property (copy) NSString *titleAccessibilityLabel;
@property (copy) NSDictionary *userInfo;

/* class methods */
+ (signed char)supportsSecureCoding;
+ (id)requestWithTitle:(id)title message:(id)message;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)description;
- (id)init;
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;
- (id)initWithError:(id)error;
- (id)initWithTitle:(id)title message:(id)message;
- (void)addButtonAction:(id)action;
- (void)addTextField:(id)field;
- (id)initWithTitle:(id)title message:(id)message appearanceInfo:(id)info;
- (id)locateActionWithIdentifier:(id)identifier;
- (void)replaceAction:(id)action;

@end

#endif /* _AMSDialogRequest_h */
