//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSDelegateAuthenticateTask_h
#define _AMSDelegateAuthenticateTask_h

@import Foundation;

#include "ACAccount.h"
#include "AMSBagConsumer-Protocol.h"
#include "AMSBagProtocol-Protocol.h"
#include "AMSBiometricsSignatureResult.h"
#include "AMSDelegateAuthenticateRequest.h"
#include "AMSTask.h"
#include "AMSURLProtocolDelegate-Protocol.h"
#include "AMSURLSession.h"

@interface AMSDelegateAuthenticateTask : AMSTask <AMSURLProtocolDelegate, NSURLSessionDelegate, AMSBagConsumer>

@property (retain) ACAccount *account;
@property (readonly) AMSURLSession *session;
@property (readonly) id <AMSBagProtocol> bag;
@property (retain) NSDictionary *formData;
@property (readonly) AMSDelegateAuthenticateRequest *request;
@property (retain) AMSBiometricsSignatureResult *signatureResult;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)bagSubProfile;
+ (id)bagSubProfileVersion;
+ (id)bagKeySet;
+ (id)createBagForSubProfile;

/* instance methods */
- (void)_init;
- (id)_delegateAuthenticateResultFromUrlResult:(id)result;
- (id)_encodedURLRequestWithError:(id *)error;
- (id)_parseFormDataAsStringFromResult:(id)result;
- (id)_parseFormDataFromResult:(id)result;
- (id)_performDelegateAuthenticationWithError:(id *)error;
- (id)_urlRequestParameters;
- (id)delegateAuthenticateUrl;
- (id)initWithBag:(id)bag account:(id)account;
- (id)initWithDelegateAuthenticateRequest:(id)request bag:(id)bag account:(id)account;
- (id)performDelegateAuthentication;

@end

#endif /* _AMSDelegateAuthenticateTask_h */
