//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSDaemonConnectionProtocol_Protocol_h
#define _AMSDaemonConnectionProtocol_Protocol_h

@import Foundation;

@protocol AMSDaemonConnectionProtocol <NSObject>

@required

/* required instance methods */
- (void)getAccountCachedServerDataServiceProxyWithReplyHandler:(id /* block */)handler;
- (void)getAccountSignOutServiceProxyWithReplyHandler:(id /* block */)handler;
- (void)getCookieServiceProxyWithReplyHandler:(id /* block */)handler;
- (void)getDeviceMessengerServiceProxyWithDelegate:(id)delegate replyHandler:(id /* block */)handler;
- (void)getDismissQRDialogServiceProxyWithReplyHandler:(id /* block */)handler;
- (void)getFraudReportServiceProxyWithReplyHandler:(id /* block */)handler;
- (void)getKeychainServiceProxyWithReplyHandler:(id /* block */)handler;
- (void)getPurchaseServiceProxyWithReplyHandler:(id /* block */)handler;
- (void)getPushNotificationServiceProxyWithReplyHandler:(id /* block */)handler;
- (void)getSecurityServiceProxyWithDelegate:(id)delegate replyHandler:(id /* block */)handler;

@optional

@end

#endif /* _AMSDaemonConnectionProtocol_Protocol_h */
