//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSDeviceOfferRegistrationGroup_h
#define _AMSDeviceOfferRegistrationGroup_h

@import Foundation;

#include "AMSStorageDatabasePersistable-Protocol.h"

@interface AMSDeviceOfferRegistrationGroup : NSObject <AMSStorageDatabasePersistable>

@property (readonly) NSArray *registrationItems;
@property unsigned long long validationOptions;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (signed char)isEqual:(id)equal;
- (id)_initWithRegistrationItems:(id)items validationOptions:(unsigned long long)options;
- (signed char)_serialsMatchSerialsFromGroup:(id)group;
- (id)initWithDatabaseEntry:(id)entry;
- (id)initWithRegistrationItems:(id)items;
- (signed char)isEqualToRegistrationGroup:(id)group;
- (signed char)isModifiedVersionOfGroup:(id)group;
- (id)serializeToDictionary;

@end

#endif /* _AMSDeviceOfferRegistrationGroup_h */
