//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSDeviceMessenger_h
#define _AMSDeviceMessenger_h

@import Foundation;

#include "AMSDaemonConnection.h"
#include "AMSDeviceMessengerClientInterface-Protocol.h"
#include "AMSDeviceMessengerServiceInterface-Protocol.h"

@protocol OS_dispatch_queue;

@interface AMSDeviceMessenger : NSObject <AMSDeviceMessengerClientInterface> {
    /* instance variables */
    id <AMSDeviceMessengerServiceInterface> _proxyObject;
}

@property (retain) AMSDaemonConnection *connection;
@property (retain) NSObject<OS_dispatch_queue> *queue;
@property (retain) NSMutableArray *updateHandlers;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)init;
- (void)deviceMessengerDidClearMessage:(id)message;
- (void)deviceMessengerDidUpdateDevices;
- (id)_getProxyObject;
- (void)deviceMessengerDidReceiveReply:(id)reply;
- (id)_identifierFromDialogRequest:(id)request;
- (void)_sendDelegateUpdateForMessage:(id)message;
- (void)addUpdateHandlerForType:(long long)type filter:(id)filter handler:(id /* block */)handler;
- (void)deviceMessengerDidReceiveMessage:(id)message;
- (id)sendDialog:(id)dialog account:(id)account;

@end

#endif /* _AMSDeviceMessenger_h */
