//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSDelegateTokenTask_h
#define _AMSDelegateTokenTask_h

@import Foundation;

#include "AMSDelegateAuthenticateTask.h"
#include "AMSProcessInfo.h"
#include "AMSURLResult.h"
#include "AMSURLTaskInfo.h"

@interface AMSDelegateTokenTask : AMSDelegateAuthenticateTask

@property (retain) AMSURLTaskInfo *taskInfo;
@property (retain) AMSURLResult *urlResult;
@property (retain) AMSProcessInfo *processInfo;

/* instance methods */
- (void)AMSURLSession:(id)amsurlsession task:(id)task handleAuthenticateRequest:(id)request completion:(id /* block */)completion;
- (id)_parseBiometricsSignatureRequestFromTask:(id)task;
- (id)_performFallbackAuthentication;
- (id)authenticateTaskWithRequest:(id)request;
- (id)delegateAuthenticateUrl;
- (id)initWithDelegateAuthenticateRequest:(id)request bag:(id)bag processInfo:(id)info account:(id)account;
- (id)performRetrieveDelegateToken;

@end

#endif /* _AMSDelegateTokenTask_h */
