//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSDeviceOfferRegistrationPrivacyValidator_h
#define _AMSDeviceOfferRegistrationPrivacyValidator_h

@import Foundation;

#include "ACAccount.h"

@interface AMSDeviceOfferRegistrationPrivacyValidator : NSObject

@property (readonly) ACAccount *account;

/* class methods */
+ (id)_identifiersForValidationOptions:(unsigned long long)options;
+ (signed char)_isPrivacyAcknowledgementForIdentifier:(id)identifier satisfiedOnAccount:(id)account;
+ (signed char)_isPrivacyAcknowledgementForIdentifiers:(id)identifiers satisfiedOnAccount:(id)account;
+ (id)_masterEligibilityPrivacyOptionsIdentifiers;
+ (id)_minimumAcknowledgementVersionForIdentifier:(id)identifier;
+ (id)_privacyVersionMap;

/* instance methods */
- (id)initWithAccount:(id)account;
- (signed char)canMasterDevicePerformRegistration;
- (signed char)isPrivacyRequirementMetForOptions:(unsigned long long)options;

@end

#endif /* _AMSDeviceOfferRegistrationPrivacyValidator_h */
