//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSDaemonConnectionInterface_h
#define _AMSDaemonConnectionInterface_h

@import Foundation;

@interface AMSDaemonConnectionInterface : NSObject

/* class methods */
+ (id)interface;
+ (id)_deviceMessengerClientInterface;
+ (id)_accountCachedServerDataInterface;
+ (id)_accountSignOutInterface;
+ (void)_configureURLPresentationDelegateClasses:(id)classes;
+ (id)_cookieServiceInterface;
+ (id)_deviceMessengerServiceInterface;
+ (id)_dismissQRDialogServiceInterface;
+ (id)_fraudReportServiceInterface;
+ (id)_keychainServiceInterface;
+ (id)_purchaseServiceInterface;
+ (id)_securityClientInterface;
+ (id)_securityServiceInterface;
+ (void)_setUpSecurityInterfaceApplePayClassic:(id)classic;
+ (void)_setUpSecurityInterfaceBiometricSelectors:(id)selectors;
+ (void)_setUpSecurityInterfaceDeviceIdentitySelectors:(id)selectors;
+ (void)_setUpSecurityInterfaceHandleResponseSelector:(id)selector;
+ (void)_setUpSecurityInterfaceSignedHeadersSelector:(id)selector;
+ (void)_setUpSecurityInterfaceSilentEnrollmentSelector:(id)selector;

@end

#endif /* _AMSDaemonConnectionInterface_h */
