//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSDeviceOfferEligibilityTask_h
#define _AMSDeviceOfferEligibilityTask_h

@import Foundation;

#include "AMSBagProtocol-Protocol.h"
#include "AMSURLSession.h"

@interface AMSDeviceOfferEligibilityTask : NSObject

@property (retain) id <AMSBagProtocol> bag;
@property (readonly) NSString *deviceGUID;
@property (retain) AMSURLSession *urlSession;
@property (readonly) NSString *masterSerialNumber;

/* instance methods */
- (id)_accountEligibilityEncoderWithBag:(id)bag account:(id)account clientInfo:(id)info;
- (id)_accountEligibilityRequestParametersWithIdentifiers:(id)identifiers;
- (id)_deviceEligibilityEncoderWithBag:(id)bag clientInfo:(id)info;
- (id)_deviceEligibilityRequestParametersWithGroups:(id)groups;
- (id)_eligibilityRequest;
- (id)_offersDecodedFromResult:(id)result;
- (id)initWithBag:(id)bag deviceGUID:(id)guid masterSerialNumber:(id)number urlSession:(id)session;
- (id)performAccountEligibility:(id)eligibility forOffers:(id)offers clientInfo:(id)info;
- (id)performAnonymousDeviceEligibility:(id)eligibility clientInfo:(id)info;

@end

#endif /* _AMSDeviceOfferEligibilityTask_h */
