//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSDeviceOfferRegistrationItem_h
#define _AMSDeviceOfferRegistrationItem_h

@import Foundation;

#include "AMSStorageDatabasePersistable-Protocol.h"

@interface AMSDeviceOfferRegistrationItem : NSObject <AMSStorageDatabasePersistable>

@property (readonly) NSString *model;
@property (readonly) NSString *serialNumber;
@property (readonly) NSData *validationData;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (signed char)isEqual:(id)equal;
- (id)initWithDatabaseEntry:(id)entry;
- (id)initWithSerialNumber:(id)number model:(id)model validationData:(id)data;
- (signed char)isEqualToRegistrationItem:(id)item;
- (id)serializeToDictionary;

@end

#endif /* _AMSDeviceOfferRegistrationItem_h */
