//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSDeviceIdentityCertificateTask_h
#define _AMSDeviceIdentityCertificateTask_h

@import Foundation;

#include "AMSBagProtocol-Protocol.h"
#include "AMSTask.h"

@protocol OS_dispatch_queue;

@interface AMSDeviceIdentityCertificateTask : AMSTask

@property (retain) id <AMSBagProtocol> bag;
@property (retain) NSObject<OS_dispatch_queue> *requestQueue;

/* instance methods */
- (id)initWithBag:(id)bag;
- (id)performDeviceIdentityRequestForAbsinthe;
- (id)performDeviceIdentityRequestForFraudReport;
- (id)performDeviceIdentityRequestWithBaaOptions:(id)options ttlBagKey:(id)key logInformation:(id)information;

@end

#endif /* _AMSDeviceIdentityCertificateTask_h */
