//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSDataMigratorOptions_h
#define _AMSDataMigratorOptions_h

@import Foundation;

@interface AMSDataMigratorOptions : NSObject

@property (copy) NSString *currentBuildVersion;
@property (readonly) NSArray *optionsArray;
@property (copy) NSString *previousBuildVersion;
@property unsigned long long scenario;

/* class methods */
+ (id)_stringFromOptionsArray:(id)array atIndex:(unsigned long long)index;

/* instance methods */
- (id)init;
- (id)initWithOptionsArray:(id)array;

@end

#endif /* _AMSDataMigratorOptions_h */
