//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSDaemonConnection_h
#define _AMSDaemonConnection_h

@import Foundation;

#include "AMSDServiceBrokerProtocol-Protocol.h"

@protocol OS_dispatch_queue;

@interface AMSDaemonConnection : NSObject <AMSDServiceBrokerProtocol>

@property (retain, nonatomic) NSXPCConnection *sharedConnection;
@property (readonly) NSObject<OS_dispatch_queue> *sharedConnectionAccessQueue;
@property (readonly) NSMutableArray *interruptionHandlers;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (void)dealloc;
- (id)init;
- (void)_handleInterruption;
- (void)addInterruptionHandler:(id /* block */)handler;
- (id)_connectionProxyWithAccessBlock:(id /* block */)block;
- (void)_connectionSyncProxyWithAccessBlock:(id /* block */)block;
- (void)_errorForwardingProxyForServiceProxy:(id)proxy proxyReplyError:(id)error interface:(id)interface proxyPromise:(id)promise;
- (void)_handleInvalidation;
- (void)_initializeConnection;
- (id)_serviceInterfaceForSelector:(SEL)selector;
- (id)accountCachedServerDataService;
- (id)accountSignOutServiceProxy;
- (void)attemptResumeIfRequired;
- (id)callService:(id)service then:(id /* block */)then;
- (id)cookieServiceProxy;
- (id)cookieServiceProxySyncWithError:(id *)error;
- (id)deviceMessengerProxyWithDelegate:(id)delegate;
- (id)dismissQRDialogServiceProxy;
- (id)fraudReportServiceProxy;
- (id)keychainServiceProxy;
- (id)purchaseServiceProxy;
- (id)pushNotificationService;
- (id)securityServiceProxyWithDelegate:(id)delegate;

@end

#endif /* _AMSDaemonConnection_h */
