//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSEngagementObserverInfo_h
#define _AMSEngagementObserverInfo_h

@import Foundation;

@protocol OS_dispatch_queue;

@interface AMSEngagementObserverInfo : NSObject

@property (retain) NSMutableSet *underlyingPlacements;
@property (retain) NSMutableSet *underlyingServiceTypes;
@property (readonly) NSSet *placements;
@property (readonly) NSSet *serviceTypes;
@property (retain) NSObject<OS_dispatch_queue> *dispatchQueue;

/* instance methods */
- (id)initWithQueue:(id)queue;
- (void)addServiceType:(id)type;
- (void)addPlacements:(id)placements;
- (void)removePlacement:(id)placement;
- (void)removeServiceType:(id)type;

@end

#endif /* _AMSEngagementObserverInfo_h */
