//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSEngagementCacheDatabase_h
#define _AMSEngagementCacheDatabase_h

@import Foundation;

#include "AMSSQLiteConnection.h"
#include "AMSSQLiteConnectionDelegate-Protocol.h"

@interface AMSEngagementCacheDatabase : NSObject <AMSSQLiteConnectionDelegate>

@property (retain) AMSSQLiteConnection *connection;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (signed char)openAtPath:(id)path error:(id *)error;
- (signed char)closeWithError:(id *)error;
- (void)_performTransaction:(id /* block */)transaction;
- (signed char)collectGarbageWithError:(id *)error;
- (signed char)connectionNeedsResetForCorruption:(id)corruption;
- (signed char)insertResponseData:(id)data filterData:(id)data expiration:(id)expiration error:(id *)error;
- (signed char)selectWithExpirationDate:(id)date handler:(id /* block */)handler error:(id *)error;

@end

#endif /* _AMSEngagementCacheDatabase_h */
