//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSEngagementAppResponseModel_h
#define _AMSEngagementAppResponseModel_h

@import Foundation;

@interface AMSEngagementAppResponseModel : NSObject

@property (readonly) NSDictionary *definition;
@property (readonly) NSString *cacheKey;
@property (readonly) NSDate *created;
@property (readonly) NSDictionary *responseData;

/* class methods */
+ (signed char)_shouldEvictDefinition:(id)definition created:(id)created;

/* instance methods */
- (id)exportObject;
- (id)initWithCacheObject:(id)object;
- (id)initWithData:(id)data cacheInfo:(id)info;
- (signed char)matchesEvent:(id)event;

@end

#endif /* _AMSEngagementAppResponseModel_h */
