//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSEngagementMessageAction_h
#define _AMSEngagementMessageAction_h

@import Foundation;

#include "AMSMetricsEvent.h"

@interface AMSEngagementMessageAction : NSObject

@property (copy) NSDictionary *clickstreamMetricsEvent;
@property (retain) NSURL *deepLink;
@property (retain) NSString *identifier;
@property (retain) NSURL *iconURL;
@property (retain) NSString *kind;
@property (copy) AMSMetricsEvent *metricsEvent;
@property (copy) NSDictionary *parameters;
@property signed char requiresDelegate;
@property long long style;
@property (retain) NSString *title;

/* instance methods */
- (id)initWithJSObject:(id)jsobject;
- (id)makeDialogAction;

@end

#endif /* _AMSEngagementMessageAction_h */
