//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSEngagementExtensionConnection_h
#define _AMSEngagementExtensionConnection_h

@import Foundation;

#include "_EXMainConnectionHandler-Protocol.h"

@interface AMSEngagementExtensionConnection : NSObject <_EXMainConnectionHandler>

@property (readonly) id principalObject;

/* instance methods */
- (id)initWithPrincipalObject:(id)object;
- (signed char)shouldAcceptXPCConnection:(id)xpcconnection;
- (void)performRequestWithObject:(id)object completion:(id /* block */)completion;

@end

#endif /* _AMSEngagementExtensionConnection_h */
