//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSEngagementPlacementInfo_h
#define _AMSEngagementPlacementInfo_h

@import Foundation;

@interface AMSEngagementPlacementInfo : NSObject

@property (readonly) NSDictionary *context;
@property (readonly) NSString *placement;
@property signed char supportsMultipleMessages;

/* instance methods */
- (id)initWithPlacement:(id)placement context:(id)context;
- (id)makeRawDictionary;

@end

#endif /* _AMSEngagementPlacementInfo_h */
