//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSEngagement_h
#define _AMSEngagement_h

@import Foundation;

#include "AMSBagConsumer-Protocol.h"
#include "AMSBagProtocol-Protocol.h"
#include "AMSEngagementConnection.h"
#include "AMSEngagementMessageCache.h"

@protocol OS_dispatch_queue;

@interface AMSEngagement : NSObject <AMSBagConsumer> {
    /* instance variables */
    NSObject<OS_dispatch_queue> *_callbackQueue;
}

@property (retain) NSMapTable *observerInfo;
@property (retain) NSMutableSet *runningPromises;
@property (retain) id <AMSBagProtocol> bag;
@property (retain) AMSEngagementConnection *connection;
@property (readonly) AMSEngagementMessageCache *cacheInfo;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)_connection;
+ (id)notificationCenter;
+ (id)_notifyQueue;
+ (id)bagSubProfile;
+ (id)bagSubProfileVersion;
+ (double)_enqueueTimeout;
+ (id)_engagementQueue;
+ (void)_recordLoggingEventWithBag:(id)bag enqueueData:(id)data eventType:(id)type userInfo:(id)info destinations:(id)destinations error:(id)error;
+ (id)createBagForSubProfile;

/* instance methods */
- (void)dealloc;
- (id)init;
- (id)sync;
- (id)enqueueEvent:(id)event;
- (void)_connectionErrorNotification;
- (id)_createCombinedLogKey;
- (id)_enqueue:(id)_enqueue;
- (id)_enqueueWithContext:(id)context;
- (void)_failAllRunningPromisesWithError:(id)error;
- (void)_handleServiceResponse:(id)response;
- (void)_manageRunningPromise:(id)promise;
- (void)_observeNotifications;
- (id)_parseActions:(id)actions;
- (void)_pushEventReceived:(id)received;
- (void)_removeRunningPromise:(id)promise;
- (void)_scheduleSyncIfNeeded:(id)needed;
- (void)addCachePolicy:(long long)policy forPlacements:(id)placements serviceType:(id)type;
- (void)addObserver:(id)observer placement:(id)placement serviceType:(id)type;
- (void)addObserver:(id)observer placement:(id)placement serviceType:(id)type queue:(id)queue;
- (void)addObserver:(id)observer placements:(id)placements serviceType:(id)type;
- (void)addObserver:(id)observer placements:(id)placements serviceType:(id)type queue:(id)queue;
- (id)contentInfoForApp:(id)app cacheKey:(id)key version:(id)version;
- (id)enqueueData:(id)data;
- (id)enqueueMessageEvent:(id)event;
- (void)handleDialogResult:(id)result;
- (void)handlePushEvent:(id)event;
- (id)initWithBag:(id)bag;
- (void)removeObserver:(id)observer placement:(id)placement serviceType:(id)type;
- (id)syncDestinations:(id)destinations;
- (id)syncMetricsIdentifiers;
- (id)syncWithRequest:(id)request;
- (id)treatmentStoreService;

@end

#endif /* _AMSEngagement_h */
