//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSEngagementMessageEvent_h
#define _AMSEngagementMessageEvent_h

@import Foundation;

#include "AMSEngagementEvent-Protocol.h"

@interface AMSEngagementMessageEvent : NSObject <AMSEngagementEvent>

@property (copy) NSArray *placementInfo;
@property (copy) NSString *serviceType;
@property (readonly) NSDictionary *engagementData;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (id)initWithServiceType:(id)type placements:(id)placements;
- (id)initWithServiceType:(id)type placementInfo:(id)info;

@end

#endif /* _AMSEngagementMessageEvent_h */
