//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSEngagementMessageRequest_h
#define _AMSEngagementMessageRequest_h

@import Foundation;

#include "AMSEngagementMessageAction.h"
#include "AMSEngagementRequest.h"
#include "AMSMetricsEvent.h"

@interface AMSEngagementMessageRequest : NSObject

@property (retain) NSArray *debugInfo;
@property (retain) NSArray *actions;
@property (retain) NSDictionary *appearanceInfo;
@property (copy) NSDictionary *clickstreamMetricsEvent;
@property (retain) AMSEngagementMessageAction *defaultAction;
@property (retain) AMSEngagementRequest *engagementRequest;
@property (retain) NSURL *iconURL;
@property (copy) NSString *identifier;
@property signed char isMessageCached;
@property (copy) AMSMetricsEvent *metricsEvent;
@property long long presentationAction;
@property long long style;
@property (copy) NSString *subtitle;
@property (copy) NSString *subtitleAccessibilityLabel;
@property (copy) NSString *title;
@property (copy) NSString *titleAccessibilityLabel;

/* instance methods */
- (id)initWithJSObject:(id)jsobject;
- (id)makeDialogRequest;

@end

#endif /* _AMSEngagementMessageRequest_h */
