//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSEngagementClientData_h
#define _AMSEngagementClientData_h

@import Foundation;

@interface AMSEngagementClientData : NSObject

@property (retain) NSMutableDictionary *apps;
@property (retain) NSString *lastSyncedBuild;

/* class methods */
+ (void)_registerNotifications;
+ (id)_sharedQueue;
+ (void)_assertEngagementd;
+ (id)_fetchClientData;
+ (signed char)_isDaemon;
+ (id)clientDataURL;
+ (void)erase;
+ (id)loadFromDisk;

/* instance methods */
- (void)setAllowedEvents:(id)events appIdentifier:(id)identifier;
- (id)_appForIdentifier:(id)identifier;
- (void)_enumerateAppsWithBlock:(id /* block */)block;
- (void)_setApp:(id)app forIdentifier:(id)identifier;
- (void)addCachedResponseData:(id)data cacheInfo:(id)info appIdentifier:(id)identifier;
- (id)cachedResponseDataForEvent:(id)event;
- (signed char)destination:(id)destination allowsEvent:(id)event;
- (id)destinationsForEvent:(id)event;
- (id)initWithCacheObject:(id)object;
- (void)saveToDisk;

@end

#endif /* _AMSEngagementClientData_h */
