//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSFamilyAccountPair_h
#define _AMSFamilyAccountPair_h

@import Foundation;

@interface AMSFamilyAccountPair : NSObject

@property (readonly, nonatomic) unsigned long long downloaderAccountID;
@property (readonly, nonatomic) unsigned long long familyID;
@property (readonly, nonatomic) unsigned long long purchaserAccountID;

/* instance methods */
- (id)initWithDownloaderAccountID:(unsigned long long)id purchaserAccountID:(unsigned long long)id familyID:(unsigned long long)id;

@end

#endif /* _AMSFamilyAccountPair_h */
