//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSFailingBagValue_h
#define _AMSFailingBagValue_h

@import Foundation;

#include "AMSFrozenBagValue.h"

@interface AMSFailingBagValue : AMSFrozenBagValue

@property (retain) NSError *error;

/* instance methods */
- (id)initWithKey:(id)key valueType:(unsigned long long)type error:(id)error;
- (void)valueWithCompletion:(id /* block */)completion;

@end

#endif /* _AMSFailingBagValue_h */
