//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSFinanceExpressCheckoutResponse_h
#define _AMSFinanceExpressCheckoutResponse_h

@import Foundation;

#include "AMSFinancePaymentSheetResponse.h"

@interface AMSFinanceExpressCheckoutResponse : AMSFinancePaymentSheetResponse

/* class methods */
+ (signed char)_isExpressCheckoutEnabledForBag:(id)bag;
+ (signed char)_isExpressCheckoutRecordUserChoiceEnabledForBag:(id)bag;
+ (signed char)_isFlagEnabled;
+ (signed char)isEligibleForBag:(id)bag;
+ (signed char)isExpressCheckoutPayload:(id)payload;
+ (signed char)isExpressCheckoutShouldCheckForWalletBiometricsForBag:(id)bag;

/* instance methods */
- (id)initWithResponseDictionary:(id)dictionary taskInfo:(id)info;

@end

#endif /* _AMSFinanceExpressCheckoutResponse_h */
