//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSFeatureFlagTask_h
#define _AMSFeatureFlagTask_h

@import Foundation;

#include "AMSBagConsumer-Protocol.h"
#include "AMSTask.h"

@interface AMSFeatureFlagTask : AMSTask <AMSBagConsumer>

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (void)clearCache;
+ (id)_cacheDirectory;
+ (id)_cachePath;
+ (id)_deviceClass;
+ (id)bagSubProfile;
+ (id)bagSubProfileVersion;
+ (id)lastFetchedDate;
+ (signed char)_cacheResponse:(id)response error:(id *)error;
+ (void)_handleDeletedITFEsFromResponse:(id)response;
+ (id)cachedRemoteGroups;
+ (id)createBagForSubProfile;

/* instance methods */
- (id)perform;
- (id)_updateRemoteFeatureFlags;

@end

#endif /* _AMSFeatureFlagTask_h */
