//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSFollowUpItem_h
#define _AMSFollowUpItem_h

@import Foundation;

#include "ACAccount.h"
#include "AMSFollowUpNotification.h"
#include "AMSMetricsEvent.h"

@protocol OS_dispatch_queue;

@interface AMSFollowUpItem : NSObject

@property (retain) NSObject<OS_dispatch_queue> *internalQueue;
@property (retain) NSObject<OS_dispatch_queue> *metricsQueue;
@property (retain) ACAccount *account;
@property (retain) AMSFollowUpNotification *notification;
@property (retain) NSArray *actions;
@property (readonly) signed char active;
@property (readonly) NSString *backingIdentifier;
@property (retain) NSString *bundleIconName;
@property signed char disableGrouping;
@property long long displayStyle;
@property (retain) NSDate *expirationDate;
@property signed char expirationDateHidden;
@property (retain) NSString *footer;
@property (readonly) NSString *groupIdentifier;
@property signed char hardwareOffer;
@property (retain) NSString *identifier;
@property (retain) NSString *informativeText;
@property (retain) NSString *logKey;
@property signed char keepNotificationOnLockscreen;
@property (copy) AMSMetricsEvent *metricsEvent;
@property signed char newDeviceOutreach;
@property long long priority;
@property signed char shouldPostNotification;
@property (retain) NSString *title;
@property (retain) NSMutableDictionary *userInfo;

/* class methods */
+ (id)_dateFromString:(id)string;
+ (id)backingIdentifierForIdentifier:(id)identifier account:(id)account;
+ (id)componentsFromBackingIdentifier:(id)identifier;

/* instance methods */
- (signed char)isHardwareOffer;
- (id)generateItem;
- (id)initWithFollowUpItem:(id)item;
- (id)initWithIdentifier:(id)identifier account:(id)account priority:(long long)priority;
- (id)initWithIdentifier:(id)identifier jsonDictionary:(id)dictionary account:(id)account priority:(long long)priority logKey:(id)key;
- (signed char)isExpirationDateHidden;
- (signed char)isNewDeviceOutreach;
- (id)postMetricsWithBag:(id)bag;
- (id)postMetricsWithBagContract:(id)contract;
- (signed char)shouldOverwriteItem:(id)item;

@end

#endif /* _AMSFollowUpItem_h */
