//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSFDSRequest_h
#define _AMSFDSRequest_h

@import Foundation;

#include "ACAccount.h"
#include "AMSFDSOptions.h"

@interface AMSFDSRequest : NSObject <NSCopying, NSSecureCoding>

@property (readonly) ACAccount *account;
@property (readonly) unsigned long long accountType;
@property (copy) NSString *logKey;
@property (readonly) AMSFDSOptions *options;
@property (readonly, copy) NSNumber *purchaseIdentifier;

/* class methods */
+ (signed char)supportsSecureCoding;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;
- (id)initWithPurchaseIdentifier:(id)identifier account:(id)account options:(id)options;

@end

#endif /* _AMSFDSRequest_h */
