//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSFraudReportResponse_h
#define _AMSFraudReportResponse_h

@import Foundation;

@interface AMSFraudReportResponse : NSObject <NSSecureCoding>

@property (retain) NSString *nameSpace;
@property long long reportedScore;
@property long long newScore;
@property (retain) NSString *proof;
@property (retain) NSString *evaluatedElement;
@property (retain) NSString *finalizedElement;
@property (retain) NSString *keyID;

/* class methods */
+ (signed char)supportsSecureCoding;

/* instance methods */
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;
- (id)initWithDictionary:(id)dictionary keyID:(id)id;
- (id)initWithURLResult:(id)urlresult keyID:(id)id;

@end

#endif /* _AMSFraudReportResponse_h */
