//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSFinanceAuthenticateResponse_h
#define _AMSFinanceAuthenticateResponse_h

@import Foundation;

#include "AMSAuthenticateRequest.h"
#include "AMSFinanceDialogResponse.h"
#include "AMSFinancePerformable-Protocol.h"

@interface AMSFinanceAuthenticateResponse : NSObject <AMSFinancePerformable>

@property (retain) NSDictionary *dialogDictionary;
@property (readonly) AMSFinanceDialogResponse *dialogResponse;
@property (readonly) AMSAuthenticateRequest *authenticateRequest;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)_authenticateRequestWithAuthType:(unsigned long long)type taskInfo:(id)info dialogResponse:(id)response serviceIdentifier:(id)identifier;
+ (id)_handleAuthResult:(id)result authError:(id)error originalRequest:(id)request actionResult:(id)result redirectURL:(id)url taskInfo:(id)info;
+ (void)_handleDialogFromAuthError:(id)error taskInfo:(id)info;
+ (id)_performAuthRequest:(id)request actionResult:(id)result redirectURL:(id)url taskInfo:(id)info;
+ (id)_performSyncAuthRequest:(id)request actionResult:(id)result redirectURL:(id)url taskInfo:(id)info;
+ (id)_presentAuthRequest:(id)request taskInfo:(id)info;
+ (id)_serviceIdentifierForResponse:(id)response taskInfo:(id)info;
+ (void)_updateTaskWithAuthedAccount:(id)account taskInfo:(id)info;
+ (void)_updateTaskWithLastCredentialSource:(id)source taskInfo:(id)info;
+ (unsigned long long)authenticationTypeForResponse:(id)response responseDictionary:(id)dictionary;
+ (id)performAuthFromResponse:(id)response taskInfo:(id)info;

/* instance methods */
- (id)_locateActionableButtonUsingDialogResponse:(id)response;
- (id)initWithResponseDictionary:(id)dictionary taskInfo:(id)info;
- (id)performWithTaskInfo:(id)info;

@end

#endif /* _AMSFinanceAuthenticateResponse_h */
