//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSFeatureFlagITFE_h
#define _AMSFeatureFlagITFE_h

@import Foundation;

@interface AMSFeatureFlagITFE : NSObject

@property (nonatomic) signed char enabled;
@property (nonatomic) signed char readonly;
@property (copy, nonatomic) NSString *value;

/* class methods */
+ (id)_flagGroupITFEs;
+ (id)_concreteITFEs;
+ (id)_customITFEs;
+ (signed char)_isITFEValueCustom:(id)custom;
+ (id)_mutableITFEs;
+ (id)_profileITFEs;
+ (id)_remoteGroupITFEs;
+ (id)fetchCustomFeatures;
+ (id)fetchMutableFeatures;
+ (id)fetchProfileFeatures;
+ (void)removeOrphanITFEValues:(id)itfevalues;
+ (void)resetFeatures;
+ (void)setMutableFeatureName:(id)name toValue:(id)value;
+ (void)verifyOrphans;
+ (void)verifyOrphansForGroups:(id)groups;

/* instance methods */
- (unsigned long long)hash;
- (signed char)isEqual:(id)equal;
- (signed char)isEnabled;
- (signed char)isReadonly;
- (void)toggle:(signed char)toggle;
- (id)initWithValue:(id)value isEnabled:(signed char)enabled isMutable:(signed char)_mutable;

@end

#endif /* _AMSFeatureFlagITFE_h */
