//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSFeatureFlagGroup_h
#define _AMSFeatureFlagGroup_h

@import Foundation;

@interface AMSFeatureFlagGroup : NSObject

@property (retain, nonatomic) NSMutableArray *mutableFlags;
@property (copy, nonatomic) NSString *name;
@property (readonly, nonatomic) NSArray *flags;

/* class methods */
+ (signed char)disableFlagGroupWithName:(id)name error:(id *)error;
+ (id)_normalizedFlagGroupsFromFlagGroups:(id)groups;
+ (id)allFlagGroups;
+ (id)allFlagGroupsIncludingHidden:(signed char)hidden;
+ (id)allFlagGroupsIncludingHidden:(signed char)hidden searchDirectory:(id)directory;
+ (signed char)enableFlagGroupWithName:(id)name error:(id *)error;
+ (id)fetchFlagGroupWithName:(id)name;
+ (id)flagGroupWithName:(id)name includingHidden:(signed char)hidden;
+ (id)groupsFromDomainData:(id)data domain:(id)domain;
+ (id)groupsFromDomainData:(id)data domain:(id)domain mutableFeatures:(id)features profileFeatures:(id)features includesHidden:(signed char)hidden;
+ (void)resetAllFlagGroups;
+ (signed char)setFlagGroupWithName:(id)name enabled:(signed char)enabled error:(id *)error;

/* instance methods */
- (id)initWithName:(id)name;
- (void)reset;
- (id)_completedFlags;
- (id)_developmentFlags;
- (id)_groupKeyForDevelopmentPhase:(long long)phase;
- (id)_groupKeyForType:(long long)type;
- (id)_testableFlags;
- (id)activateFlagsIfNeededForDevelopmentPhase:(long long)phase;
- (id)activateFlagsIfNeededForType:(long long)type;
- (void)activateITFEs;
- (id)allITFEs;
- (void)appendFlag:(id)flag;
- (id)completedFlags;
- (id)developmentFlags;
- (id)fetchAllGroupKeys;
- (id)flagsForDevelopmentPhase:(long long)phase;
- (id)flagsForType:(long long)type;
- (id)initWithName:(id)name domain:(id)domain;
- (signed char)isDevelopmentPhaseEnabled:(long long)enabled;
- (signed char)isGroupTypeEnabled:(long long)enabled;
- (void)setFlagsForDevelopmentPhase:(long long)phase enabled:(signed char)enabled;
- (void)setGroupType:(long long)type enabled:(signed char)enabled;
- (id)testableFlags;

@end

#endif /* _AMSFeatureFlagGroup_h */
