//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSFamilyInfoLookupResult_h
#define _AMSFamilyInfoLookupResult_h

@import Foundation;

@interface AMSFamilyInfoLookupResult : NSObject

@property (readonly) NSDictionary *dictionaryRepresentation;
@property (readonly) signed char cached;
@property (readonly) NSArray *familyMembers;
@property (readonly) NSNumber *headOfHouseholdICloudDSID;
@property (readonly) signed char headOfHouseholdSharingPayment;

/* class methods */
+ (id)_familyMembersFromDictionaryRepresentation:(id)representation;

/* instance methods */
- (id)description;
- (signed char)isCached;
- (signed char)isHeadOfHouseholdSharingPayment;
- (id)initWithDictionaryRepresentation:(id)representation cached:(signed char)cached;

@end

#endif /* _AMSFamilyInfoLookupResult_h */
