//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSFollowUp_h
#define _AMSFollowUp_h

@import Foundation;

@class FLFollowUpController;
@protocol OS_dispatch_queue;

@interface AMSFollowUp : NSObject

@property (retain, nonatomic) FLFollowUpController *followUpController;
@property (retain, nonatomic) NSObject<OS_dispatch_queue> *followUpQueue;

/* instance methods */
- (id)init;
- (id)_pendingFollowUpWithBackingIdentifier:(id)identifier error:(id *)error;
- (id)clearFollowUpItem:(id)item;
- (id)clearFollowUpWithBackingIdentifier:(id)identifier;
- (id)clearFollowUpWithIdentifier:(id)identifier account:(id)account;
- (id)pendingFollowUpWithIdentifier:(id)identifier account:(id)account;
- (id)pendingFollowUps;
- (id)pendingFollowUpsForAccount:(id)account;
- (id)postFollowUpItem:(id)item;

@end

#endif /* _AMSFollowUp_h */
