//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSFinanceResponse_h
#define _AMSFinanceResponse_h

@import Foundation;

#include "ACAccount.h"
#include "AMSFinanceAuthenticateResponse.h"
#include "AMSFinanceDialogResponse.h"
#include "AMSFinancePaymentSheetResponse.h"
#include "AMSURLTaskInfo.h"

@interface AMSFinanceResponse : NSObject

@property (retain) AMSFinanceAuthenticateResponse *cachedAuthenticateResponse;
@property (retain) AMSFinanceDialogResponse *cachedDialogResponse;
@property (retain) AMSFinancePaymentSheetResponse *cachedPaymentSheetResponse;
@property (readonly) long long dialogKind;
@property (retain) NSDictionary *responseDictionary;
@property (retain) AMSURLTaskInfo *taskInfo;
@property (readonly) ACAccount *account;
@property (readonly) NSArray *actions;
@property (readonly) NSArray *pingURLs;
@property (readonly) NSError *serverError;
@property (readonly) signed char supportedProtocolVersion;
@property (readonly) NSURL *versionMismatchURL;

/* class methods */
+ (id)valueForProtocolKey:(id)key inResponse:(id)response;

/* instance methods */
- (id)initWithTaskInfo:(id)info decodedObject:(id)object;
- (id)_performerForActionDictionary;
- (id)_performerForAuthenticate;
- (id)_performerForCreditDisplay;
- (id)_performerForDialog;
- (id)_performerForExpressCheckout;
- (id)_performerForPaymentSheetWithDelegateAuthentication:(signed char)authentication;
- (id)_valueForProtocolKey:(id)key;

@end

#endif /* _AMSFinanceResponse_h */
