//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSFollowUpAction_h
#define _AMSFollowUpAction_h

@import Foundation;

#include "AMSMetricsEvent.h"

@protocol OS_dispatch_queue;

@interface AMSFollowUpAction : NSObject

@property (retain, nonatomic) NSString *backingIdentifier;
@property (retain, nonatomic) NSObject<OS_dispatch_queue> *internalQueue;
@property (retain, nonatomic) NSObject<OS_dispatch_queue> *actionQueue;
@property (retain) NSString *identifier;
@property (retain) NSString *label;
@property (retain) NSString *logKey;
@property (copy) AMSMetricsEvent *metricsEvent;
@property (retain) NSString *parentIdentifier;
@property (retain) NSString *preferredClient;
@property (retain) NSURLRequest *request;
@property signed char requiresFollowUpUI;
@property signed char shouldClear;
@property (retain) NSURL *url;
@property (retain) NSMutableDictionary *userInfo;

/* instance methods */
- (id)initWithAction:(id)action;
- (id)initWithLabel:(id)label;
- (id)initWithLabel:(id)label parentIdentifier:(id)identifier;
- (void)_setUserInfoProperty:(id)property forKey:(id)key;
- (id)generateAction;
- (id)initWithAction:(id)action parentIdentifier:(id)identifier;
- (id)initWithItem:(id)item action:(id)action;
- (id)initWithJSONDictionary:(id)jsondictionary parentIdentifier:(id)identifier;
- (id)performActionsWithBag:(id)bag account:(id)account;
- (id)performActionsWithContract:(id)contract account:(id)account;
- (id)postMetricsWithBag:(id)bag;
- (id)postMetricsWithBagContract:(id)contract;

@end

#endif /* _AMSFollowUpAction_h */
