//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSFamilyInfoLookupTask_h
#define _AMSFamilyInfoLookupTask_h

@import Foundation;

#include "ACAccount.h"
#include "AMSBagConsumer-Protocol.h"
#include "AMSBagProtocol-Protocol.h"
#include "AMSTask.h"

@interface AMSFamilyInfoLookupTask : AMSTask <AMSBagConsumer>

@property (readonly) ACAccount *account;
@property (readonly) id <AMSBagProtocol> bag;
@property (retain) NSString *logKey;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)bagSubProfile;
+ (id)bagSubProfileVersion;
+ (id)_processURLResult:(id)urlresult;
+ (id)bagKeySet;
+ (id)createBagForSubProfile;

/* instance methods */
- (id)fetchFamilyInfoLookupFromServer;
- (void)_cacheFamilyInfoLookupResult:(id)result forAccount:(id)account;
- (id)_cachedFamilyInfoLookupResultForAccount:(id)account;
- (id)_currentCachedFamilyInfo;
- (id)_pathForCachedFamilyInfoLookupResult;
- (id)_performFamilyInfoRequestForAccount:(id)account error:(id *)error;
- (id)fetchFamilyInfoLookupFromCache;
- (id)initWithAccount:(id)account bag:(id)bag;
- (id)initWithBag:(id)bag;
- (id)initWithBagContract:(id)contract;
- (id)performFamilyInfoLookup;
- (id)performFamilyInfoLookupWithCachePolicy:(long long)policy;

@end

#endif /* _AMSFamilyInfoLookupTask_h */
