//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSFollowUpNotification_h
#define _AMSFollowUpNotification_h

@import Foundation;

#include "AMSFollowUpAction.h"

@interface AMSFollowUpNotification : NSObject

@property (retain) AMSFollowUpAction *activateAction;
@property (retain) NSSet *options;
@property (retain) NSString *informativeText;
@property (retain) NSString *title;

/* class methods */
+ (id)defaultOptions;
+ (id)optionForString:(id)string;

/* instance methods */
- (id)init;
- (id)generateNotification;
- (id)initWithJSONDictionary:(id)jsondictionary parentIdentifier:(id)identifier logKey:(id)key;

@end

#endif /* _AMSFollowUpNotification_h */
