//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSFinancePaymentSheetResponse_h
#define _AMSFinancePaymentSheetResponse_h

@import Foundation;

#include "AMSFinanceAuthenticateResponse.h"
#include "AMSFinancePerformable-Protocol.h"
#include "AMSPaymentSheetRequest.h"

@interface AMSFinancePaymentSheetResponse : NSObject <AMSFinancePerformable>

@property (readonly) AMSFinanceAuthenticateResponse *authenticateResponse;
@property (readonly) NSDictionary *metricsDictionary;
@property (readonly) AMSPaymentSheetRequest *paymentSheetRequest;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)_attributedListDictionaryForValues:(id)values account:(id)account;
+ (id)_attributedStringForAttributedArray:(id)array account:(id)account;
+ (id)_attributedStringForAttributedDictionary:(id)dictionary account:(id)account;
+ (id)_attributedStringForSalableInfoStringArray:(id)array account:(id)account shouldUppercase:(signed char)uppercase;
+ (id)_attributedStringForSalableInfoStyledStringArray:(id)array account:(id)account shouldUppercase:(signed char)uppercase;
+ (id)_attributedStringForStringArray:(id)array useGrey:(signed char)grey account:(id)account shouldUppercase:(signed char)uppercase;
+ (long long)_confirmationTitleForString:(id)string;
+ (id)_createMerchantSessionFromDictionary:(id)dictionary;
+ (id)_flexListDictionaryForValues:(id)values styles:(id)styles account:(id)account shouldUppercaseText:(signed char)text designVersion:(id)version;
+ (id)_flexListLeadingItemForValues:(id)values styles:(id)styles;
+ (id)_greyAttributedStringForAttributedString:(id)string range:(NSRange)range;
+ (long long)_payeeInferredFromEnumeratedTitle:(id)title;
+ (long long)_salableIconForString:(id)string;
+ (id)_salableInfoDictionaryForValues:(id)values styles:(id)styles account:(id)account shouldUppercaseText:(signed char)text designVersion:(id)version;
+ (id)_salableInfoForKey:(id)key inDictionary:(id)dictionary shouldUppercase:(signed char)uppercase;
+ (id)_styleDictionaryWithName:(id)name styles:(id)styles;
+ (id)attributedStringWithString:(id)string styles:(id)styles;
+ (id)createRequestFromDictionary:(id)dictionary confirmationOnly:(signed char)only delegateAuthenticationRequired:(signed char)required biometricSignatureRequired:(signed char)required authenticateResponse:(id)response taskInfo:(id)info account:(id)account;
+ (id)fallbackTitleFromResponse:(id)response;

/* instance methods */
- (id)_enrichedMetricsDictionaryWithFinanceDictionary:(id)dictionary;
- (id)_performAuthorizationDialogProxyWithTaskInfo:(id)info;
- (id)initWithResponseDictionary:(id)dictionary confirmationOnly:(signed char)only delegateAuthenticationRequired:(signed char)required biometricSignatureRequired:(signed char)required taskInfo:(id)info;
- (id)performWithTaskInfo:(id)info;

@end

#endif /* _AMSFinancePaymentSheetResponse_h */
