//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSHTTPArchive_h
#define _AMSHTTPArchive_h

@import Foundation;

@interface AMSHTTPArchive : NSObject <NSSecureCoding>

@property (retain) NSData *backingJSONData;
@property signed char compressed;
@property (readonly) NSData *JSONData;
@property (retain) NSString *urlString;

/* class methods */
+ (signed char)supportsSecureCoding;
+ (id)directory;
+ (id)merge:(id)merge;
+ (id)_createJSONObjectForEntries:(id)entries;
+ (id)_createJSONObjectForTaskMetrics:(id)metrics requestData:(id)data responseData:(id)data;
+ (double)_timeIntervalFromFilename:(id)filename;
+ (id)ams_dateFormatterForTimeZone:(id)zone;
+ (id)ams_generateCommentsStringForMetrics:(id)metrics;
+ (id)ams_generateContentDictionaryForResponse:(id)response responseData:(id)data;
+ (id)ams_generateHeadersArrayForHTTPHeaders:(id)httpheaders;
+ (id)ams_generateRequestDictionaryForMetrics:(id)metrics requestData:(id)data;
+ (id)ams_generateResponseDictionaryForMetrics:(id)metrics responseData:(id)data;
+ (id)merge:(id)merge withEstimatedFileSizeLimit:(unsigned long long)limit;
+ (void)removeHTTPArchiveFilesOlderThanDate:(id)date;

/* instance methods */
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;
- (signed char)isCompressed;
- (id)initWithHTTPArchiveTaskInfo:(id)info;
- (id)initWithJSONObject:(id)jsonobject;
- (id)initWithMetrics:(id)metrics requestData:(id)data responseData:(id)data;
- (void)logHARData;
- (signed char)writeToDiskWithError:(id *)error compressed:(signed char)compressed;
- (signed char)writeToDiskWithError:(id *)error compressed:(signed char)compressed appendCombined:(signed char)combined;

@end

#endif /* _AMSHTTPArchive_h */
