//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSHandleDialogResultTask_h
#define _AMSHandleDialogResultTask_h

@import Foundation;

#include "ACAccount.h"
#include "AMSBagProtocol-Protocol.h"
#include "AMSDialogRequest.h"
#include "AMSDialogResult.h"
#include "AMSProcessInfo.h"
#include "AMSTask.h"

@interface AMSHandleDialogResultTask : AMSTask

@property (copy) ACAccount *account;
@property (readonly) id <AMSBagProtocol> bag;
@property (retain) AMSProcessInfo *clientInfo;
@property (copy) NSString *proxyBundleId;
@property (readonly) AMSDialogRequest *request;
@property (readonly) AMSDialogResult *result;
@property (readonly, copy) NSError *error;

/* instance methods */
- (id)perform;
- (id)initWithRequest:(id)request result:(id)result error:(id)error bag:(id)bag;
- (id)initWithResult:(id)result bag:(id)bag;

@end

#endif /* _AMSHandleDialogResultTask_h */
