//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSKeybag_h
#define _AMSKeybag_h

@import Foundation;

#include "AMSFairPlayContext.h"

@protocol OS_dispatch_queue;

@interface AMSKeybag : NSObject

@property (retain) NSObject<OS_dispatch_queue> *dispatchQueue;
@property (retain) AMSFairPlayContext *fairPlayContext;

/* class methods */
+ (id)sharedInstance;

/* instance methods */
- (id)init;
- (unsigned int)fairplayContextWithError:(id *)error;
- (signed char)importDiversityBagWithData:(id)data error:(id *)error;
- (signed char)importKeybagData:(id)data outError:(id *)error;
- (signed char)importKeybagWithData:(id)data error:(id *)error;
- (id)keybagSyncData:(id)data transactionType:(unsigned int)type outError:(id *)error;
- (id)keybagSyncDataWithAccountID:(id)id transactionType:(unsigned int)type error:(id *)error;
- (id)kybsyncData:(id)data transationType:(unsigned int)type error:(id *)error;
- (void)resetContext;

@end

#endif /* _AMSKeybag_h */
