//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSKeychainOptions_h
#define _AMSKeychainOptions_h

@import Foundation;

@interface AMSKeychainOptions : NSObject <NSCopying, NSSecureCoding>

@property (copy) NSString *clientCertLabel;
@property (copy) NSString *intermediateCertLabel;
@property (copy) NSString *label;
@property unsigned long long purpose;
@property signed char regenerateKeys;
@property unsigned long long style;
@property signed char authenticationFallbackVisible;
@property signed char displayAuthenticationReason;
@property (copy) NSString *prompt;

/* class methods */
+ (signed char)supportsSecureCoding;
+ (unsigned long long)preferredAttestationStyle;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)description;
- (id)init;
- (signed char)isEqual:(id)equal;
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;
- (id)optionsDictionary;
- (signed char)_compareString:(id)string withString:(id)string;
- (id)initWithOptionsDictionary:(id)dictionary;

@end

#endif /* _AMSKeychainOptions_h */
