//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSLRUCache_h
#define _AMSLRUCache_h

@import Foundation;

#include "AMSDoubleLinkedList.h"

@protocol OS_dispatch_queue;

@interface AMSLRUCache : NSObject

@property (retain) NSObject<OS_dispatch_queue> *accessQueue;
@property (retain) NSMutableDictionary *backingDictionary;
@property (retain) AMSDoubleLinkedList *backingList;
@property (readonly) unsigned long long count;
@property (readonly) unsigned long long maxSize;

/* instance methods */
- (id)description;
- (id)init;
- (unsigned long long)_count;
- (id)objectForKey:(id)key;
- (void)removeAllObjects;
- (void)setObject:(id)object forKey:(id)key;
- (id)objectForKey:(id)key canLogCacheMisses:(signed char)misses;
- (id)objectForKey:(id)key withCreationBlock:(id /* block */)block;
- (void)_addObject:(id)object forKey:(id)key;
- (void)_removeObjectForKey:(id)key;
- (id)allObjectsAndKeys;
- (id)initWithMaxSize:(unsigned long long)size;

@end

#endif /* _AMSLRUCache_h */
