//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSLookupDecoder_h
#define _AMSLookupDecoder_h

@import Foundation;

#include "AMSResponseDecoding-Protocol.h"

@interface AMSLookupDecoder : NSObject <AMSResponseDecoding>

/* instance methods */
- (id)resultFromResult:(id)result error:(id *)error;

@end

#endif /* _AMSLookupDecoder_h */
