//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSMetricsDatabaseDataSource_h
#define _AMSMetricsDatabaseDataSource_h

@import Foundation;

#include "AMSMetricsDataSource-Protocol.h"
#include "AMSMetricsDatabase.h"

@protocol OS_dispatch_queue;

@interface AMSMetricsDatabaseDataSource : NSObject <AMSMetricsDataSource>

@property (readonly) AMSMetricsDatabase *database;
@property (retain) NSString *currentLockKey;
@property (retain) NSObject<OS_dispatch_queue> *queue;
@property (readonly) NSString *containerIdentifier;
@property (readonly) long long eventCount;

/* instance methods */
- (void)dealloc;
- (void)cancel;
- (id)initWithContainerIdentifier:(id)identifier;
- (void)removeAllEvents;
- (void)didFinishBatching;
- (id)enqueueEvents:(id)events;
- (void)enumerateSortedEventsForTopic:(id)topic block:(id /* block */)block;
- (signed char)removeEvents:(id)events error:(id *)error;
- (signed char)skipEvents:(id)events error:(id *)error;
- (signed char)willStartBatchingWithLogKey:(id)key error:(id *)error;

@end

#endif /* _AMSMetricsDatabaseDataSource_h */
