//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSMutablePromise_h
#define _AMSMutablePromise_h

@import Foundation;

#include "AMSPromise.h"

@interface AMSMutablePromise : AMSPromise

/* class methods */
+ (signed char)finishPromise:(id)promise withResult:(id)result error:(id)error;
+ (id)promiseWithAll:(id)all;
+ (id)promiseWithAny:(id)any;
+ (void)startTimeoutForPromise:(id)promise timeout:(double)timeout;
+ (signed char)_finishPromise:(id)promise withResult:(id)result error:(id)error logDuplicateFinishes:(signed char)finishes;
+ (signed char)cancelPromise:(id)promise;
+ (signed char)finishPromise:(id)promise withError:(id)error;
+ (signed char)finishPromise:(id)promise withPromise:(id)promise;
+ (signed char)finishPromise:(id)promise withResult:(id)result;
+ (id)promiseWithAll:(id)all timeout:(double)timeout;
+ (id)promiseWithAny:(id)any timeout:(double)timeout;
+ (id)promiseWithFlattenedPromises:(id)promises;

/* instance methods */
- (signed char)cancel;
- (signed char)finishWithError:(id)error;
- (signed char)finishWithResult:(id)result error:(id)error;
- (id)initWithTimeout:(double)timeout;
- (signed char)finishWithResult:(id)result;
- (id)catchWithBlock:(id /* block */)block;
- (signed char)_finishWithResult:(id)result error:(id)error logDuplicateFinishes:(signed char)finishes;
- (id)continueWithBlock:(id /* block */)block;
- (signed char)finishWithPromise:(id)promise;
- (signed char)finishWithPromiseResult:(id)result;
- (id)promiseWithTimeout:(double)timeout;
- (void)startTimeout:(double)timeout;
- (id)thenWithBlock:(id /* block */)block;

@end

#endif /* _AMSMutablePromise_h */
