//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSMarketingItemTask_h
#define _AMSMarketingItemTask_h

@import Foundation;

#include "ACAccount.h"
#include "AMSBagConsumer-Protocol.h"
#include "AMSBagProtocol-Protocol.h"
#include "AMSProcessInfo.h"
#include "AMSTask.h"

@interface AMSMarketingItemTask : AMSTask <AMSBagConsumer>

@property (retain) ACAccount *account;
@property (readonly) id <AMSBagProtocol> bag;
@property (copy) NSDictionary *contextInfo;
@property (readonly) NSString *clientIdentifier;
@property (retain) AMSProcessInfo *clientInfo;
@property (readonly) NSString *clientVersion;
@property signed char hydrateRelatedContent;
@property (retain) NSString *logKey;
@property (retain) NSString *offerHints;
@property (readonly) NSString *placement;
@property (readonly) NSString *serviceType;
@property signed char includeMediaAssets;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)bagSubProfile;
+ (id)bagSubProfileVersion;
+ (id)bagKeySet;
+ (id)createBagForSubProfile;

/* instance methods */
- (id)perform;
- (id)_fetchItems;
- (id)_processMediaResultFromPromise:(id)promise;
- (id)_fetchItemsFromURL:(id)url;
- (id)initWithAccount:(id)account bag:(id)bag clientIdentifier:(id)identifier clientVersion:(id)version placement:(id)placement serviceType:(id)type;
- (id)initWithBag:(id)bag clientIdentifier:(id)identifier clientVersion:(id)version placement:(id)placement serviceType:(id)type;
- (id)performWithFetchOnly;

@end

#endif /* _AMSMarketingItemTask_h */
