//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSMescalSession_h
#define _AMSMescalSession_h

@import Foundation;

#include "AMSMescalFairPlay.h"
#include "AMSURLSession.h"

@protocol OS_dispatch_queue;

@interface AMSMescalSession : NSObject {
    /* instance variables */
    NSData *_certificateData;
    AMSURLSession *_urlSession;
    AMSMescalFairPlay *_fairPlayContext;
    long long _mescalType;
}

@property (readonly) NSObject<OS_dispatch_queue> *dispatchQueue;

/* class methods */
+ (id)defaultSession;
+ (id)primeSession;
+ (id)sessionWithType:(long long)type;

/* instance methods */
- (id)initWithType:(long long)type;
- (id)_cachedCertPath;
- (id)_cachedCertData;
- (id)_establishContextWithBag:(id)bag error:(id *)error;
- (signed char)_cacheCertData:(id)data expiration:(double)expiration;
- (id)_loadCertificateDataWithBag:(id)bag error:(id *)error;
- (id)_postExchangeData:(id)data bag:(id)bag error:(id *)error;
- (void)_resetSession;
- (signed char)_shouldRetryFairPlayForError:(id)error;
- (signed char)_verifyEntitlements;
- (id)primeSignatureForData:(id)data bag:(id)bag error:(id *)error;
- (id)signData:(id)data bag:(id)bag error:(id *)error;
- (signed char)verifyData:(id)data withSignature:(id)signature bag:(id)bag error:(id *)error;
- (signed char)verifyPrimeSignature:(id)signature error:(id *)error;

@end

#endif /* _AMSMescalSession_h */
