//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSMockURLOverride_h
#define _AMSMockURLOverride_h

@import Foundation;

#include "AMSMockURLResponse.h"
#include "AMSObservable.h"

@interface AMSMockURLOverride : NSObject <NSCopying>

@property (retain) NSMutableArray *comparators;
@property (retain) AMSObservable *executedObservable;
@property (retain) AMSMockURLResponse *response;

/* class methods */
+ (id)overrideWithHost:(id)host usingResponse:(id)response;
+ (id)overrideWithPathComponent:(id)component usingResponse:(id)response;
+ (id)overrideWithURLRegex:(id)urlregex usingResponse:(id)response;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)init;
- (void)_withURLMatchingHost:(id)host containingPath:(id)path queryItems:(id)items;
- (signed char)shouldOverrideURLRequest:(id)urlrequest;
- (void)withHTTPBodyValidation:(id /* block */)validation encoding:(long long)encoding;
- (void)withHTTPHeaderValidation:(id /* block */)validation;
- (void)withResponse:(id)response;
- (void)withURLContainingPath:(id)path;
- (void)withURLMatchingHost:(id)host;
- (void)withURLQueryItems:(id)items;
- (void)withURLRegexValidation:(id)validation;

@end

#endif /* _AMSMockURLOverride_h */
