//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSMediaInvokeAuthenticationQueuedObject_h
#define _AMSMediaInvokeAuthenticationQueuedObject_h

@import Foundation;

#include "AMSPromise.h"
#include "AMSURLTaskInfo.h"

@interface AMSMediaInvokeAuthenticationQueuedObject : NSObject

@property (retain) NSURLResponse *response;
@property (retain) AMSURLTaskInfo *taskInfo;
@property (retain) AMSPromise *pendingPromise;
@property signed char ignoringResult;

/* instance methods */

@end

#endif /* _AMSMediaInvokeAuthenticationQueuedObject_h */
