//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSMetricsIdentifierInfo_h
#define _AMSMetricsIdentifierInfo_h

@import Foundation;

@interface AMSMetricsIdentifierInfo : NSObject

@property signed char crossDeviceSync;
@property (retain) NSString *idKey;
@property (retain) NSString *name;
@property (retain) NSString *storeUUID;
@property (retain) NSString *value;
@property (retain) NSDate *expires;
@property signed char deleted;
@property (retain) NSDate *lastSync;
@property (retain) NSDate *modified;

/* instance methods */
- (void)populateDictionary:(id)dictionary;
- (id)syncStateFieldName;

@end

#endif /* _AMSMetricsIdentifierInfo_h */
