//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSMetricsIdentifierKey_h
#define _AMSMetricsIdentifierKey_h

@import Foundation;

@interface AMSMetricsIdentifierKey : NSObject

@property signed char crossDeviceSync;
@property (retain) NSString *name;
@property signed char isActiveITunesAccountRequired;

/* class methods */
+ (id)keyWithName:(id)name crossDeviceSync:(signed char)sync;
+ (id)keyWithName:(id)name crossDeviceSync:(signed char)sync isActiveITunesAccountRequired:(signed char)required;

/* instance methods */

@end

#endif /* _AMSMetricsIdentifierKey_h */
