//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSMonitoredAccountStore_h
#define _AMSMonitoredAccountStore_h

@import Foundation;

#include "ACMonitoredAccountStore.h"

@interface AMSMonitoredAccountStore : ACMonitoredAccountStore { // (Swift)
    /* instance variables */
    //  typeStore;
    //  error;
    //  fallback;
}

/* class methods */
+ (id)shared;

/* instance methods */
- (id)init;
- (id)initWithEffectiveBundleID:(id)id;
- (id)monitoredAccountWithIdentifier:(id)identifier;
- (id)accountTypeWithAccountTypeIdentifier:(id)identifier error:(id *)error;
- (void)accountTypeWithIdentifier:(id)identifier completion:(id /* block */)completion;
- (void)accountWithIdentifier:(id)identifier completion:(id /* block */)completion;
- (id)accountWithIdentifier:(id)identifier error:(id *)error;
- (void)accountsWithAccountType:(id)type options:(unsigned long long)options completion:(id /* block */)completion;
- (id)accountsWithAccountType:(id)type options:(unsigned long long)options error:(id *)error;
- (id)initWithAccountTypes:(id)types delegate:(id)delegate;
- (id)initWithAccountTypes:(id)types propertiesToPrefetch:(id)prefetch delegate:(id)delegate;
- (id)initWithRemoteEndpoint:(id)endpoint;
- (id)initWithRemoteEndpoint:(id)endpoint effectiveBundleID:(id)id;
- (id)initWithWithRemoteEndpoint:(id)endpoint effectiveBundleID:(id)id accountTypes:(id)types propertiesToPrefetch:(id)prefetch delegate:(id)delegate;

@end

#endif /* _AMSMonitoredAccountStore_h */
