//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSMediaACIService_h
#define _AMSMediaACIService_h

@import Foundation;

@interface AMSMediaACIService : NSObject { // (Swift)
    /* instance variables */
    //  clientIdentifier;
    //  keychainAccessGroup;
    //  bag;
    //  store;
    //  network;
    //  refresh;
    //  date;
}

/* instance methods */
- (id)init;
- (void)fetchMediaACIWithCompletionHandler:(id /* block */)handler;
- (id)initWithClientIdentifier:(id)identifier keychainAccessGroup:(id)group bag:(id)bag;

@end

#endif /* _AMSMediaACIService_h */
