//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSMarketingItemAction_h
#define _AMSMarketingItemAction_h

@import Foundation;

#include "AMSBuyParams.h"

@interface AMSMarketingItemAction : NSObject

@property (retain) NSDictionary *rawValues;
@property (readonly) AMSBuyParams *buyParams;
@property (readonly) NSString *callToActionLabel;
@property (readonly) NSString *disclaimerText;
@property (readonly) signed char isDefault;
@property (readonly) signed char isFamily;
@property (readonly) signed char isRecommended;
@property (readonly) NSString *offerID;
@property (readonly) NSNumber *price;
@property (readonly) NSString *priceForDisplay;
@property (readonly) NSNumber *priceDiff;
@property (readonly) NSString *priceDiffForDisplay;
@property (readonly) NSString *valuePropDetail;
@property (readonly) NSString *valuePropInfo;
@property (readonly) NSArray *serviceComponents;
@property (readonly) NSString *type;
@property (readonly) NSURL *url;

/* instance methods */
- (id)description;
- (id)name;
- (id)initWithDictionary:(id)dictionary;
- (id)_serviceNames;
- (id)freeTrialPeriod;
- (id)inAppID;
- (id)introOfferPrice;
- (id)_serviceComponentsFromMap:(id)map withNames:(id)names;
- (id)_servicesData;
- (id)dismissLabel;
- (id)introOfferPeriod;
- (id)introOfferPriceForDisplay;
- (signed char)isYearly;
- (id)priceFormatted;
- (id)priceString;
- (id)recurringSubscriptionPeriod;

@end

#endif /* _AMSMarketingItemAction_h */
