//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSMetricsBatch_h
#define _AMSMetricsBatch_h

@import Foundation;

#include "ACAccount.h"

@interface AMSMetricsBatch : NSObject

@property (retain) ACAccount *account;
@property signed char anonymous;
@property (retain) NSString *canaryIdentifier;
@property signed char containsLoadURL;
@property (retain) NSArray *droppedEvents;
@property (retain) NSArray *eventDictionaries;
@property (retain) NSArray *events;
@property (retain) NSURL *reportURL;
@property (retain) NSArray *skippedEvents;

/* instance methods */

@end

#endif /* _AMSMetricsBatch_h */
