//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSMediaToken_h
#define _AMSMediaToken_h

@import Foundation;

@interface AMSMediaToken : NSObject <NSCopying, NSSecureCoding>

@property (readonly) NSDate *expirationDate;
@property (readonly) double lifetime;
@property (readonly, copy) NSString *tokenString;
@property (readonly) signed char valid;

/* class methods */
+ (signed char)supportsSecureCoding;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)description;
- (signed char)isEqual:(id)equal;
- (signed char)isValid;
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;
- (signed char)isExpired;
- (id)initWithString:(id)string expirationDate:(id)date lifetime:(double)lifetime;
- (id)initWithString:(id)string expirationDate:(id)date lifetime:(double)lifetime valid:(signed char)valid;
- (id)invalidCopy;
- (double)percentageOfLifetimeRemaining;
- (signed char)willExpireWithin:(double)within;

@end

#endif /* _AMSMediaToken_h */
