//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSMediaTokenServiceDeserializer_h
#define _AMSMediaTokenServiceDeserializer_h

@import Foundation;

@interface AMSMediaTokenServiceDeserializer : NSObject

/* class methods */
+ (id)mediaTokenFromDictionary:(id)dictionary error:(id *)error;
+ (id)_correctPayload:(id)payload;
+ (id)_deserializeMediaTokenDictionary:(id)dictionary;

@end

#endif /* _AMSMediaTokenServiceDeserializer_h */
