//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSMutableLazyPromise_h
#define _AMSMutableLazyPromise_h

@import Foundation;

#include "AMSLazyPromise.h"

@interface AMSMutableLazyPromise : AMSLazyPromise

/* instance methods */
- (signed char)cancel;
- (id)initWithBlock:(id /* block */)block;
- (signed char)finishWithError:(id)error;
- (signed char)finishWithResult:(id)result error:(id)error;
- (signed char)finishWithResult:(id)result;
- (signed char)finishWithPromise:(id)promise;
- (id)initWithTimeout:(double)timeout block:(id /* block */)block;

@end

#endif /* _AMSMutableLazyPromise_h */
