//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSMetricsLoadURLContext_h
#define _AMSMetricsLoadURLContext_h

@import Foundation;

#include "AMSBagProtocol-Protocol.h"
#include "AMSProcessInfo.h"
#include "AMSURLRequestProperties.h"

@interface AMSMetricsLoadURLContext : NSObject

@property (retain) NSDictionary *decodedResponseBody;
@property (retain) AMSURLRequestProperties *properties;
@property (retain) id <AMSBagProtocol> bag;
@property (retain) NSError *error;
@property (retain) AMSProcessInfo *processInfo;
@property (retain) NSData *responseBody;
@property (retain) NSURLSession *session;
@property (retain) NSURLSessionTask *task;
@property (retain) NSURLSessionTaskMetrics *taskMetrics;
@property (readonly, copy) NSDictionary *metricsOverlay;

/* instance methods */
- (id)initWithTaskInfo:(id)info serverPayload:(id)payload;
- (void)setBagContract:(id)contract;
- (id)bagContract;
- (id)initWithTask:(id)task metrics:(id)metrics;
- (id)metricsDictionaryPromise;

@end

#endif /* _AMSMetricsLoadURLContext_h */
