//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSMetricsIdentifierStoreInfo_h
#define _AMSMetricsIdentifierStoreInfo_h

@import Foundation;

@interface AMSMetricsIdentifierStoreInfo : NSObject

@property (retain) NSString *account;
@property signed char crossDeviceSync;
@property double resetInterval;
@property (retain) NSDate *started;
@property (retain) NSString *storeKey;
@property (retain) NSString *storeUUID;
@property signed char deleted;
@property (retain) NSDate *lastSync;
@property (retain) NSDate *modified;

/* instance methods */

@end

#endif /* _AMSMetricsIdentifierStoreInfo_h */
