//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSMetricsIdentifierStore_h
#define _AMSMetricsIdentifierStore_h

@import Foundation;

#include "ACAccount.h"
#include "AMSProcessInfo.h"

@interface AMSMetricsIdentifierStore : NSObject

@property (retain) ACAccount *account;
@property (retain) AMSProcessInfo *clientInfo;
@property (retain) NSString *domain;
@property signed char includeAccountMatchStatus;
@property signed char isActiveITunesAccountRequired;
@property double resetInterval;

/* class methods */
+ (id)_database;
+ (id)_sync;
+ (id)_sharedQueue;
+ (id)_parametersForBag:(id)bag bagNamespace:(id)_namespace;
+ (id)_accountIdentifierForAccount:(id)account;
+ (id)_identifierStoreWithAccount:(id)account parameters:(id)parameters;
+ (void)cleanupIdentifiers;
+ (id)identifierForAccount:(id)account bag:(id)bag bagNamespace:(id)_namespace keyName:(id)name;
+ (id)identifierStoreWithAccount:(id)account bagNamespace:(id)_namespace bag:(id)bag;
+ (void)removeIdentifiersForAccount:(id)account;

/* instance methods */
- (void)reset;
- (id)_generateEventFieldsForKeys:(id)keys date:(id)date;
- (void)_generateFutureIdentifiersIfNeededForKeys:(id)keys storeInfo:(id)info afterPeriod:(long long)period inDatabase:(id)database date:(id)date;
- (id)_generateIdentifierKey:(id)key storeInfo:(id)info period:(long long)period;
- (id)_generateStoreKey;
- (id)_identifierInfoForKey:(id)key storeInfo:(id)info period:(long long)period inDatabase:(id)database date:(id)date setValue:(id)value lastSyncDate:(id)date needsToSync:(char *)sync error:(id *)error;
- (id)_identifierStoreInfoForKeys:(id)keys inDatabase:(id)database date:(id)date needsToSync:(char *)sync error:(id *)error;
- (id)_identifiersForKeys:(id)keys currentDate:(id)date;
- (void)_setIdentifier:(id)identifier withStartedDate:(id)date forKey:(id)key;
- (void)_setIdentifier:(id)identifier withStartedDate:(id)date lastSyncDate:(id)date forKey:(id)key;
- (id)generateEventFieldsForKeys:(id)keys;
- (id)generateEventFieldsForKeys:(id)keys date:(id)date;
- (id)identifierForKey:(id)key;
- (id)identifierIfExistsForKey:(id)key;
- (signed char)isAccountValidForKey:(id)key activeItunesAccountDSID:(inout id *)dsid;
- (void)setIdentifier:(id)identifier forKey:(id)key;

@end

#endif /* _AMSMetricsIdentifierStore_h */
