//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSMultiUserServiceProtocol_Protocol_h
#define _AMSMultiUserServiceProtocol_Protocol_h

@import Foundation;

@protocol AMSMultiUserServiceProtocol <NSObject>

@required

/* required instance methods */
- (void)performMultiUserAuthenticationForHomeUserIdentifier:(id)identifier completion:(id /* block */)completion;
- (void)exportMultiUserTokenForHomeIdentifier:(id)identifier generateIfMissing:(signed char)missing generateIfInvalid:(signed char)invalid completion:(id /* block */)completion;
- (void)generateInfoWithCompletion:(id /* block */)completion;
- (void)iTunesAccountForHomeWithIdentifier:(id)identifier completion:(id /* block */)completion;
- (void)iTunesAccountIsHomeOwner:(id)owner completion:(id /* block */)completion;
- (void)importMultiUserTokenWithInfoDictionary:(id)dictionary completion:(id /* block */)completion;
- (void)invalidateMultiUserTokenForAccount:(id)account homeUserIdentifier:(id)identifier completion:(id /* block */)completion;
- (void)invalidateMultiUserTokenForHomeIdentifier:(id)identifier completion:(id /* block */)completion;
- (void)multiUserTokenForAccount:(id)account completion:(id /* block */)completion;
- (void)multiUserTokenForAccount:(id)account homeUserIdentifier:(id)identifier qualityOfService:(long long)service completion:(id /* block */)completion;
- (void)refreshAfterTimeInterval:(double)interval completion:(id /* block */)completion;
- (void)setiTunesAccount:(id)account forHomeWithIdentifier:(id)identifier completion:(id /* block */)completion;
- (void)updateMultiUserTokenForAccount:(id)account completion:(id /* block */)completion;

@optional

@end

#endif /* _AMSMultiUserServiceProtocol_Protocol_h */
