//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSMetricsFigaroEventModifier_h
#define _AMSMetricsFigaroEventModifier_h

@import Foundation;

@interface AMSMetricsFigaroEventModifier : NSObject

@property (readonly) NSDictionary *fieldFilters;
@property (readonly) NSDictionary *metricsDictionary;
@property (readonly) NSDictionary *overrideDictionary;
@property (readonly) NSString *sampleSessionKey;
@property (readonly) double flushInterval;

/* instance methods */
- (id)_createSampleSessionKey;
- (id)_fieldFiltersFromOverrides:(id)overrides;
- (id)_overridePropertyForKey:(id)key;
- (signed char)_shouldSampleEvent:(id)event;
- (signed char)fieldFiltersMatchEvent:(id)event;
- (id)initWithMetricsDictionary:(id)dictionary overrideDictionary:(id)dictionary;
- (id)preparedEventPromiseWithEvent:(id)event;
- (id)reportingURLForEvent:(id)event;
- (signed char)shouldDropEvent:(id)event;
- (signed char)shouldSkipEvent:(id)event;

@end

#endif /* _AMSMetricsFigaroEventModifier_h */
