//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSMetricsDataSource_Protocol_h
#define _AMSMetricsDataSource_Protocol_h

@import Foundation;

@protocol AMSMetricsDataSource

@required

/* required instance methods */
- (void)cancel;
- (void)didFinishBatching;
- (void)enumerateSortedEventsForTopic:(id)topic block:(id /* block */)block;
- (signed char)removeEvents:(id)events error:(id *)error;
- (signed char)skipEvents:(id)events error:(id *)error;
- (signed char)willStartBatchingWithLogKey:(id)key error:(id *)error;

@optional

@end

#endif /* _AMSMetricsDataSource_Protocol_h */
