//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSMediaTask_h
#define _AMSMediaTask_h

@import Foundation;

#include "ACAccount.h"
#include "AMSBagConsumer-Protocol.h"
#include "AMSBagProtocol-Protocol.h"
#include "AMSProcessInfo.h"
#include "AMSTask.h"

@interface AMSMediaTask : AMSTask <AMSBagConsumer>

@property signed char URLKnownToBeTrusted;
@property (retain) ACAccount *account;
@property (retain) NSArray *additionalPlatforms;
@property (retain) NSDictionary *additionalQueryParams;
@property (readonly) id <AMSBagProtocol> bag;
@property (retain) NSArray *bundleIdentifiers;
@property signed char charts;
@property (readonly) NSString *clientIdentifier;
@property (retain) AMSProcessInfo *clientInfo;
@property (readonly) NSString *clientVersion;
@property (retain) NSDictionary *filters;
@property (retain) NSArray *includedResultKeys;
@property (retain) NSArray *itemIdentifiers;
@property (retain) NSString *logKey;
@property (retain) NSString *searchTerm;
@property (readonly) long long type;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)bagSubProfile;
+ (id)bagSubProfileVersion;
+ (id)bagKeySet;
+ (id)createBagForSubProfile;

/* instance methods */
- (id)perform;
- (id)initWithType:(long long)type clientIdentifier:(id)identifier clientVersion:(id)version bag:(id)bag;

@end

#endif /* _AMSMediaTask_h */
