//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSMutableBinaryPromise_h
#define _AMSMutableBinaryPromise_h

@import Foundation;

#include "AMSBinaryPromise.h"

@interface AMSMutableBinaryPromise : AMSBinaryPromise

/* class methods */
+ (signed char)cancelPromise:(id)promise;
+ (signed char)finishPromise:(id)promise withError:(id)error;
+ (signed char)finishPromise:(id)promise withPromise:(id)promise;
+ (signed char)finishPromise:(id)promise withSuccess:(signed char)success;
+ (signed char)finishPromise:(id)promise withSuccess:(signed char)success error:(id)error;

/* instance methods */
- (signed char)cancel;
- (signed char)finishWithError:(id)error;
- (signed char)finishWithPromise:(id)promise;
- (signed char)finishWithSuccess;
- (signed char)finishWithSuccess:(signed char)success error:(id)error;

@end

#endif /* _AMSMutableBinaryPromise_h */
