//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSMediaInvokeAuthenticationCoordinator_h
#define _AMSMediaInvokeAuthenticationCoordinator_h

@import Foundation;

#include "AMSPromise.h"
#include "os_unfair_lock_s.h"

@interface AMSMediaInvokeAuthenticationCoordinator : NSObject

@property (readonly) struct os_unfair_lock_s queueLock;
@property (readonly) NSMutableArray *invokeAuthQueue;
@property (retain) AMSPromise *inflightAuthPromise;

/* class methods */
+ (id)sharedInstance;

/* instance methods */
- (id)init;
- (void)_finishQueueWithAuthResult:(id)result queuedObjects:(id)objects;
- (id)addToQueueAndPerformAuthFromResponseIfNeeded:(id)needed taskInfo:(id)info;
- (id)performAuthFromResponse:(id)response taskInfo:(id)info;
- (void)updateQueueIfNeeded;

@end

#endif /* _AMSMediaInvokeAuthenticationCoordinator_h */
