//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSMediaTaskTypeConfig_h
#define _AMSMediaTaskTypeConfig_h

@import Foundation;

@interface AMSMediaTaskTypeConfig : NSObject

@property (readonly) NSString *hostBagKey;
@property (readonly) _Bool includePlatform;
@property (readonly) NSString *realm;
@property (readonly) long long type;
@property (readonly) NSString *typeString;

/* class methods */
+ (id)configForType:(long long)type;

/* instance methods */
- (id)initWithType:(long long)type typeString:(id)string hostBagKey:(id)key realm:(id)realm includePlatform:(signed char)platform;

@end

#endif /* _AMSMediaTaskTypeConfig_h */
