//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSMediaTokenServiceThrottler_h
#define _AMSMediaTokenServiceThrottler_h

@import Foundation;

@interface AMSMediaTokenServiceThrottler : NSObject

@property unsigned long long attemptNumber;
@property (retain) NSDate *throttleDate;
@property double baseSleepInterval;
@property double maxSleepInterval;

/* instance methods */
- (void)reset;
- (signed char)shouldThrottle;
- (void)throttle;
- (double)_calculateThrottleInterval;
- (id)initWithBaseSleepInterval:(double)interval maxSleepInterval:(double)interval;

@end

#endif /* _AMSMediaTokenServiceThrottler_h */
