//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSMockNetworkProxy_h
#define _AMSMockNetworkProxy_h

@import Foundation;

#include "AMSMockURLOverride.h"

@interface AMSMockNetworkProxy : NSURLProtocol

@property (retain) AMSMockURLOverride *currentOverride;

/* class methods */
+ (id)_overrides;
+ (signed char)canInitWithRequest:(id)request;
+ (id)canonicalRequestForRequest:(id)request;
+ (void)removeOverride:(id)override;
+ (void)addOverride:(id)override;
+ (void)clearOverrides;
+ (id)_executedOverrides;
+ (void)_removeAllOverrides;
+ (void)_removeOverride:(id)override;
+ (void)_sync:(id /* block */)_sync;
+ (id)executedOverrides;
+ (id)registeredOverrides;

/* instance methods */
- (void)stopLoading;
- (void)startLoading;
- (void)sendResponse:(id)response;
- (void)finishWithError:(id)error;
- (void)finishWithData:(id)data;
- (void)performRedirectFromResponse:(id)response;

@end

#endif /* _AMSMockNetworkProxy_h */
