//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSMercuryCacheFetchTask_h
#define _AMSMercuryCacheFetchTask_h

@import Foundation;

#include "ACAccount.h"
#include "AMSBagConsumer-Protocol.h"
#include "AMSBagProtocol-Protocol.h"
#include "AMSProcessInfo.h"
#include "AMSTask.h"

@interface AMSMercuryCacheFetchTask : AMSTask <AMSBagConsumer>

@property (readonly) ACAccount *account;
@property (readonly) id <AMSBagProtocol> bag;
@property (readonly) NSSet *cacheTypeIDs;
@property (readonly) NSString *clientIdentifier;
@property (retain) AMSProcessInfo *clientInfo;
@property (readonly) NSString *clientVersion;
@property (retain) NSString *logKey;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)bagSubProfile;
+ (id)bagSubProfileVersion;
+ (id)createBagForSubProfile;
+ (id)requestEncoderWithSharedProperties:(id)properties task:(id)task;
+ (id)sharedPropertiesFromTask:(id)task;

/* instance methods */
- (id)perform;
- (id)_updateEndpointURLRequestWithError:(id *)error;
- (id)initWithAccount:(id)account bag:(id)bag cacheTypeIDs:(id)ids clientIdentifier:(id)identifier clientVersion:(id)version;

@end

#endif /* _AMSMercuryCacheFetchTask_h */
