//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSNotificationSettingsItem_h
#define _AMSNotificationSettingsItem_h

@import Foundation;

@interface AMSNotificationSettingsItem : NSObject

@property (readonly) NSDictionary *dictionaryRepresentation;
@property (readonly) NSString *desc;
@property signed char enabled;
@property (readonly) NSString *identifier;
@property (readonly) NSString *title;
@property signed char userChanged;

/* instance methods */
- (id)description;
- (signed char)isEnabled;
- (id)initWithDictionaryRepresentation:(id)representation;
- (id)initWithTitle:(id)title description:(id)description identifier:(id)identifier enabled:(signed char)enabled;

@end

#endif /* _AMSNotificationSettingsItem_h */
