//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSNetworkConstraints_h
#define _AMSNetworkConstraints_h

@import Foundation;

#include "AMSBagConsumer-Protocol.h"

@interface AMSNetworkConstraints : NSObject <AMSBagConsumer>

@property (retain) NSMutableDictionary *sizeLimits;
@property (readonly) signed char anyNetworkTypeEnabled;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)bagSubProfile;
+ (id)bagSubProfileVersion;
+ (id)_networkConstraintsForMediaType:(id)type withArray:(id)array;
+ (id)bagKeySet;
+ (id)createBagForSubProfile;
+ (id)networkConstraintsForMediaType:(id)type withBag:(id)bag;

/* instance methods */
- (id)init;
- (signed char)isEqual:(id)equal;
- (void)_disableAllNetworkTypes;
- (id)_initWithStoreConstraintDictionary:(id)dictionary;
- (void)_setSizeLimit:(long long)limit forNetworkType:(id)type;
- (long long)_sizeLimitForNetworkType:(id)type;
- (signed char)hasSizeLimitForNetworkType:(id)type;
- (signed char)isAnyNetworkTypeEnabled;
- (signed char)isEqualToConstraints:(id)constraints;
- (long long)sizeLimitForNetworkType:(id)type;

@end

#endif /* _AMSNetworkConstraints_h */
