//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSOptional_h
#define _AMSOptional_h

@import Foundation;

@interface AMSOptional : NSObject

@property (readonly) id value;

/* class methods */
+ (id)optionalWithNil;
+ (id)optionalWithValue:(id)value;

/* instance methods */
- (id)init;
- (id)initWithValue:(id)value;

@end

#endif /* _AMSOptional_h */
