//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSOpenURL_h
#define _AMSOpenURL_h

@import Foundation;

#include "AMSBagProtocol-Protocol.h"
#include "AMSProcessInfo.h"

@interface AMSOpenURL : NSObject

@property (retain) NSMutableSet *attemptedTargets;
@property (readonly) NSURL *URL;
@property (retain) AMSProcessInfo *clientInfo;
@property (retain) id <AMSBagProtocol> bag;

/* class methods */
+ (id)_modifiedURLFromURL:(id)url bundleInfo:(id)info;
+ (signed char)_openURL:(id)url inApp:(id)app;
+ (unsigned long long)_openModeForStandardURL:(id)url inApp:(id)app withLinks:(id)links;
+ (signed char)_openURLWithLaunchServices:(id)services;
+ (signed char)_shouldOpenStandardURL:(id)url inApp:(id)app withLinks:(id)links;
+ (signed char)openStandardURL:(id)url;
+ (void)openURL:(id)url account:(id)account preferredClient:(id)client;
+ (id)openURL:(id)url clientInfo:(id)info bag:(id)bag;

/* instance methods */
- (signed char)_shouldOpenURL:(id)url;
- (signed char)_openURL:(id)url bundleInfo:(id)info;
- (id)_performOpen;
- (id)initWithURL:(id)url clientInfo:(id)info bag:(id)bag;

@end

#endif /* _AMSOpenURL_h */
