//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSObservable_h
#define _AMSObservable_h

@import Foundation;

@protocol OS_dispatch_queue;

@interface AMSObservable : NSObject

@property (readonly) unsigned long long behavior;
@property (retain) NSError *failureError;
@property (retain) NSString *logKey;
@property (retain) NSMutableArray *observers;
@property (retain) NSMutableArray *queuedResults;
@property (retain) NSObject<OS_dispatch_queue> *sendMessageQueue;
@property (retain) NSConditionLock *stateLock;
@property (readonly) signed char cancelled;
@property (readonly) signed char complete;

/* instance methods */
- (id)init;
- (signed char)isComplete;
- (signed char)cancel;
- (signed char)isCancelled;
- (id)initWithObserver:(id)observer;
- (void)subscribe:(id)subscribe;
- (signed char)_isComplete;
- (id)initWithObject:(id)object keyPath:(id)path options:(unsigned long long)options;
- (id)initWithNotification:(id)notification object:(id)object;
- (id)initWithObserver:(id)observer behavior:(unsigned long long)behavior;
- (id)initWithObservers:(id)observers;
- (id)initWithObservers:(id)observers behavior:(unsigned long long)behavior;
- (signed char)sendCompletion;
- (signed char)sendFailure:(id)failure;
- (signed char)sendResult:(id)result;
- (id)subscribeWithResultBlock:(id /* block */)block;
- (void)unsubscribe:(id)unsubscribe;
- (void)unsubscribeAll;

@end

#endif /* _AMSObservable_h */
