//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSPageRenderMetricsPresenter_h
#define _AMSPageRenderMetricsPresenter_h

@import Foundation;

#include "AMSBagProtocol-Protocol.h"
#include "AMSMetrics.h"
#include "AMSPageRenderMetricsEvent.h"

@interface AMSPageRenderMetricsPresenter : NSObject

@property (retain) id <AMSBagProtocol> bag;
@property (retain) AMSMetrics *metrics;
@property (retain) AMSPageRenderMetricsEvent *pageRenderEvent;

/* instance methods */
- (void)viewDidAppear;
- (void)viewDidDisappear;
- (void)viewDidLoad;
- (void)viewWillAppear;
- (void)viewWillDisappear;
- (void)endWithActivity:(long long)activity pageMetrics:(id)metrics;
- (void)enqueueEvent;
- (void)importTimings:(id)timings;
- (id)initWithBag:(id)bag metrics:(id)metrics;
- (void)startWithActivity:(long long)activity;

@end

#endif /* _AMSPageRenderMetricsPresenter_h */
