//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSPushConfiguration_h
#define _AMSPushConfiguration_h

@import Foundation;

@protocol AMSPushHandlerDelegate;

@interface AMSPushConfiguration : NSObject

@property (weak) id <AMSPushHandlerDelegate> delegate;
@property (retain) NSString *engagementPushTopic;
@property (retain) NSString *userNotificationExtensionId;
@property (retain) NSSet *enabledActionTypes;

/* instance methods */
- (id)initWithEnabledActionTypes:(id)types;

@end

#endif /* _AMSPushConfiguration_h */
