//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSPaymentSheetRequest_h
#define _AMSPaymentSheetRequest_h

@import Foundation;

#include "ACAccount.h"
#include "AMSBiometricsSignatureRequest.h"
#include "AMSCardSingleSelection.h"

@interface AMSPaymentSheetRequest : NSObject

@property (readonly) unsigned long long ams_confirmationStyle;
@property signed char isDelegateAuthentication;
@property (copy) NSDictionary *responseDictionary;
@property (copy) ACAccount *account;
@property (copy) NSString *accountHeader;
@property signed char applePayClassic;
@property (copy) NSArray *attributedList;
@property (retain) AMSBiometricsSignatureRequest *biometricsRequest;
@property long long confirmationTitle;
@property (copy) NSString *currencyCode;
@property (copy) NSString *countryCode;
@property (copy) NSString *delegateAuthenticateChallenge;
@property (copy) NSNumber *designVersion;
@property (copy) NSString *displayPrice;
@property (copy) NSString *explanation;
@property (copy) NSArray *flexList;
@property (retain) NSArray *inlineImages;
@property (retain) NSString *logKey;
@property (copy) NSDictionary *merchantSession;
@property (copy) NSString *message;
@property long long payee;
@property (copy) NSString *paymentSession;
@property (copy) NSString *paymentSummary;
@property (copy) NSArray *preSheetDialog;
@property (copy) NSNumber *price;
@property (copy) NSArray *priceSectionItems;
@property (copy) NSString *ratingHeader;
@property (copy) NSString *ratingValue;
@property signed char requiresAuthorization;
@property (readonly) signed char requiresDelegateAuthentication;
@property long long salableIcon;
@property (copy) NSURL *salableIconURL;
@property (copy) NSArray *salableInfo;
@property (copy) NSAttributedString *salableInfoLabel;
@property (copy) NSArray *secondaryFlexList;
@property long long secondarySalableIcon;
@property (copy) NSURL *secondarySalableIconURL;
@property (copy) NSArray *secondarySalableInfo;
@property (copy) NSAttributedString *secondarySalableInfoLabel;
@property (retain) AMSCardSingleSelection *selectedCard;
@property signed char shouldUppercaseText;
@property (copy) NSString *storeName;
@property (copy) NSArray *styles;
@property (copy) NSString *title;
@property long long titleType;
@property (copy) NSString *userAgent;

/* class methods */
+ (id)attributedStringByRemovingPlaceholderTagsFromAttributedString:(id)string;
+ (id)paymentSheetRequestFromDictionary:(id)dictionary account:(id)account;

/* instance methods */
- (id)init;
- (struct CGImage *)_createImageRefForImageRef:(struct CGImage *)ref withAdornmentStyle:(long long)style andDesignVersion:(id)version;
- (id)ams_createContentItemForAccount;
- (id)_attachInlineImagesToAttributedString:(id)string designVersion:(id)version bag:(id)bag;
- (id)_attachLeadingItem:(id)item attributedString:(id)string designVersion:(id)version;
- (id)_contentItemsForFlexibleList:(id)list assetCache:(id)cache designVersion:(id)version bag:(id)bag;
- (struct CGPath *)_createBorderPathForAdornmentStyle:(long long)style iconWidth:(double)width iconHeight:(double)height;
- (struct CGImage *)_createDefaultImageWithImageRef:(struct CGImage *)ref size:(CGSize)size borderPath:(struct CGPath *)path;
- (struct CGImage *)_createImageForAssetConfiguration:(id)configuration outAssetScale:(float *)scale;
- (struct CGImage *)_createImageMaskRefWithSize:(CGSize)size andPath:(struct CGPath *)path;
- (struct CGImage *)_createImageRefForAssetURL:(id)url size:(CGSize)size assetType:(long long)type outAssetScale:(float *)scale;
- (struct CGImage *)_createImageRefForImageSource:(struct CGImageSource *)source screenScale:(float)scale outAssetScale:(float *)scale;
- (struct CGImage *)_createImageRefForImageURL:(id)url outAssetScale:(float *)scale;
- (struct CGImage *)_createImageRefForPDFURL:(id)pdfurl size:(CGSize)size outAssetScale:(float *)scale;
- (struct CGImage *)_createImageRefWithURL:(id)url designVersion:(id)version adornmentStyle:(long long)style bag:(id)bag;
- (struct CGImage *)_createMaskedImageRefForImageRef:(struct CGImage *)ref withPathRef:(struct CGPath *)ref adornmentStyle:(long long)style andDesignVersion:(id)version;
- (struct CGImage *)_createRGBImageRefForGreyScaleImageRef:(struct CGImage *)ref width:(unsigned long long)width height:(unsigned long long)height;
- (struct CGImage *)_createRatingImageWithStringValue:(id)value assetScale:(float *)scale;
- (long long)_imageTypeForURL:(id)url;
- (CGRect)_rectWithAspectRatio:(CGSize)ratio insideRect:(CGRect)rect;
- (id)_replaceImagePlaceholderTag:(id)tag withAttributes:(id)attributes foregroundColor:(long long)color forAttributedString:(id)string;
- (id)_replaceImagePlaceholderTag:(id)tag withImageData:(id)data scale:(float)scale tint:(signed char)tint forAttributedString:(id)string;
- (signed char)_shouldDrawGrayBorderForMaskedImageWithDesignVersion:(id)version;
- (id)_summaryItemsForAttributedList:(id)list assetCache:(id)cache bag:(id)bag;
- (id)ams_contentItemForSalableInfoLabel:(id)label salableIconURL:(id)url salableIcon:(long long)icon assetCache:(id)cache designVersion:(id)version bag:(id)bag;
- (id)ams_createContentItemForDeviceName:(id)name;
- (id)ams_createContentItemForRating;
- (id)ams_createContentItemForSalableInfoWithAssetCache:(id)cache designVersion:(id)version bag:(id)bag;
- (id)ams_createContentItemsForFlexibleListWithAssetCache:(id)cache designVersion:(id)version bag:(id)bag;
- (id)ams_createContentItemsForPreScreenDialogWithAssetCache:(id)cache designVersion:(id)version bag:(id)bag;
- (id)ams_createSecondaryContentItemForSalableInfoWithAssetCache:(id)cache designVersion:(id)version bag:(id)bag;
- (id)ams_createSecondaryContentItemsForFlexibleListWithAssetCache:(id)cache designVersion:(id)version bag:(id)bag;
- (id)ams_createSummaryItems;
- (id)ams_createSummaryItemsForAttributedListWithAssetCache:(id)cache bag:(id)bag;
- (unsigned long long)ams_paymentRequestorType;
- (signed char)isApplePayClassic;
- (signed char)isDesignVersionEqual:(id)equal;
- (signed char)isDesignVersionEqualOrGreaterThan:(id)than;
- (signed char)isDesignVersionLessThan:(id)than;

@end

#endif /* _AMSPaymentSheetRequest_h */
