//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSPurchaseSIWATask_h
#define _AMSPurchaseSIWATask_h

@import Foundation;

#include "AMSPurchaseSIWA.h"
#include "AMSPurchaseTask.h"

@class AKAuthorization, AKCredentialRequestContext;

@interface AMSPurchaseSIWATask : AMSPurchaseTask

@property (retain, nonatomic) AMSPurchaseSIWA *purchaseSIWA;
@property (retain, nonatomic) AKCredentialRequestContext *requestContext;
@property (copy, nonatomic) NSUUID *continuationRequestIdentifier;
@property (copy, nonatomic) NSError *siwaError;
@property (nonatomic) signed char purchaseRequiresAuthorization;
@property (retain, nonatomic) AKAuthorization *authorization;

/* instance methods */
- (id)_cancelAuthorization;
- (signed char)_beginAuthorizationWasPerformed;
- (signed char)performPreActionRequestForTaskInfo:(id)info requiresAuthorization:(signed char)authorization error:(id *)error;
- (id)_beginAuthorization;
- (id)_continueAuthorization;
- (signed char)_siwaDidCommence;
- (void)_updateRequestContextWithPurchaseInfo:(id)info;
- (signed char)_willRequireAskToBuyForTaskInfo:(id)info;
- (id)initWithPurchaseSIWA:(id)siwa bag:(id)bag;
- (id)newAuthorizationController;
- (id)performPreauthenticate;
- (id)performPurchaseSIWA;
- (id)preauthenticateOptions;

@end

#endif /* _AMSPurchaseSIWATask_h */
