//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSPurchaseServiceInterface_Protocol_h
#define _AMSPurchaseServiceInterface_Protocol_h

@import Foundation;

@protocol AMSPurchaseServiceInterface <NSObject>

@required

/* required instance methods */
- (void)cacheFDS:(id)fds forPurchaseIdentifier:(id)identifier logKey:(id)key completion:(id /* block */)completion;
- (void)cachedFDSForPurchaseIdentifier:(id)identifier logKey:(id)key completion:(id /* block */)completion;
- (void)createODISessionWithSessionIdentifier:(id)identifier accountType:(unsigned long long)type bundleIdentifier:(id)identifier completion:(id /* block */)completion;
- (void)didConsumeFDSForPurchaseIdentifier:(id)identifier logKey:(id)key completion:(id /* block */)completion;
- (void)generateFDSWithRequest:(id)request completion:(id /* block */)completion;
- (void)getODIAssessmentForSessionIdentifier:(id)identifier clearCache:(signed char)cache completion:(id /* block */)completion;
- (void)partialFDSAssessmentForRequest:(id)request completion:(id /* block */)completion;
- (void)provideFeedbackOnPayloadOutcome:(unsigned long long)outcome sessionIdentifier:(id)identifier clearCache:(signed char)cache completion:(id /* block */)completion;
- (void)updateODIWithAttributes:(id)attributes forSessionIdentifier:(id)identifier completion:(id /* block */)completion;

@optional

@end

#endif /* _AMSPurchaseServiceInterface_Protocol_h */
