//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSPushRegisterTask_h
#define _AMSPushRegisterTask_h

@import Foundation;

#include "ACAccount.h"
#include "AMSBagProtocol-Protocol.h"
#include "AMSTask.h"

@interface AMSPushRegisterTask : AMSTask

@property (readonly) ACAccount *account;
@property (readonly) id <AMSBagProtocol> bag;
@property (readonly, copy) NSString *environment;
@property (readonly, copy) NSData *token;

/* instance methods */
- (id)performTask;
- (id)initWithAccount:(id)account token:(id)token environment:(id)environment bag:(id)bag;

@end

#endif /* _AMSPushRegisterTask_h */
