//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSPushParsableFollowUp_h
#define _AMSPushParsableFollowUp_h

@import Foundation;

#include "AMSBagConsumer-Protocol.h"
#include "AMSPushParsable-Protocol.h"
#include "AMSUserNotificationIntentDelegate-Protocol.h"

@interface AMSPushParsableFollowUp : NSObject <AMSPushParsable, AMSUserNotificationIntentDelegate, AMSBagConsumer>

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)bagSubProfile;
+ (id)bagSubProfileVersion;
+ (id)_createFollowUpItemFromPayload:(id)payload;
+ (id)_createFollowUpItemFromNotification:(id)notification;
+ (id)_createNotificationFromFollowUpItem:(id)item;
+ (id)_dateFromString:(id)string;
+ (void)_performClearWithPayload:(id)payload;
+ (void)_performPostWithPayload:(id)payload bag:(id)bag;
+ (signed char)_shouldAllowFollowUp:(id)up bag:(id)bag;
+ (signed char)_shouldClearFollowUpFromPayload:(id)payload;
+ (id)createBagForSubProfile;
+ (void)handleNotificationPayload:(id)payload config:(id)config bag:(id)bag;
+ (signed char)isDeviceOfferNotification:(id)notification;
+ (void)removeDeviceOfferWithPayload:(id)payload logKey:(id)key bag:(id)bag;
+ (signed char)shouldSkipAccountCheck;
+ (void)userNotification:(id)notification selectedButtonAction:(id)action bag:(id)bag;

@end

#endif /* _AMSPushParsableFollowUp_h */
