//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSPaymentSheetTask_h
#define _AMSPaymentSheetTask_h

@import Foundation;

#include "AMSBagProtocol-Protocol.h"
#include "AMSFinancePaymentSheetResponse.h"
#include "AMSPaymentSheetAssetCache.h"
#include "AMSPaymentSheetRequest.h"
#include "AMSPromise.h"
#include "AMSPurchaseInfo.h"
#include "AMSTask.h"
#include "PKPaymentAuthorizationControllerDelegate-Protocol.h"
#include "PKPaymentAuthorizationControllerPrivateDelegate-Protocol.h"
#include "_PaymentSheetState.h"

@class AKAppleIDAuthenticationContext, PKPaymentAuthorizationController;

@interface AMSPaymentSheetTask : AMSTask <PKPaymentAuthorizationControllerDelegate, PKPaymentAuthorizationControllerPrivateDelegate>

@property (retain) AMSPaymentSheetAssetCache *assetCache;
@property (retain, nonatomic) AKAppleIDAuthenticationContext *authenticationContext;
@property (retain) PKPaymentAuthorizationController *paymentAuthorizationController;
@property (retain) AMSPromise *paymentSheetPromise;
@property (readonly) AMSFinancePaymentSheetResponse *paymentSheetResponse;
@property (readonly) AMSPaymentSheetRequest *request;
@property (retain) _PaymentSheetState *state;
@property (retain) NSMutableArray *userActions;
@property (retain) id <AMSBagProtocol> bag;
@property (retain) NSDictionary *metricsDictionary;
@property (copy) NSString *presentingSceneBundleIdentifier;
@property (copy) NSString *presentingSceneIdentifier;
@property (retain) AMSPurchaseInfo *purchaseInfo;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (signed char)_shouldCompanionAuthFallbackToPasswordForError:(id)error;

/* instance methods */
- (signed char)cancel;
- (id)perform;
- (id)_paymentRequest;
- (float)_challengeSigningDelay;
- (void)_dismissPaymentAuthorizationController:(id)controller;
- (id)_metricsEvent;
- (void)_presentCompanionAuthenticationSheetWithPaymentRequest:(id)request purchaseResult:(id)result;
- (id)_presentPaymentSheetWithPaymentRequest:(id)request;
- (id)initWithRequest:(id)request bag:(id)bag;
- (void)paymentAuthorizationController:(id)controller didAuthorizePayment:(id)payment handler:(id /* block */)handler;
- (void)paymentAuthorizationController:(id)controller didEncounterAuthorizationEvent:(unsigned long long)event;
- (void)paymentAuthorizationController:(id)controller didSelectPaymentMethod:(id)method handler:(id /* block */)handler;
- (void)paymentAuthorizationController:(id)controller willFinishWithError:(id)error;
- (void)paymentAuthorizationControllerDidFinish:(id)finish;
- (id)presentationSceneBundleIdentifierForPaymentAuthorizationController:(id)controller;
- (id)presentationSceneIdentifierForPaymentAuthorizationController:(id)controller;
- (id)presentationWindowForPaymentAuthorizationController:(id)controller;

@end

#endif /* _AMSPaymentSheetTask_h */
