//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSPurchaseQueueBatchList_h
#define _AMSPurchaseQueueBatchList_h

@import Foundation;

#include "AMSThreadSafeObject.h"

@interface AMSPurchaseQueueBatchList : NSObject

@property (retain) AMSThreadSafeObject *backingArray;

/* instance methods */
- (id)init;
- (unsigned long long)count;
- (void)appendBatch:(id)batch;
- (id)batchForPurchase:(id)purchase;
- (id)nextPurchase;
- (void)popBatch:(id)batch;

@end

#endif /* _AMSPurchaseQueueBatchList_h */
