//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSPromiseCompletionBlocks_h
#define _AMSPromiseCompletionBlocks_h

@import Foundation;

#include "os_unfair_lock_s.h"

@interface AMSPromiseCompletionBlocks : NSObject {
    /* instance variables */
    struct os_unfair_lock_s _completionBlockLock;
    NSMutableArray *_completionBlocks;
    signed char _shouldCallImmediately;
}

/* instance methods */
- (id)init;
- (void)addCompletionBlock:(id /* block */)block;
- (void)addSuccessBlock:(id /* block */)block;
- (void)addErrorBlock:(id /* block */)block;
- (void)callCompletionBlock:(id /* block */)block withPromiseResult:(id)result;
- (void)callErrorBlock:(id /* block */)block withPromiseResult:(id)result;
- (void)callSuccessBlock:(id /* block */)block withPromiseResult:(id)result;
- (void)flushCompletionBlocksWithPromiseResult:(id)result;

@end

#endif /* _AMSPromiseCompletionBlocks_h */
