//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSPurchaseQueue_h
#define _AMSPurchaseQueue_h

@import Foundation;

#include "AMSBagConsumer-Protocol.h"
#include "AMSPurchaseDelegate-Protocol.h"
#include "AMSPurchaseQueueBatchList.h"
#include "AMSPurchaseQueueConfiguration.h"
#include "AMSThreadSafeSet.h"

@protocol OS_dispatch_queue;

@interface AMSPurchaseQueue : NSObject <AMSPurchaseDelegate, AMSBagConsumer>

@property (retain) AMSPurchaseQueueBatchList *batches;
@property (retain) AMSPurchaseQueueConfiguration *config;
@property (retain) NSObject<OS_dispatch_queue> *dispatchQueue;
@property (retain) AMSThreadSafeSet *preAuthenticatedDSIDs;
@property signed char suspended;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)bagSubProfile;
+ (id)bagSubProfileVersion;
+ (id)bagKeySet;
+ (id)createBagForSubProfile;

/* instance methods */
- (signed char)isSuspended;
- (id)initWithConfiguration:(id)configuration;
- (id)enquePurchases:(id)purchases;
- (id)_createPurchasePromiseForTask:(id)task purchase:(id)purchase;
- (void)_handleNextPurchase;
- (void)_handleResult:(id)result error:(id)error forPurchase:(id)purchase;
- (id)_performPreauthenticateForPurchaseTask:(id)task;
- (id)_processPurchase:(id)purchase;
- (void)purchase:(id)purchase handleAuthenticateRequest:(id)request completion:(id /* block */)completion;
- (void)purchase:(id)purchase handleDialogRequest:(id)request completion:(id /* block */)completion;
- (void)purchase:(id)purchase handleEngagementRequest:(id)request completion:(id /* block */)completion;
- (void)setSuspended:(signed char)suspended logUUID:(id)uuid;

@end

#endif /* _AMSPurchaseQueue_h */
