//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSQRCodeDialogTask_h
#define _AMSQRCodeDialogTask_h

@import Foundation;

#include "AMSSystemAlertDialogTask.h"

@interface AMSQRCodeDialogTask : AMSSystemAlertDialogTask

/* instance methods */
- (struct __CFDictionary *)_createNoteDictionaryWithKeys:(struct ButtonKey { struct __CFString *x0; int x1; } *)keys buttonActions:(id)actions outOptions:(unsigned long long *)options;

@end

#endif /* _AMSQRCodeDialogTask_h */
