//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSRatingsStoreFront_h
#define _AMSRatingsStoreFront_h

@import Foundation;

@interface AMSRatingsStoreFront : NSObject

@property (readonly) NSString *defaultLanguage;
@property (readonly) unsigned long long mediaType;
@property (readonly) NSString *name;
@property (readonly) NSArray *ratingSystems;
@property (readonly) NSString *storeFront;
@property (readonly) NSString *storeFrontID;
@property (readonly) NSArray *supportedLanguages;

/* class methods */
+ (id)storeFrontWithDictionary:(id)dictionary mediaType:(unsigned long long)type;
+ (id)storeFrontWithDictionary:(id)dictionary mediaType:(unsigned long long)type andStoreFront:(id)front;

/* instance methods */
- (id)description;
- (id)initWithDictionary:(id)dictionary mediaType:(unsigned long long)type;
- (id)initWithDictionary:(id)dictionary mediaType:(unsigned long long)type andStoreFront:(id)front;

@end

#endif /* _AMSRatingsStoreFront_h */
