//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSRBSKeepAlive_h
#define _AMSRBSKeepAlive_h

@import Foundation;

@interface AMSRBSKeepAlive : NSObject { // (Swift)
    /* instance variables */
    //  keepAlive;
}

@property (nonatomic, readonly) NSString *name;
@property (nonatomic, readonly) long long style;

/* class methods */
+ (id)keepAliveWithName:(id)name;
+ (id)keepAliveWithName:(id)name style:(long long)style;
+ (void)keepAliveWithName:(id)name style:(long long)style block:(id /* block */)block;

/* instance methods */
- (id)init;
- (void)invalidate;

@end

#endif /* _AMSRBSKeepAlive_h */
