//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSRatingsProviderTask_h
#define _AMSRatingsProviderTask_h

@import Foundation;

#include "AMSBagConsumer-Protocol.h"
#include "AMSBagProtocol-Protocol.h"
#include "AMSTask.h"

@interface AMSRatingsProviderTask : AMSTask <AMSBagConsumer>

@property (readonly) unsigned long long mediaType;
@property (readonly) NSString *storeFront;
@property (readonly) id <AMSBagProtocol> bag;
@property (readonly) NSString *clientIdentifier;
@property (readonly) unsigned long long useCase;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)bagSubProfile;
+ (id)bagSubProfileVersion;
+ (id)bagKeySet;
+ (id)createBagForSubProfile;
+ (id)ratingWithValue:(id)value mediaType:(unsigned long long)type storeFront:(id)front clientIdentifier:(id)identifier bag:(id)bag;

/* instance methods */
- (id)performTask;
- (id)_appQueryItems;
- (id)_commonQueryItems;
- (id)_unratedRatingQueryItem;
- (id)_urlForMediaType:(unsigned long long)type error:(id *)error;
- (id)initForAllMediaWithClientIdentifier:(id)identifier useCase:(unsigned long long)_case bag:(id)bag;
- (id)initForAllMediaWithStoreFront:(id)front clientIdentifier:(id)identifier useCase:(unsigned long long)_case bag:(id)bag;
- (id)initForAllMediaWithUnratedRatingsForStoreFront:(id)front clientIdentifier:(id)identifier useCase:(unsigned long long)_case bag:(id)bag;
- (id)initWithMediaType:(unsigned long long)type clientIdentifier:(id)identifier bag:(id)bag;
- (id)initWithMediaType:(unsigned long long)type storeFront:(id)front clientIdentifier:(id)identifier bag:(id)bag;
- (id)resultWithCachedData:(id)data;

@end

#endif /* _AMSRatingsProviderTask_h */
