//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSRatingSystem_h
#define _AMSRatingSystem_h

@import Foundation;

@interface AMSRatingSystem : NSObject

@property (readonly) NSString *kind;
@property (readonly) NSString *label;
@property (readonly) NSArray *contentRatings;
@property (readonly) NSString *ratingSystemID;
@property (readonly) NSArray *types;

/* class methods */
+ (id)ratingSystemWithDictionary:(id)dictionary;

/* instance methods */
- (id)description;
- (id)initWithDictionary:(id)dictionary;

@end

#endif /* _AMSRatingSystem_h */
