//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSResource_h
#define _AMSResource_h

@import Foundation;

@interface AMSResource : NSObject

/* class methods */
+ (id)loadHARFileWithName:(id)name bundle:(id)bundle;
+ (id)loadPropertyListWithName:(id)name bundle:(id)bundle error:(id *)error;

@end

#endif /* _AMSResource_h */
