//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSSQLiteBinding_Protocol_h
#define _AMSSQLiteBinding_Protocol_h

@import Foundation;

@protocol AMSSQLiteBinding <NSObject>

@required

/* required instance methods */
- (void)bindArray:(id)array atPosition:(int)position;
- (void)bindData:(id)data atPosition:(int)position;
- (void)bindDataCopy:(id)copy atPosition:(int)position;
- (void)bindDate:(id)date atPosition:(int)position;
- (void)bindDictionary:(id)dictionary atPosition:(int)position;
- (void)bindDouble:(double)_double atPosition:(int)position;
- (void)bindFloat:(float)_float atPosition:(int)position;
- (void)bindInt64:(long long)int64 atPosition:(int)position;
- (void)bindInt:(int)_int atPosition:(int)position;
- (void)bindNullAtPosition:(int)position;
- (void)bindNullableString:(id)string atPosition:(int)position;
- (void)bindNumber:(id)number atPosition:(int)position;
- (void)bindString:(id)string atPosition:(int)position;
- (void)bindStringCopy:(id)copy atPosition:(int)position;
- (void)bindURL:(id)url atPosition:(int)position;
- (int)clearBindings;

@optional

@end

#endif /* _AMSSQLiteBinding_Protocol_h */
