//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSSyncRestrictedRegionTask_h
#define _AMSSyncRestrictedRegionTask_h

@import Foundation;

#include "ACAccount.h"
#include "AMSBagConsumer-Protocol.h"
#include "AMSBagProtocol-Protocol.h"
#include "AMSTask.h"

@interface AMSSyncRestrictedRegionTask : AMSTask <AMSBagConsumer>

@property (retain) ACAccount *account;
@property (retain) id <AMSBagProtocol> bag;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)bagSubProfile;
+ (id)bagSubProfileVersion;
+ (double)checkRestrictedRegionDurationValueFromBag:(id)bag;
+ (id)createBagForSubProfile;
+ (id)createSyncAccountFlagsTaskForAccount:(id)account bag:(id)bag;
+ (signed char)didExceededSyncDuration:(double)duration lastTimestamp:(double)timestamp currentTimestamp:(double)timestamp;
+ (double)durationOfSyncRestrictedRegionValueFromBag:(id)bag;
+ (signed char)hasCachedRestrictedRegionsValueFromAccount:(id)account cachedTimestamp:(double *)timestamp;
+ (signed char)storefrontContainsRestrictedRegionsValueFromBag:(id)bag;

/* instance methods */
- (id)initWithAccount:(id)account;
- (void)cacheRestrictedRegionSyncTimestamp:(double)timestamp;
- (id)initWithAccount:(id)account bag:(id)bag;
- (id)performSync;

@end

#endif /* _AMSSyncRestrictedRegionTask_h */
