//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSSigningSecurityService_h
#define _AMSSigningSecurityService_h

@import Foundation;

#include "AMSDServiceBrokerProtocol-Protocol.h"

@interface AMSSigningSecurityService : NSObject

@property (readonly) id <AMSDServiceBrokerProtocol> serviceBroker;

/* class methods */
+ (id)sharedService;

/* instance methods */
- (id)init;
- (id)_defaultSecurityServiceWithDelegate:(id)delegate;
- (id)_handleResponse:(id)response bag:(id)bag securityServicePromise:(id)promise onDenied:(id /* block */)denied;
- (void)_handleSecurityServicePromise:(id)promise onConnected:(id /* block */)connected onDenied:(id /* block */)denied onError:(id /* block */)error;
- (id)_headersForRequest:(id)request buyParams:(id)params bag:(id)bag securityServicePromise:(id)promise onDenied:(id /* block */)denied;
- (id)handleResponse:(id)response bag:(id)bag;
- (id)headersForRequest:(id)request buyParams:(id)params bag:(id)bag;
- (id)initWithServiceBroker:(id)broker;
- (id)signatureForRequest:(id)request;

@end

#endif /* _AMSSigningSecurityService_h */
