//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSSQLiteMemoryEntity_h
#define _AMSSQLiteMemoryEntity_h

@import Foundation;

@interface AMSSQLiteMemoryEntity : NSObject <NSCopying>

@property (nonatomic) long long databaseID;
@property (readonly, copy, nonatomic) NSDictionary *propertyValues;
@property (readonly, copy, nonatomic) NSDictionary *externalPropertyValues;

/* class methods */
+ (id)defaultProperties;
+ (id)anyOnConnection:(id)connection predicate:(id)predicate;
+ (Class)databaseEntityClass;
+ (id)queryOnConnection:(id)connection predicate:(id)predicate;
+ (id)queryOnConnection:(id)connection predicate:(id)predicate orderingProperties:(id)properties;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (id)description;
- (unsigned long long)hash;
- (id)init;
- (signed char)isEqual:(id)equal;
- (id)valueForProperty:(id)property;
- (void)setValue:(id)value forProperty:(id)property;
- (id)initWithDatabaseEntity:(id)entity properties:(id)properties;
- (void)reloadFromDatabaseEntity:(id)entity properties:(id)properties;
- (void)setExternalValuesWithDictionary:(id)dictionary;
- (void)setValue:(id)value forExternalProperty:(id)property;
- (void)setValues:(id *)values forExternalProperties:(const id *)properties count:(long long)count;
- (void)setValues:(id *)values forProperties:(const id *)properties count:(long long)count;
- (void)setValuesWithDictionary:(id)dictionary;
- (id)valueForExternalProperty:(id)property;

@end

#endif /* _AMSSQLiteMemoryEntity_h */
