//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSSQLiteComparisonPredicate_h
#define _AMSSQLiteComparisonPredicate_h

@import Foundation;

#include "AMSSQLitePropertyPredicate.h"

@interface AMSSQLiteComparisonPredicate : AMSSQLitePropertyPredicate <NSCopying>

@property (readonly, nonatomic) long long comparisonType;
@property (readonly, nonatomic) id value;

/* class methods */
+ (id)predicateWithProperty:(id)property equalToLongLong:(long long)_long;
+ (id)predicateWithProperty:(id)property equalToValue:(id)value;
+ (id)predicateWithProperty:(id)property value:(id)value comparisonType:(long long)type;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (unsigned long long)hash;
- (signed char)isEqual:(id)equal;
- (id)SQLForEntityClass:(Class)_class;
- (id)_comparisonTypeString;
- (void)applyBinding:(id)binding atIndex:(inout int *)index;

@end

#endif /* _AMSSQLiteComparisonPredicate_h */
