//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSSQLiteQuery_h
#define _AMSSQLiteQuery_h

@import Foundation;

#include "AMSSQLiteConnection.h"
#include "AMSSQLiteQueryDescriptor.h"

@interface AMSSQLiteQuery : NSObject {
    /* instance variables */
    AMSSQLiteQueryDescriptor *_descriptor;
}

@property (readonly) AMSSQLiteConnection *connection;
@property (readonly) AMSSQLiteQueryDescriptor *queryDescriptor;
@property (readonly) long long countOfEntities;

/* instance methods */
- (id)_newSelectSQLWithProperties:(id)properties;
- (void)applyBinding:(id)binding atIndex:(inout int *)index;
- (id)copyEntityIdentifiers;
- (id)copySelectSQLWithProperties:(id)properties;
- (signed char)createTemporaryTableWithName:(id)name properties:(id)properties;
- (signed char)deleteAllEntities;
- (void)enumerateMemoryEntitiesUsingBlock:(id /* block */)block;
- (void)enumerateMemoryEntitiesWithProperties:(id)properties usingBlock:(id /* block */)block;
- (void)enumeratePersistentIDsAndProperties:(id)properties usingBlock:(id /* block */)block;
- (void)enumeratePersistentIDsUsingBlock:(id /* block */)block;
- (id)initOnConnection:(id)connection descriptor:(id)descriptor;

@end

#endif /* _AMSSQLiteQuery_h */
