//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSStreamHTTPArchiveEntryController_h
#define _AMSStreamHTTPArchiveEntryController_h

@import Foundation;

@interface AMSStreamHTTPArchiveEntryController : NSObject

/* class methods */
+ (void)initialize;
+ (id)buffer;
+ (id)_createNewFileWithError:(id *)error outputDirectory:(id)directory forCombining:(signed char)combining;
+ (id)_footerData;
+ (id)_harFileURLsInPath:(id)path;
+ (id)_headerData;
+ (void)_performCombiningFiles:(id)files toStream:(id)stream;
+ (void)_periodicCleanup;
+ (signed char)_shouldWriteEntryDirectlyToDiskForURLString:(id)urlstring;
+ (void)_streamToDiskWithEntries:(id)entries;
+ (void)_updateMaxBufferSize;
+ (signed char)_writeData:(id)data enumeratingBytesToStream:(id)stream;
+ (void)_writeEntries:(id)entries toStream:(id)stream;
+ (signed char)_writeFooterToStream:(id)stream;
+ (signed char)_writeHeaderToStream:(id)stream;
+ (void)ams_addEntriesForTaskInfo:(id)info;
+ (id)ams_combineEntriesForPath:(id)path error:(id *)error;
+ (void)ams_streamEntriesToDisk;

@end

#endif /* _AMSStreamHTTPArchiveEntryController_h */
