//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSSQLiteStatement_h
#define _AMSSQLiteStatement_h

@import Foundation;

#include "AMSSQLiteBinding-Protocol.h"
#include "AMSSQLiteConnection.h"

@interface AMSSQLiteStatement : NSObject <AMSSQLiteBinding> {
    /* instance variables */
    struct sqlite3_stmt * _statement;
    AMSSQLiteStatement *_strongSelf;
}

@property (readonly, nonatomic) AMSSQLiteConnection *connection;
@property (readonly, nonatomic) struct sqlite3_stmt * sqlite3_stmt;
@property (readonly, copy, nonatomic) NSDictionary *columnIndexByName;
@property (readonly, nonatomic) signed char readOnly;
@property (readonly, copy, nonatomic) NSString *SQL;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* instance methods */
- (int)reset;
- (int)finalizeStatement;
- (int)step;
- (signed char)isReadOnly;
- (id)initWithStatement:(struct sqlite3_stmt *)statement onConnection:(id)connection;
- (void)bindArray:(id)array atPosition:(int)position;
- (void)bindData:(id)data atPosition:(int)position;
- (void)bindDataCopy:(id)copy atPosition:(int)position;
- (void)bindDate:(id)date atPosition:(int)position;
- (void)bindDictionary:(id)dictionary atPosition:(int)position;
- (void)bindDouble:(double)_double atPosition:(int)position;
- (void)bindFloat:(float)_float atPosition:(int)position;
- (void)bindInt64:(long long)int64 atPosition:(int)position;
- (void)bindInt:(int)_int atPosition:(int)position;
- (void)bindNullAtPosition:(int)position;
- (void)bindNullableString:(id)string atPosition:(int)position;
- (void)bindNumber:(id)number atPosition:(int)position;
- (void)bindString:(id)string atPosition:(int)position;
- (void)bindStringCopy:(id)copy atPosition:(int)position;
- (void)bindURL:(id)url atPosition:(int)position;
- (int)clearBindings;

@end

#endif /* _AMSSQLiteStatement_h */
