//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSSQLiteCursor_h
#define _AMSSQLiteCursor_h

@import Foundation;

#include "AMSSQLiteStatement.h"

@interface AMSSQLiteCursor : NSObject {
    /* instance variables */
    NSDictionary *_columnIndexByName;
    struct sqlite3_stmt * _statement;
    AMSSQLiteStatement *_statementWrapper;
}

@property (readonly, nonatomic) long long numberOfColumns;

/* instance methods */
- (id)initWithStatement:(id)statement;
- (id)URLForColumnIndex:(int)index;
- (id)URLForColumnName:(id)name;
- (int)_columnTypeForColumnIndex:(int)index;
- (int)columnIndexForColumnName:(id)name;
- (id)dataForColumnIndex:(int)index;
- (id)dataForColumnName:(id)name;
- (id)dateForColumnIndex:(int)index;
- (id)dateForColumnName:(id)name;
- (double)doubleForColumnIndex:(int)index;
- (double)doubleForColumnName:(id)name;
- (long long)int64ForColumnIndex:(int)index;
- (long long)int64ForColumnName:(id)name;
- (int)intForColumnIndex:(int)index;
- (int)intForColumnName:(id)name;
- (id)numberForColumnIndex:(int)index;
- (id)numberForColumnName:(id)name;
- (id)stringForColumnIndex:(int)index;
- (id)stringForColumnName:(id)name;

@end

#endif /* _AMSSQLiteCursor_h */
