//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSSQLiteNullPredicate_h
#define _AMSSQLiteNullPredicate_h

@import Foundation;

#include "AMSSQLitePropertyPredicate.h"

@interface AMSSQLiteNullPredicate : AMSSQLitePropertyPredicate <NSCopying>

@property (readonly, nonatomic) signed char matchesNull;

/* class methods */
+ (id)isNotNullPredicateWithProperty:(id)property;
+ (id)isNullPredicateWithProperty:(id)property;

/* instance methods */
- (id)copyWithZone:(struct _NSZone *)zone;
- (signed char)isEqual:(id)equal;
- (id)SQLForEntityClass:(Class)_class;

@end

#endif /* _AMSSQLiteNullPredicate_h */
