//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSSQLiteConnection_h
#define _AMSSQLiteConnection_h

@import Foundation;

#include "AMSSQLiteConnectionDelegate-Protocol.h"
#include "AMSSQLiteConnectionOptions.h"

@interface AMSSQLiteConnection : NSObject {
    /* instance variables */
    NSMutableArray *_afterTransactionBlocks;
    struct sqlite3 * _database;
    signed char _didResetForCorruption;
    NSMapTable *_preparedStatements;
    long long _transactionDepth;
    signed char _transactionWantsRollback;
}

@property (readonly, copy, nonatomic) NSError *currentError;
@property (readonly, copy, nonatomic) AMSSQLiteConnectionOptions *options;
@property (weak, nonatomic) id <AMSSQLiteConnectionDelegate> delegate;
@property (readonly, nonatomic) long long lastChangeCount;

/* instance methods */
- (void)dealloc;
- (signed char)close;
- (id)initWithOptions:(id)options;
- (signed char)openWithError:(id *)error;
- (signed char)_close;
- (void)performTransaction:(id /* block */)transaction;
- (signed char)executeStatement:(id)statement error:(id *)error;
- (id)_verifiedStatementForSQL:(id)sql error:(id *)error;
- (signed char)_openWithError:(id *)error;
- (signed char)executePreparedStatement:(id)statement error:(id *)error;
- (signed char)_executeStatement:(id)statement error:(id *)error;
- (signed char)_executeWithError:(id *)error usingBlock:(id /* block */)block;
- (void)_finalizeAllStatements;
- (void)_flushAfterTransactionBlocks;
- (signed char)_openAndAllowRetry:(signed char)retry error:(id *)error;
- (signed char)_performResetAfterCorruptionError;
- (id)_prepareStatement:(id)statement error:(id *)error;
- (signed char)_resetAfterCorruptionError;
- (signed char)_resetAfterIOError;
- (id)_statementForPreparedStatement:(id)statement error:(id *)error;
- (id)_verifiedStatementForPreparedStatement:(id)statement error:(id *)error;
- (void)dispatchAfterTransaction:(id /* block */)transaction;
- (void)executePreparedQuery:(id)query withResults:(id /* block */)results;
- (signed char)executePreparedStatement:(id)statement error:(id *)error bindings:(id /* block */)bindings;
- (void)executeQuery:(id)query withResults:(id /* block */)results;
- (signed char)executeStatement:(id)statement error:(id *)error bindings:(id /* block */)bindings;
- (signed char)executeWithError:(id *)error usingBlock:(id /* block */)block;
- (signed char)finalizePreparedStatement:(id)statement error:(id *)error;
- (id)prepareStatement:(id)statement error:(id *)error;
- (signed char)truncate;

@end

#endif /* _AMSSQLiteConnection_h */
