//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSTreatmentStore_h
#define _AMSTreatmentStore_h

@import Foundation;

#include "AMSEngagement.h"

@interface AMSTreatmentStore : NSObject

@property (readonly) long long cachePolicy;
@property (retain) AMSEngagement *engagement;

/* class methods */
+ (signed char)attemptConnectionInTests;
+ (id)defaultTreatmentStore;
+ (void)setAttemptConnectionInTests:(signed char)tests;

/* instance methods */
- (id)init;
- (id)areasForTopics:(id)topics;
- (id)_encodeExperimentData:(id)data;
- (id)_treatmentStoreService;
- (id)areasForNamespaces:(id)namespaces;
- (id)encodeExperimentDataForTopic:(id)topic;
- (id)experimentDataForAreas:(id)areas;
- (id)initWithCachePolicy:(long long)policy;
- (id)synchronizeTreatments;
- (id)treatmentsForAreas:(id)areas;
- (id)treatmentsPayloadForAreas:(id)areas;

@end

#endif /* _AMSTreatmentStore_h */
