//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSTask_h
#define _AMSTask_h

@import Foundation;

#include "AMSPromise.h"
#include "os_unfair_lock_s.h"

@protocol OS_dispatch_queue;

@interface AMSTask : NSObject

@property (retain) NSObject<OS_dispatch_queue> *performTaskQueue;
@property (retain) AMSPromise *promise;
@property struct os_unfair_lock_s promiseAccessLock;
@property (readonly) signed char cancelled;
@property (readonly) signed char finished;
@property (readonly) signed char running;
@property long long runMode;

/* class methods */
+ (id)taskCache;

/* instance methods */
- (id)init;
- (signed char)cancel;
- (signed char)isCancelled;
- (signed char)isFinished;
- (signed char)isRunning;
- (id)performBinaryTaskWithBlock:(id /* block */)block;
- (id)performTaskWithBlock:(id /* block */)block;
- (id)performTaskWithPromiseBlock:(id /* block */)block;

@end

#endif /* _AMSTask_h */
