//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSUserNotificationSettingsResult_h
#define _AMSUserNotificationSettingsResult_h

@import Foundation;

@interface AMSUserNotificationSettingsResult : NSObject

@property (readonly) NSString *serviceIdentifier;
@property (readonly) NSDictionary *itemsMap;

/* class methods */
+ (id)_itemsMapForServiceIdentifier:(id)identifier dictionaryRepresentation:(id)representation;

/* instance methods */
- (id)initWithServiceIdentifier:(id)identifier dictionaryRepresentation:(id)representation;

@end

#endif /* _AMSUserNotificationSettingsResult_h */
