//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSUserNotification_h
#define _AMSUserNotification_h

@import Foundation;

#include "ACAccount.h"
#include "AMSBagConsumer-Protocol.h"
#include "AMSUserNotificationAction.h"

@interface AMSUserNotification : NSObject <AMSBagConsumer>

@property signed char anonymizeMetrics;
@property long long intent;
@property (retain) NSString *categoryIdentifier;
@property signed char shouldSuppressDefaultAction;
@property (retain) NSString *threadIdentifier;
@property (retain) ACAccount *account;
@property (retain) NSURL *artworkUrl;
@property (retain) NSURL *videoUrl;
@property (retain) NSArray *buttonActions;
@property (retain) NSString *centerBundleIdentifier;
@property (retain) AMSUserNotificationAction *defaultAction;
@property signed char explicitContent;
@property (retain) NSString *identifier;
@property (retain) NSString *informativeText;
@property (retain) NSString *logKey;
@property (retain) NSDictionary *metricsEvent;
@property (retain) NSDate *scheduledTime;
@property (retain) NSSet *subsections;
@property (retain) NSString *subtitle;
@property (retain) NSString *title;
@property (retain) NSMutableDictionary *userInfo;
@property unsigned long long interruptionLevel;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

/* class methods */
+ (id)bagSubProfile;
+ (id)bagSubProfileVersion;
+ (id)handleNotificationResponse:(id)response bag:(id)bag;
+ (signed char)shouldDeleteNotificationForPayload:(id)payload outIdentifier:(id *)identifier scheduledOnly:(char *)only;
+ (id)_cachedImagePathForIdentifier:(id)identifier assetURL:(id)url;
+ (signed char)_canParseNotificationWithIdentifier:(id)identifier userInfo:(id)info;
+ (id)_dateFromString:(id)string;
+ (id)_downloadAssetAtUrl:(id)url withIdentifier:(id)identifier logKey:(id)key bag:(id)bag;
+ (id)_identifierFromPayload:(id)payload;
+ (id)bagKeySet;
+ (id)createBagForSubProfile;
+ (id)handleNotificationResponse:(id)response bagContract:(id)contract;
+ (void)handleServiceExtensionNotificationRequest:(id)request bag:(id)bag withContentHandler:(id /* block */)handler;
+ (id)notificationCenter:(id)center didChangeSettings:(id)settings bag:(id)bag;
+ (id)notificationCenter:(id)center openSettingsForNotification:(id)notification bag:(id)bag;
+ (id)notificationWithPayload:(id)payload andConfig:(id)config;
+ (void)openAppUsingBundleIdentifier:(id)identifier;
+ (signed char)shouldHandleNotificationResponse:(id)response;
+ (signed char)shouldHandleServiceExtensionNotificationRequest:(id)request;

/* instance methods */
- (id)init;
- (id)initWithTitle:(id)title;
- (id)_generatePayloadWithBase:(id)base;
- (void)addButtonAction:(id)action;
- (id)createNSUserNotification;
- (id)createUNNotificationActions;
- (id)createUNNotificationContent;
- (id)createUNNotificationRequestFromContent:(id)content;
- (id)determineSelectedActionFromResponse:(id)response error:(id *)error;
- (id)handleSelectedButton:(id)button bag:(id)bag;
- (id)handleSelectedButton:(id)button bagContract:(id)contract;
- (id)initWithNSUserNotification:(id)notification;
- (id)initWithPayload:(id)payload andConfig:(id)config;
- (id)initWithTitle:(id)title intent:(long long)intent;
- (id)initWithUNNotification:(id)unnotification;

@end

#endif /* _AMSUserNotification_h */
