//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSUniqueExecutionQueue_h
#define _AMSUniqueExecutionQueue_h

@import Foundation;

#include "AMSPromise.h"

@protocol OS_dispatch_queue;

@interface AMSUniqueExecutionQueue : NSObject

@property (copy) id /* block */ block;
@property (retain) NSObject<OS_dispatch_queue> *completionCallbacksQueue;
@property (retain) NSObject<OS_dispatch_queue> *executeBlockQueue;
@property (retain) AMSPromise *executionPromise;
@property (readonly) NSObject<OS_dispatch_queue> *executionPromiseAccessQueue;

/* instance methods */
- (id)initWithBlock:(id /* block */)block;
- (void)addCompletionBlock:(id /* block */)block;
- (void)_beginExecutingBlockWithPromise:(id)promise;
- (id)_createExecutionPromise;
- (void)addCompletionBlockForSubsequentExecution:(id /* block */)execution;

@end

#endif /* _AMSUniqueExecutionQueue_h */
