//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSUserNotificationCenter_h
#define _AMSUserNotificationCenter_h

@import Foundation;

#include "AMSUserNotificationStrategy-Protocol.h"

@interface AMSUserNotificationCenter : NSObject

@property (readonly) id <AMSUserNotificationStrategy> strategy;

/* class methods */
+ (Class)_determineStrategyForBundleId:(id)id;
+ (id)activeNotificationsWithCenterBundleId:(id)id;
+ (signed char)badgeBundleId:(id)id badgeId:(id)id enabled:(signed char)enabled error:(id *)error;
+ (id)postNotification:(id)notification bag:(id)bag centerBundleId:(id)id;
+ (id)removeNotification:(id)notification centerBundleId:(id)id;
+ (id)removeNotificationWithIdentifier:(id)identifier centerBundleId:(id)id logKey:(id)key scheduledOnly:(signed char)only;

/* instance methods */

@end

#endif /* _AMSUserNotificationCenter_h */
