//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSURLTaskInfo_h
#define _AMSURLTaskInfo_h

@import Foundation;

#include "AMSContiguousActionPerformer.h"
#include "AMSURLAction.h"
#include "AMSURLRequestProperties.h"
#include "AMSURLSession.h"
#include "os_unfair_recursive_lock_s.h"

@protocol OS_dispatch_queue;

@interface AMSURLTaskInfo : NSObject {
    /* instance variables */
    signed char _performingBlockWithDataAccess;
}

@property (readonly) struct os_unfair_recursive_lock_s taskLock;
@property (readonly) NSObject<OS_dispatch_queue> *taskQueue;
@property (readonly) AMSContiguousActionPerformer *contiguousActionPerformer;
@property (copy) id /* block */ completionBlock;
@property (readonly) NSData *data;
@property (retain) NSError *error;
@property (retain) NSURLSessionTaskMetrics *metrics;
@property unsigned long long previousAuthorizationCredentialSource;
@property (retain) AMSURLRequestProperties *properties;
@property (retain) AMSURLAction *receivedAction;
@property (retain) NSURLResponse *response;
@property (retain) NSURLResponse *originalResponse;
@property long long retryCount;
@property (readonly) NSSet *retryIdentifiers;
@property (retain) AMSURLSession *session;
@property unsigned long long signpostID;
@property (readonly) NSURLSessionTask *task;

/* class methods */
+ (id)sharedTaskQueue;
+ (id)sharedTaskStore;
+ (id)createTaskInfoForTask:(id)task;
+ (void)removeTaskInfoForTask:(id)task;
+ (id)taskInfoForTask:(id)task;

/* instance methods */
- (void)appendData:(id)data;
- (void)setAccount:(id)account;
- (void)performAsyncBlock:(id /* block */)block;
- (void)performSyncBlock:(id /* block */)block;
- (id)initWithTask:(id)task;
- (void)_performDataAccessUsingBlock:(id /* block */)block;
- (void)addRetryIdentifier:(id)identifier;
- (void)assertHasExclusiveAccess;
- (void)assertIsOnPrivateQueue;
- (void)continueContiguousAsyncActionWithIdentifier:(unsigned long long)identifier block:(id /* block */)block;
- (id)createMetricsContextForDecodedObject:(id)object;
- (void)finishContiguousAsyncActionWithIdentifier:(unsigned long long)identifier;
- (void)migrateFromTaskInfo:(id)info;
- (void)performAsyncBlockWithData:(id /* block */)data;
- (void)performSyncBlockWithExclusiveAccess:(id /* block */)access;
- (unsigned long long)startContiguousAsyncActionWithInitialBlock:(id /* block */)block;
- (unsigned long long)startContiguousAsyncActionWithInitialDataBlock:(id /* block */)block;

@end

#endif /* _AMSURLTaskInfo_h */
