//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSUserNotificationMetricsEvent_h
#define _AMSUserNotificationMetricsEvent_h

@import Foundation;

#include "AMSMetricsEvent.h"

@interface AMSUserNotificationMetricsEvent : AMSMetricsEvent

@property (retain) NSString *displayScheduledTime;
@property (retain) NSString *errorDescription;
@property signed char postedSuccessfully;

/* class methods */
+ (id)_centerForBundleId:(id)id;
+ (id)_propertyValueClassesForKnownProperties;
+ (id)_stringFromInteruptionLevel:(unsigned long long)level;
+ (id)eventForBadgingForMetricsDictionary:(id)dictionary bundleID:(id)id;
+ (id)eventForContentEngagementWithNotification:(id)notification;
+ (id)eventForPostedNotification:(id)notification;
+ (id)eventForSettingsChangedWithSettings:(id)settings bundleID:(id)id;
+ (id)eventForSettingsChangedWithSettings:(id)settings bundleID:(id)id account:(id)account;
+ (id)eventForVideoPlaybackForNotification:(id)notification;
+ (id)eventFromMetricsDictionary:(id)dictionary centerBundleId:(id)id;
+ (id)eventFromNotificationCenterSettings:(id)settings centerBundleId:(id)id;

/* instance methods */
- (id)_stringFromNotificationSetting:(long long)setting;
- (id)_createDisplayCriteriaFromSettings:(id)settings;
- (id)initWithTopic:(id)topic settings:(id)settings notificationSettingsForTopic:(id)topic centerBundleId:(id)id;

@end

#endif /* _AMSUserNotificationMetricsEvent_h */
