//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSUserNotificationSettingsItem_h
#define _AMSUserNotificationSettingsItem_h

@import Foundation;

@interface AMSUserNotificationSettingsItem : NSObject

@property (readonly) NSDictionary *dictionaryRepresentation;
@property (readonly) NSDictionary *updateDictionary;
@property signed char enabled;
@property (readonly) NSString *identifier;
@property signed char userChanged;

/* instance methods */
- (id)description;
- (signed char)isEnabled;
- (id)initWithIdentifier:(id)identifier dictionaryRepresentation:(id)representation;
- (id)initWithIdentifier:(id)identifier enabled:(signed char)enabled;

@end

#endif /* _AMSUserNotificationSettingsItem_h */
