//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSURLSentry_h
#define _AMSURLSentry_h

@import Foundation;

@interface AMSURLSentry : NSObject { // (Swift)
    /* instance variables */
    //  bag;
}

/* instance methods */
- (id)init;
- (void)isTrustedURL:(NSURL *)url completionHandler:(id /* block */)handler;
- (id)initWithBag:(id)bag;

@end

#endif /* _AMSURLSentry_h */
