//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _AMSXDDevice_h
#define _AMSXDDevice_h

@import Foundation;

@interface AMSXDDevice : NSObject <NSSecureCoding>

@property (readonly) NSDictionary *JSONDictionary;
@property (readonly) NSString *identifier;
@property long long type;

/* class methods */
+ (signed char)supportsSecureCoding;
+ (id)activePairedDevices;
+ (id)allPairedDevices;
+ (id)deviceFromIdentifier:(id)identifier;

/* instance methods */
- (void)encodeWithCoder:(id)coder;
- (id)initWithCoder:(id)coder;
- (id)initWithJSONDictionary:(id)jsondictionary;
- (id)initWithDeviceID:(id)id type:(long long)type;

@end

#endif /* _AMSXDDevice_h */
