//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _NSBundle_AppleMediaServices_h
#define _NSBundle_AppleMediaServices_h

@import Foundation;

@interface NSBundle (AppleMediaServices)

/* class methods */
+ (id)ams_MusicBundle;
+ (id)ams_AppleMediaServicesBundle;

@end

#endif /* _NSBundle_AppleMediaServices_h */
