//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _NSDictionary_AppleMediaServices_EncryptionResult_h
#define _NSDictionary_AppleMediaServices_EncryptionResult_h

@import Foundation;

@interface NSDictionary (AppleMediaServices_EncryptionResult) <AMSHashable, AMSSecureCodingSanitizable>

/* class methods */
+ (id)ams_dictionaryWithEncryptionResult:(struct { id x0; id x1; id x2; })result;

/* instance methods */
- (id)ams_DSID;
- (id)ams_secureToken;
- (id)ams_accountFlags;
- (id)ams_altDSID;
- (id)ams_arrayUsingTransform:(id /* block */)transform;
- (id)ams_componentsJoinedByString:(id)string;
- (id)ams_creditsString;
- (id)ams_dictionaryByAddingEntriesFromDictionary:(id)dictionary;
- (id)ams_dictionaryRemovingKeys:(id)keys;
- (struct { id x0; id x1; id x2; })ams_encryptionResult;
- (long long)ams_errorCode;
- (id)ams_filterUsingTest:(id /* block */)test;
- (id)ams_firstKeyObjectPassingTest:(id /* block */)test;
- (id)ams_firstKeyPassingTest:(id /* block */)test;
- (id)ams_firstName;
- (id)ams_firstObjectPassingTest:(id /* block */)test;
- (signed char)ams_isManagedAppleID;
- (id)ams_keysForChangedValuesComparedToDictionary:(id)dictionary;
- (id)ams_lastName;
- (id)ams_mapWithTransform:(id /* block */)transform;
- (id)ams_objectForCaseInsensitiveKey:(id)key;
- (id)ams_objectForKey:(id)key defaultValue:(id)value;
- (id)ams_privacyAcknowledgement;
- (id)ams_sanitizedForSecureCoding;
- (id)ams_username;
- (id)ams_valuesForKeys:(id)keys;
- (id)hashedDescription;

@end

#endif /* _NSDictionary_AppleMediaServices_EncryptionResult_h */
