//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _NSMutableURLRequest_AppleMediaServices_h
#define _NSMutableURLRequest_AppleMediaServices_h

@import Foundation;

@interface NSMutableURLRequest (AppleMediaServices)

/* instance methods */
- (void)_addAbsintheHeadersFromPromise:(id)promise;
- (void)ams_addXTokenHeaderWithAccount:(id)account;
- (void)ams_addClientVersionsForClient:(id)client;
- (void)ams_addHeaders:(id)headers;
- (void)_ams_addCookies:(id)cookies;
- (void)_ams_replaceCookies:(id)cookies;
- (id)_ams_separateCookies:(id)cookies;
- (void)_syncAddHeadersFromPromise:(id)promise error:(id *)error;
- (void)ams_addABPayloadHeaderForTreatmentNamespace:(id)_namespace;
- (void)ams_addAbsintheHeaderRemotelyWithBuyParams:(id)params bag:(id)bag signingService:(id)service;
- (void)ams_addAbsintheHeadersWithBuyParams:(id)params bag:(id)bag;
- (void)ams_addAcceptLanguageHeader;
- (void)ams_addAnisetteHeadersForAccount:(id)account type:(long long)type bag:(id)bag;
- (void)ams_addAuthKitHeaders;
- (void)ams_addAuthorizationHeaderForAccount:(id)account;
- (void)ams_addBiometricsHeadersForAccount:(id)account options:(id)options;
- (void)ams_addCacheBusterParameterWithPreservedQueryEncoding:(signed char)encoding;
- (void)ams_addCachePolicyHeader;
- (void)ams_addClientIdentifierHeaderForClient:(id)client;
- (void)ams_addConnectionTypeHeader;
- (void)ams_addContentLengthHeaderForData:(id)data;
- (void)ams_addContentTypeHeaderForEncoding:(long long)encoding;
- (id)ams_addCookiesAsynchronouslyForAccount:(id)account clientInfo:(id)info bag:(id)bag cleanupGlobalCookies:(signed char)cookies;
- (void)ams_addCookiesForAccount:(id)account clientInfo:(id)info bag:(id)bag;
- (void)ams_addCookiesForAccount:(id)account clientInfo:(id)info bag:(id)bag cleanupGlobalCookies:(signed char)cookies;
- (void)ams_addForwardedForHeader;
- (void)ams_addGSTokenForAccount:(id)account identifier:(id)identifier;
- (void)ams_addGUIDParameterUsingBag:(id)bag preservingQueryEncoding:(signed char)encoding;
- (void)ams_addIdentifierHeadersForAccount:(id)account;
- (void)ams_addIssuingProcessHeader;
- (void)ams_addMMeClientInfoAndDeviceHeaders;
- (void)ams_addMescalHeaderWithType:(long long)type bag:(id)bag logKey:(id)key;
- (void)ams_addPrimaryiCloudIdentifierHeader;
- (void)ams_addRequestTimestampHeader;
- (void)ams_addRequestingProcessWithClient:(id)client;
- (void)ams_addSilentEnrollmentHeadersForAccount:(id)account;
- (void)ams_addStoreFrontHeaderForAccount:(id)account client:(id)client withBag:(id)bag;
- (void)ams_addTimezoneOffsetHeader;
- (void)ams_addUserAgentHeaderFromClient:(id)client;
- (void)ams_addXGroupDSIDsWithPrimaryAccount:(id)account andGroupAccounts:(id)accounts;
- (void)ams_removeAnisetteHeaders;
- (void)ams_setBodyParameters:(id)parameters encoding:(long long)encoding compressBody:(signed char)body error:(id *)error;

@end

#endif /* _NSMutableURLRequest_AppleMediaServices_h */
