//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _NSSet_AppleMediaServices_h
#define _NSSet_AppleMediaServices_h

@import Foundation;

@interface NSSet (AppleMediaServices)

/* class methods */
+ (id)ams_JSONClasses;
+ (id)ams_PLISTClasses;

/* instance methods */
- (id)ams_mapWithTransformIgnoresNil:(id /* block */)transformIgnoresNil;
- (signed char)ams_allWithTest:(id /* block */)test;
- (signed char)ams_anyWithTest:(id /* block */)test;
- (id)ams_filterUsingTest:(id /* block */)test;
- (id)ams_firstObjectPassingTest:(id /* block */)test;
- (id)ams_mapWithTransform:(id /* block */)transform;
- (id)ams_nonEmptyComponentsJoinedByString:(id)string;

@end

#endif /* _NSSet_AppleMediaServices_h */
