//
//   Generated by https://github.com/blacktop/ipsw (Version: , BuildCommit: )
//
//    - LC_BUILD_VERSION:  Platform: macOS, MinOS: 14.4, SDK: 14.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_BUILD_VERSION:  Platform: macCatalyst, MinOS: 17.4, SDK: 17.4, Tools: [ld (902.8), ld (854.1), ld (951.9)]
//    - LC_SOURCE_VERSION: 7.4.38.1.3
//
#ifndef _PKPaymentAuthorizationControllerDelegate_Protocol_h
#define _PKPaymentAuthorizationControllerDelegate_Protocol_h

@import Foundation;

@protocol PKPaymentAuthorizationControllerDelegate <NSObject>

@required

/* required instance methods */
- (void)paymentAuthorizationControllerDidFinish:(id)finish;
- (id)presentationWindowForPaymentAuthorizationController:(id)controller;

@optional

/* optional instance methods */
- (void)paymentAuthorizationController:(id)controller didRequestMerchantSessionUpdate:(id /* block */)update;
- (void)paymentAuthorizationController:(id)controller didSelectShippingMethod:(id)method handler:(id /* block */)handler;
- (void)paymentAuthorizationController:(id)controller didAuthorizePayment:(id)payment completion:(id /* block */)completion;
- (void)paymentAuthorizationController:(id)controller didAuthorizePayment:(id)payment handler:(id /* block */)handler;
- (void)paymentAuthorizationController:(id)controller didChangeCouponCode:(id)code handler:(id /* block */)handler;
- (void)paymentAuthorizationController:(id)controller didSelectPaymentMethod:(id)method completion:(id /* block */)completion;
- (void)paymentAuthorizationController:(id)controller didSelectPaymentMethod:(id)method handler:(id /* block */)handler;
- (void)paymentAuthorizationController:(id)controller didSelectShippingContact:(id)contact completion:(id /* block */)completion;
- (void)paymentAuthorizationController:(id)controller didSelectShippingContact:(id)contact handler:(id /* block */)handler;
- (void)paymentAuthorizationController:(id)controller didSelectShippingMethod:(id)method completion:(id /* block */)completion;
- (void)paymentAuthorizationControllerWillAuthorizePayment:(id)payment;

@end

#endif /* _PKPaymentAuthorizationControllerDelegate_Protocol_h */
